;;; hive-mcp-olympus.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(require 'clojure-elisp-runtime)

;;; Code:



(require 'olympus-ui)

(defalias 'hive-olympus (lambda ()
    "Open the Olympus grid UI."
    (interactive)
    (olympus-ui-show)
    (pop-to-buffer (get-buffer-create olympus-ui--buffer-name))))

(defalias 'hive-mcp-olympus-dashboard (lambda ()
    "Open the Olympus dashboard."
    (interactive)
    (olympus-ui-show)))

(provide 'hive-mcp-olympus)
;;; hive-mcp-olympus.el ends here
