;;; hive-mcp-swarm-events.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(require 'clojure-elisp-runtime)

;;; Code:



(require 'cl-lib)

(declare-function hive-mcp-channel-connected-p "hive-mcp-channel")

(declare-function hive-mcp-channel-send "hive-mcp-channel")

(declare-function hive-mcp-channel-dispatch-local "hive-mcp-channel")

(defvar hive-mcp-swarm-events--session-id nil
  "Current session ID for event correlation.")

(defun hive-mcp-swarm-events-channel-available-p ()
  "Check if the bidirectional channel is available and connected."
  (and (require 'hive-mcp-channel nil t) (fboundp 'hive-mcp-channel-connected-p) (hive-mcp-channel-connected-p)))

(defun hive-mcp-swarm-events-emit (event-type data)
  "Emit EVENT-TYPE with DATA through the channel if connected.\nEVENT-TYPE should be a string like \"task-completed\".\nDATA is an alist of additional event properties.\n\nEvents are both:\n1. Sent to MCP server via channel (if connected)\n2. Dispatched locally to elisp handlers (always)\n\nThis enables components like hive-mcp-olympus to react immediately\nto swarm events without waiting for server round-trip."
  (let* ((event (append (list (cons "type" event-type) (cons "timestamp" (truncate (float-time))) (cons "session-id" hive-mcp-swarm-events--session-id)) data)))
    (when (fboundp 'hive-mcp-channel-dispatch-local)
    (condition-case err
    (hive-mcp-channel-dispatch-local event-type event)
  (error (message "[swarm-events] Local dispatch error: %s" (error-message-string err)))))
    (when (hive-mcp-swarm-events-channel-available-p)
    (condition-case err
    (hive-mcp-channel-send event)
  (error (message "[swarm-events] Channel emit error: %s" (error-message-string err)))))))

(defun hive-mcp-swarm-events-emit-slave-spawned (slave-id name presets &optional cwd kanban-task-id)
  "Emit slave-spawned event for SLAVE-ID with NAME, PRESETS, CWD, and KANBAN-TASK-ID.\nCWD is the working directory of the slave (optional but recommended for\nregistry sync per ADR-001 Phase 2).\nKANBAN-TASK-ID is the optional kanban task this ling is linked to."
  (hive-mcp-swarm-events-emit "slave-spawned" (append (list (cons "slave-id" slave-id) (cons "name" name) (cons "presets" (or presets (list ))) (cons "cwd" (or cwd ""))) (when kanban-task-id
    (list (cons "kanban-task-id" kanban-task-id))))))

(defun hive-mcp-swarm-events-emit-slave-killed (slave-id)
  "Emit slave-killed event for SLAVE-ID."
  (hive-mcp-swarm-events-emit "slave-killed" (list (cons "slave-id" slave-id))))

(defun hive-mcp-swarm-events-emit-slave-ready (slave-id)
  "Emit slave-ready event for SLAVE-ID.\nThis signals that preset injection is complete and the slave is ready\nto receive dispatched tasks."
  (hive-mcp-swarm-events-emit "slave-ready" (list (cons "slave-id" slave-id))))

(defun hive-mcp-swarm-events-emit-task-completed (task-id slave-id result)
  "Emit task-completed event for TASK-ID from SLAVE-ID with RESULT."
  (hive-mcp-swarm-events-emit "task-completed" (list (cons "task-id" task-id) (cons "slave-id" slave-id) (cons "result" result))))

(defun hive-mcp-swarm-events-emit-task-failed (task-id slave-id error-msg)
  "Emit task-failed event for TASK-ID from SLAVE-ID with ERROR-MSG."
  (hive-mcp-swarm-events-emit "task-failed" (list (cons "task-id" task-id) (cons "slave-id" slave-id) (cons "error" error-msg))))

(defun hive-mcp-swarm-events-emit-prompt-shown (slave-id prompt-text)
  "Emit prompt-shown event for SLAVE-ID with PROMPT-TEXT."
  (hive-mcp-swarm-events-emit "prompt-shown" (list (cons "slave-id" slave-id) (cons "prompt" prompt-text))))

(defun hive-mcp-swarm-events-emit-state-changed (slave-id old-state new-state)
  "Emit state-changed event for SLAVE-ID from OLD-STATE to NEW-STATE."
  (hive-mcp-swarm-events-emit "state-changed" (list (cons "slave-id" slave-id) (cons "old-state" (symbol-name old-state)) (cons "new-state" (symbol-name new-state)))))

(defun hive-mcp-swarm-events-emit-auto-completed (slave-id duration-secs status)
  "Emit auto-completed event for SLAVE-ID with DURATION-SECS and STATUS.\nSTATUS should be a string like \"completed\", \"unknown\", etc.\nDURATION-SECS is the task duration in seconds (float)."
  (hive-mcp-swarm-events-emit "auto-completed" (list (cons "slave-id" slave-id) (cons "duration-secs" (or duration-secs 0)) (cons "status" (or status "completed")) (cons "detection-method" "terminal-ready-transition"))))

(defun hive-mcp-swarm-events-emit-auto-started (slave-id task-preview)
  "Emit auto-started event for SLAVE-ID with TASK-PREVIEW.\nTASK-PREVIEW is a truncated version of the task prompt (first 100 chars)."
  (hive-mcp-swarm-events-emit "auto-started" (list (cons "slave-id" slave-id) (cons "task-preview" (or task-preview "")) (cons "detection-method" "terminal-send"))))

(defun hive-mcp-swarm-events-emit-auto-error (slave-id duration-secs error-type error-preview)
  "Emit auto-error event for SLAVE-ID with error details.\nDURATION-SECS is the task duration before error (float).\nERROR-TYPE is a string like \"cli-error\", \"tool-error\", \"timeout\".\nERROR-PREVIEW is a truncated version of the error text (first 200 chars)."
  (hive-mcp-swarm-events-emit "auto-error" (list (cons "slave-id" slave-id) (cons "duration-secs" (or duration-secs 0)) (cons "error-type" (or error-type "unknown")) (cons "error-preview" (or error-preview "")) (cons "detection-method" "terminal-pattern-match"))))

(defun hive-mcp-swarm-events-emit-idle-timeout (slave-id idle-duration-secs)
  "Emit idle-timeout event for SLAVE-ID (Layer 2 convergence).\nIDLE-DURATION-SECS is how long the slave has been idle (float)."
  (hive-mcp-swarm-events-emit "idle-timeout" (list (cons "slave-id" slave-id) (cons "idle-duration-secs" (or idle-duration-secs 0)) (cons "detection-method" "terminal-introspection") (cons "layer" 2) (cons "convergence-pattern" "4-layer-convergence"))))

(defun hive-mcp-swarm-events-emit-prompt-stall (slave-id idle-duration-secs prompt-text)
  "Emit prompt-stall event for SLAVE-ID (Layer 2 convergence).\nIDLE-DURATION-SECS is how long the slave has been idle (float).\nPROMPT-TEXT is the pending prompt text (truncated if long).\nThis event is URGENT - the coordinator needs to respond."
  (hive-mcp-swarm-events-emit "prompt-stall" (list (cons "slave-id" slave-id) (cons "idle-duration-secs" (or idle-duration-secs 0)) (cons "prompt-preview" (if (> (length prompt-text) 100) (concat (substring prompt-text 0 97) "...") prompt-text)) (cons "detection-method" "idle-with-pending-prompt") (cons "layer" 2) (cons "convergence-pattern" "4-layer-convergence") (cons "urgency" "high"))))

(defun hive-mcp-swarm-events-emit-ling-ready-for-wrap (slave-id reason)
  "Emit ling-ready-for-wrap event for SLAVE-ID with REASON.\nREASON is a string describing why wrap is triggered."
  (hive-mcp-swarm-events-emit "ling-ready-for-wrap" (list (cons "slave-id" slave-id) (cons "reason" (or reason "task-completed")) (cons "session-id" hive-mcp-swarm-events--session-id))))

(defun hive-mcp-swarm-events-emit-dispatch-dropped (slave-id reason prompt-preview retries queued-at)
  "Emit dispatch-dropped event for SLAVE-ID with failure details.\nREASON is a string describing why the dispatch was dropped.\nPROMPT-PREVIEW is a truncated version of the prompt (first 100 chars).\nRETRIES is the number of retry attempts made.\nQUEUED-AT is the epoch time when the dispatch was queued."
  (let* ((wait-time (- (float-time) (or queued-at (float-time)))))
    (hive-mcp-swarm-events-emit "dispatch-dropped" (list (cons "slave-id" slave-id) (cons "reason" (or reason "unknown")) (cons "prompt-preview" (if (> (length prompt-preview) 100) (concat (substring prompt-preview 0 97) "...") prompt-preview)) (cons "retries" (or retries 0)) (cons "queued-at" (or queued-at 0)) (cons "wait-time-secs" wait-time) (cons "urgency" "high")))))

(defun hive-mcp-swarm-events-set-session-id (session-id)
  "Set the SESSION-ID for event correlation."
  (setq hive-mcp-swarm-events--session-id session-id))

(defun hive-mcp-swarm-events-get-session-id ()
  "Get the current session ID."
  hive-mcp-swarm-events--session-id)

(defun hive-mcp-swarm-events-init (session-id)
  "Initialize events module with SESSION-ID."
  (setq hive-mcp-swarm-events--session-id session-id))

(defun hive-mcp-swarm-events-shutdown ()
  "Shutdown events module."
  (setq hive-mcp-swarm-events--session-id nil))

(provide 'hive-mcp-swarm-events)
;;; hive-mcp-swarm-events.el ends here
