;;; hive-mcp-kanban.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(require 'clojure-elisp-runtime)
(require 'hive-mcp-memory)
(require 'seq)

;;; Code:



(defconst statuses '("todo" "doing" "review" "done") "Valid kanban task statuses.")

(defconst priorities '("high" "medium" "low") "Valid kanban task priorities.")

(defun hive-mcp-kanban---timestamp ()
  "Return current ISO 8601 timestamp."
  (format-time-string "%FT%T%z"))

(defun hive-mcp-kanban---build-tags (status priority)
  "Build tags list from STATUS and PRIORITY."
  (list "kanban" status (format "priority-%s" priority)))

(defun hive-mcp-kanban---build-tags-with-scope (status priority project-id)
  "Build tags list from STATUS, PRIORITY, and PROJECT-ID.\nIncludes scope tag for project isolation.\nIf PROJECT-ID is nil, falls back to current project."
  (let* ((base-tags (hive-mcp-kanban--build-tags status priority))
        (effective-project (or project-id (hive-mcp-memory--project-id)))
        (scope-tag (hive-mcp-memory--make-scope-tag 'project effective-project)))
    (append base-tags (list scope-tag))))

(defun hive-mcp-kanban---extract-scope (entry)
  "Extract scope tag from ENTRY tags.\nReturns the scope tag string, or nil if not found."
  (let* ((tags (plist-get entry :tags)))
    (seq-find (lambda (tag)
    (string-prefix-p "scope:" tag)) tags)))

(defun hive-mcp-kanban---is-kanban-entry-p (entry)
  "Return non-nil if ENTRY is a kanban task."
  (let* ((content (plist-get entry :content)))
    (and (plistp content) (string= (plist-get content :task-type) "kanban"))))

(defun hive-mcp-kanban-task-create (title &optional priority context project-id)
  "Create a kanban task in memory with short-term duration.\nTITLE is required. PRIORITY defaults to medium. CONTEXT is optional notes.\nPROJECT-ID specifies the project (defaults to current).\nReturns the created entry with scope tag for project isolation."
  (let* ((prio (or priority "medium"))
        (status "todo")
        (content (list :task-type "kanban" :title title :status status :priority prio :created (hive-mcp-kanban--timestamp) :started nil :context context))
        (tags (hive-mcp-kanban--build-tags-with-scope status prio project-id)))
    (unless (member prio hive-mcp-kanban-priorities)
    (error "Invalid priority: %s. Must be one of %s" prio hive-mcp-kanban-priorities))
    (hive-mcp-memory-add 'note content tags project-id 'short-term)))

(defun hive-mcp-kanban-task-move (task-id new-status &optional project-id)
  "Move task TASK-ID to NEW-STATUS. If done, delete task.\nValid statuses: todo, doing, review, done.\nPROJECT-ID specifies the project (defaults to current).\nReturns the updated entry, or t if deleted (done)."
  (unless (member new-status hive-mcp-kanban-statuses)
    (error "Invalid status: %s. Must be one of %s" new-status hive-mcp-kanban-statuses))
  (let* ((entry (hive-mcp-memory-get task-id project-id)))
    (unless entry
    (error "Task not found: %s" task-id))
    (unless (hive-mcp-kanban--is-kanban-entry-p entry)
    (error "Entry is not a kanban task: %s" task-id))
    (if (string= new-status "done") (progn
  (hive-mcp-memory-delete task-id project-id)
  t) (let* ((content (plist-get entry :content))
        (priority (plist-get content :priority))
        (new-content (plist-put (copy-sequence content) :status new-status))
        (existing-scope (hive-mcp-kanban--extract-scope entry))
        (new-tags (if existing-scope (append (hive-mcp-kanban--build-tags new-status priority) (list existing-scope)) (hive-mcp-kanban--build-tags-with-scope new-status priority project-id))))
    (when (string= new-status "doing")
    (setq new-content (plist-put new-content :started (hive-mcp-kanban--timestamp))))
    (hive-mcp-memory-update task-id (list :content new-content :tags new-tags) project-id)
    (hive-mcp-memory-get task-id project-id)))))

(defun hive-mcp-kanban-task-delete (task-id &optional project-id)
  "Delete task TASK-ID from memory.\nPROJECT-ID specifies the project (defaults to current).\nReturns t if deleted, nil if not found."
  (hive-mcp-memory-delete task-id project-id))

(defun hive-mcp-kanban-list-all (&optional project-id)
  "List all kanban tasks for the specified project.\nPROJECT-ID specifies the project (defaults to current).\nReturns list of entries sorted by priority (high first).\nOnly returns tasks scoped to the specified project."
  (let* ((effective-project (or project-id (hive-mcp-memory--project-id)))
        (scope-filter (hive-mcp-memory--make-scope-tag 'project effective-project))
        (entries (hive-mcp-memory-query 'note '("kanban") project-id nil nil scope-filter))
        (kanban-entries (seq-filter #'-is-kanban-entry-p entries)))
    (clel-sort kanban-entries (lambda (a b)
    (let* ((prio-a (plist-get (plist-get a :content) :priority))
        (prio-b (plist-get (plist-get b :content) :priority)))
    (< (seq-position hive-mcp-kanban-priorities prio-a) (seq-position hive-mcp-kanban-priorities prio-b)))))))

(defun hive-mcp-kanban-list-by-status (status &optional project-id)
  "List tasks by STATUS (todo, doing, review) for the specified project.\nPROJECT-ID specifies the project (defaults to current).\nReturns list of entries for that status, scoped to the project."
  (unless (member status hive-mcp-kanban-statuses)
    (error "Invalid status: %s" status))
  (when (string= status "done")
    (error "Cannot list 'done' tasks - they are deleted on completion"))
  (let* ((effective-project (or project-id (hive-mcp-memory--project-id)))
        (scope-filter (hive-mcp-memory--make-scope-tag 'project effective-project))
        (entries (hive-mcp-memory-query 'note (list "kanban" status) project-id nil nil scope-filter)))
    (seq-filter #'-is-kanban-entry-p entries)))

(defun hive-mcp-kanban-stats (&optional project-id)
  "Return task counts by status.\nPROJECT-ID specifies the project (defaults to current).\nReturns plist with :todo, :doing, :review counts."
  (let* ((all-tasks (hive-mcp-kanban-list-all project-id))
        (counts (list :todo 0 :doing 0 :review 0)))
    (dolist (task all-tasks)
    (let* ((content (plist-get task :content))
        (status (plist-get content :status))
        (key (intern (concat ":" status))))
    (plist-put counts key (1+ (plist-get counts key)))))
    counts))

(defun hive-mcp-kanban-task-update (task-id &optional title priority context project-id)
  "Update task TASK-ID with new TITLE, PRIORITY, or CONTEXT.\nOnly provided fields are updated.\nPROJECT-ID specifies the project (defaults to current).\nReturns the updated entry."
  (let* ((entry (hive-mcp-memory-get task-id project-id)))
    (unless entry
    (error "Task not found: %s" task-id))
    (unless (hive-mcp-kanban--is-kanban-entry-p entry)
    (error "Entry is not a kanban task: %s" task-id))
    (let* ((content (copy-sequence (plist-get entry :content)))
        (current-status (plist-get content :status))
        (new-priority (or priority (plist-get content :priority))))
    (when priority
    (unless (member priority hive-mcp-kanban-priorities)
    (error "Invalid priority: %s" priority)))
    (when title
    (setq content (plist-put content :title title)))
    (when priority
    (setq content (plist-put content :priority priority)))
    (when context
    (setq content (plist-put content :context context)))
    (let* ((existing-scope (hive-mcp-kanban--extract-scope entry))
        (new-tags (if existing-scope (append (hive-mcp-kanban--build-tags current-status new-priority) (list existing-scope)) (hive-mcp-kanban--build-tags-with-scope current-status new-priority project-id))))
    (hive-mcp-memory-update task-id (list :content content :tags new-tags) project-id))
    (hive-mcp-memory-get task-id project-id))))

(provide 'hive-mcp-kanban)
;;; hive-mcp-kanban.el ends here
