;;; hive-mcp-cider-nrepl.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(eval-and-compile (require 'clojure-elisp-runtime))

;;; Code:



(require 'cl-lib)

(defcustom hive-mcp-cider-nrepl-port 7910
  "Default port for nREPL server."
  :group 'hive-mcp-cider
  :type 'integer)

(defcustom hive-mcp-cider-nrepl-project-dir nil
  "Project directory for starting nREPL.\nIf nil, callers MUST supply project-dir explicitly (no project-current\nfallback — the Emacs daemon's current buffer is rarely the right project\nwhen spawn is triggered from an MCP tool boundary)."
  :group 'hive-mcp-cider
  :type '(choice (const nil) directory))

(defcustom hive-mcp-cider-nrepl-cljel-project-dir "~/PP/clojure-elisp"
  "Project directory for ClojureElisp nREPL sessions.\nShould point to the clojure-elisp project root with deps.edn\ncontaining the compiler and nREPL middleware."
  :group 'hive-mcp-cider
  :type 'directory)

(defcustom hive-mcp-cider-nrepl-shadow-build ":app"
  "Default shadow-cljs build ID."
  :group 'hive-mcp-cider
  :type 'string)

(defcustom hive-mcp-cider-nrepl-version "1.7.0"
  "nREPL version for inline -Sdeps spawn."
  :group 'hive-mcp-cider
  :type 'string)

(defcustom hive-mcp-cider-nrepl-cider-nrepl-version "0.58.0"
  "cider-nrepl version for inline -Sdeps spawn."
  :group 'hive-mcp-cider
  :type 'string)

(defvar hive-mcp-cider-nrepl--default-process nil
  "Process object for the auto-started default nREPL server.")

(defun hive-mcp-cider-nrepl-build-command (repl-type port dir)
  "Build the nREPL start command for REPL-TYPE on PORT in DIR.\nReturns a list of (program . args) for start-process.\nREPL-TYPE is one of 'clj, 'cljs, or 'cljel.\nUses inline -Sdeps so spawn works in any project without requiring a :nrepl alias.\nThis is a pure function — no side effects."
  (let* ((port-str (number-to-string port))
        (clj-deps (format "{:deps {nrepl/nrepl {:mvn/version \"%s\"} cider/cider-nrepl {:mvn/version \"%s\"}}}" hive-mcp-cider-nrepl-version hive-mcp-cider-nrepl-cider-nrepl-version))
        (cljel-deps (format "{:deps {nrepl/nrepl {:mvn/version \"%s\"} cider/cider-nrepl {:mvn/version \"%s\"} io.github.BuddhiLW/clojure-elisp {:local/root \"%s\"}}}" hive-mcp-cider-nrepl-version hive-mcp-cider-nrepl-cider-nrepl-version (expand-file-name hive-mcp-cider-nrepl-cljel-project-dir))))
    (pcase repl-type
  ((quote cljs) (list "npx" "shadow-cljs" "watch" hive-mcp-cider-nrepl-shadow-build))
  ((quote cljel) (list "clojure" "-Sdeps" cljel-deps "-M" "-m" "nrepl.cmdline" "--port" port-str "--middleware" "[cider.nrepl/cider-middleware,clojure-elisp.nrepl/wrap-cljel]"))
  (_ (list "clojure" "-Sdeps" clj-deps "-M" "-m" "nrepl.cmdline" "--port" port-str "--middleware" "[cider.nrepl/cider-middleware]")))))

(defun hive-mcp-cider-nrepl-project-dir (repl-type)
  "Resolve the project directory for REPL-TYPE.\nReturns absolute path string, or nil if no explicit dir is configured.\n\nFor 'cljel — falls back to `hive-mcp-cider-nrepl-cljel-project-dir'\ndefcustom (the cljel toolchain has a single canonical project).\n\nFor 'clj/'cljs — returns nil if `hive-mcp-cider-nrepl-project-dir' is\nunset. Callers must supply project-dir explicitly. The Emacs daemon's\ncurrent buffer is NOT a reliable proxy when spawn is triggered from an\nMCP tool boundary — it leaks hive-mcp into every other project's REPL."
  (or hive-mcp-cider-nrepl-project-dir (when (eq repl-type 'cljel)
    (expand-file-name hive-mcp-cider-nrepl-cljel-project-dir))))

(defun hive-mcp-cider-nrepl-port-open-p (port)
  "Check if PORT is accepting connections on localhost.\nReturns t if port is open, nil otherwise."
  (condition-case nil
    (let* ((proc (make-network-process :name "nrepl-check" :host "localhost" :service port :nowait nil)))
    (delete-process proc)
    t)
  (error nil)))

(defun hive-mcp-cider-nrepl-launch-process (name port repl-type &optional dir)
  "Start an nREPL process named NAME on PORT for REPL-TYPE.\nOptional DIR overrides the working directory.\nErrors if no dir can be resolved — explicit project routing only.\nReturns the process object."
  (let* ((resolved-dir (or dir (hive-mcp-cider-nrepl-project-dir repl-type))))
    (unless resolved-dir
    (error "hive-mcp-cider-nrepl: no project-dir for session '%s' (type=%s) — pass project-dir explicitly or set `hive-mcp-cider-nrepl-project-dir'" name (symbol-name repl-type)))
    (let* ((default-directory resolved-dir)
        (buf-name (format "*nREPL-%s*" name))
        (cmd (hive-mcp-cider-nrepl-build-command repl-type port resolved-dir)))
    (apply #'start-process (format "nrepl-%s" name) buf-name cmd))))

(defun hive-mcp-cider-nrepl-stop-process (process)
  "Kill a running nREPL process."
  (when (and process (process-live-p process))
    (kill-process process)))

(defun hive-mcp-cider-nrepl-start-default ()
  "Start the default nREPL server asynchronously.\nDoes not block Emacs startup. Uses `hive-mcp-cider-nrepl-port'."
  (let* ((default-directory (hive-mcp-cider-nrepl-project-dir 'clj))
        (port (number-to-string hive-mcp-cider-nrepl-port)))
    (message "hive-mcp-cider-nrepl: Starting on port %s in %s..." port default-directory)
    (setq hive-mcp-cider-nrepl--default-process (start-process "nrepl-server" "*nREPL-server*" "clojure" "-M:dev" "-m" "nrepl.cmdline" "--port" port "--middleware" "[cider.nrepl/cider-middleware,refactor-nrepl.middleware/wrap-refactor]"))))

(defun hive-mcp-cider-nrepl-stop-default ()
  "Stop the default nREPL server."
  (hive-mcp-cider-nrepl-stop-process hive-mcp-cider-nrepl--default-process)
  (setq hive-mcp-cider-nrepl--default-process nil)
  (message "hive-mcp-cider-nrepl: Default server stopped"))

(provide 'hive-mcp-cider-nrepl)
;;; hive-mcp-cider-nrepl.el ends here
