;;; hive-mcp-workflow-ui.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(eval-and-compile (require 'clojure-elisp-runtime))

;;; Code:



(require 'hive-mcp-channel-ws)

(defgroup hive-mcp-workflow-ui nil
  "Live workflow FSM state-tree preview."
  :group 'hive-mcp
  :prefix "hive-mcp-workflow-ui-")

(defcustom hive-mcp-workflow-ui-buffer-name "*Workflow Progress*"
  "Name of the roster buffer showing all workflow runs."
  :group 'hive-mcp-workflow-ui
  :type 'string)

(defcustom hive-mcp-workflow-ui-auto-pop nil
  "When non-nil, pop the roster buffer on the first workflow frame."
  :group 'hive-mcp-workflow-ui
  :type 'boolean)

(defcustom hive-mcp-workflow-ui-max-runs 24
  "Maximum number of runs retained in the roster before pruning oldest."
  :group 'hive-mcp-workflow-ui
  :type 'integer)

(defface hive-mcp-workflow-ui-run '((t :foreground "cyan" :weight bold)) "Face for a run-id header." :group 'hive-mcp-workflow-ui)

(defface hive-mcp-workflow-ui-started '((t :foreground "deep sky blue")) "Face for the started phase." :group 'hive-mcp-workflow-ui)

(defface hive-mcp-workflow-ui-step '((t :foreground "gold")) "Face for the step phase." :group 'hive-mcp-workflow-ui)

(defface hive-mcp-workflow-ui-completed '((t :foreground "green" :weight bold)) "Face for the completed phase." :group 'hive-mcp-workflow-ui)

(defface hive-mcp-workflow-ui-failed '((t :foreground "red" :weight bold)) "Face for the failed phase." :group 'hive-mcp-workflow-ui)

(defface hive-mcp-workflow-ui-current '((t :foreground "white" :weight bold)) "Face for the current (active) state in the trace tree." :group 'hive-mcp-workflow-ui)

(defface hive-mcp-workflow-ui-trace '((t :foreground "gray60")) "Face for prior states in the trace tree." :group 'hive-mcp-workflow-ui)

(defface hive-mcp-workflow-ui-meta '((t :foreground "gray50" :height 0.9)) "Face for metadata (status, separators)." :group 'hive-mcp-workflow-ui)

(defface hive-mcp-workflow-ui-wave '((t :foreground "medium purple" :weight bold)) "Face for the drone-parity wave line." :group 'hive-mcp-workflow-ui)

(defface hive-mcp-workflow-ui-roster '((t :foreground "light steel blue")) "Face for an in-flight roster entry (task-id)." :group 'hive-mcp-workflow-ui)

(defvar hive-mcp-workflow-ui--runs (make-hash-table :test 'equal)
  "Hash table run-id (string) -> alist of latest frame fields.")

(defvar hive-mcp-workflow-ui--order '()
  "List of run-ids in first-seen order (oldest first).")

(defun hive-mcp-workflow-ui--as-string (x)
  "Coerce X to a string, empty string for nil."
  (if (and x (stringp x)) x (if x (format "%s" x) "")))

(defun hive-mcp-workflow-ui--field (msg key)
  "Read KEY (symbol) from an alist MSG, tolerating string keys."
  (or (alist-get key msg) (cdr (assoc (symbol-name key) msg))))

(defun hive-mcp-workflow-ui--phase-face (phase)
  "Return the face for PHASE string."
  (cond
  ((string= phase "started") 'hive-mcp-workflow-ui-started)
  ((string= phase "step") 'hive-mcp-workflow-ui-step)
  ((string= phase "completed") 'hive-mcp-workflow-ui-completed)
  ((string= phase "failed") 'hive-mcp-workflow-ui-failed)
  ((string= phase "wave") 'hive-mcp-workflow-ui-wave)
  (t 'hive-mcp-workflow-ui-step)))

(defun hive-mcp-workflow-ui--phase-glyph (phase)
  "Return a short glyph for PHASE string."
  (cond
  ((string= phase "started") "◐")
  ((string= phase "step") "▸")
  ((string= phase "completed") "✓")
  ((string= phase "failed") "✗")
  ((string= phase "wave") "⛭")
  (t "•")))

(defun hive-mcp-workflow-ui--short-state (state-id)
  "Strip the fsm namespace prefix from STATE-ID for compact display."
  (let* ((s (hive-mcp-workflow-ui--as-string state-id)))
    (if (string-prefix-p "hive.events.fsm/" s) (concat "::" (substring s (length "hive.events.fsm/"))) s)))

(defvar hive-mcp-workflow-ui-mode-map (let* ((map (make-sparse-keymap)))
    (define-key map "q" #'quit-window)
    (define-key map "g" #'hive-mcp-workflow-ui-redraw)
    (define-key map "c" #'hive-mcp-workflow-ui-clear)
    map)
  "Keymap for `hive-mcp-workflow-ui-mode'.")

(define-derived-mode hive-mcp-workflow-ui-mode special-mode "Workflow-UI" "Major mode for the live workflow FSM state-tree roster.\n\n\\{hive-mcp-workflow-ui-mode-map}" (setq buffer-read-only t) (setq truncate-lines t))

(defun hive-mcp-workflow-ui--seg-state (seg)
  "Return SEG's state-id (an alist entry) as a string."
  (hive-mcp-workflow-ui--as-string (hive-mcp-workflow-ui--field seg 'state-id)))

(defun hive-mcp-workflow-ui--trace-with-terminal (frame)
  "Return FRAME's trace segments, appending the terminal state as a final\nsegment when the run has completed/failed past the last recorded segment."
  (let* ((trace (alist-get 'trace-tail frame))
        (segs (if (listp trace) trace '()))
        (phase (hive-mcp-workflow-ui--as-string (alist-get 'phase frame)))
        (cur (hive-mcp-workflow-ui--as-string (alist-get 'state-id frame)))
        (terminal (or (string= phase "completed") (string= phase "failed")))
        (tail-state (if segs (hive-mcp-workflow-ui--seg-state (clel-last segs)) "")))
    (cond
  ((and (equal (length segs) 0) (> (length cur) 0)) (list (list (cons 'state-id cur) (cons 'status phase))))
  ((and terminal (> (length cur) 0) (not (string= cur tail-state))) (append segs (list (list (cons 'state-id cur) (cons 'status phase)))))
  (t segs))))

(defun hive-mcp-workflow-ui--render-wave (wave)
  "Insert WAVE's drone-parity line (dispatched/completed/failed) and the\nin-flight roster, nested under the current run node. WAVE is an alist carrying\n`dispatched', `completed', `failed' and `in-flight' — the last a list of\nalists shaped {task-id ling-id}."
  (let* ((dispatched (hive-mcp-workflow-ui--as-string (hive-mcp-workflow-ui--field wave 'dispatched)))
        (completed (hive-mcp-workflow-ui--as-string (hive-mcp-workflow-ui--field wave 'completed)))
        (failed (hive-mcp-workflow-ui--as-string (hive-mcp-workflow-ui--field wave 'failed)))
        (in-flight (hive-mcp-workflow-ui--field wave 'in-flight))
        (roster (if (listp in-flight) in-flight '())))
    (insert (propertize "  ⛭ drones " 'face 'hive-mcp-workflow-ui-wave))
    (insert (propertize (format "%s▸" (if (> (length dispatched) 0) dispatched "0")) 'face 'hive-mcp-workflow-ui-step))
    (insert (propertize (format "  %s✓" (if (> (length completed) 0) completed "0")) 'face 'hive-mcp-workflow-ui-completed))
    (insert (propertize (format "  %s✗" (if (> (length failed) 0) failed "0")) 'face 'hive-mcp-workflow-ui-failed))
    (insert "\n")
    (dolist (entry roster)
    (let* ((task (hive-mcp-workflow-ui--as-string (hive-mcp-workflow-ui--field entry 'task-id)))
        (ling (hive-mcp-workflow-ui--as-string (hive-mcp-workflow-ui--field entry 'ling-id))))
    (insert (propertize "    ◦ " 'face 'hive-mcp-workflow-ui-meta))
    (insert (propertize task 'face 'hive-mcp-workflow-ui-roster))
    (when (> (length ling) 0)
    (insert (propertize (format " → %s" ling) 'face 'hive-mcp-workflow-ui-trace)))
    (insert "\n")))))

(defun hive-mcp-workflow-ui--render-run (run-id frame)
  "Insert one run's section at point-max from its latest FRAME alist."
  (let* ((phase (hive-mcp-workflow-ui--as-string (alist-get 'phase frame)))
        (variant (hive-mcp-workflow-ui--as-string (alist-get 'variant frame)))
        (wave (alist-get 'wave frame))
        (label (cond
  ((> (length variant) 0) variant)
  ((> (length phase) 0) phase)
  (wave "wave")
  (t "")))
        (segs (hive-mcp-workflow-ui--trace-with-terminal frame))
        (n (length segs)))
    (insert (propertize (format "%s " (hive-mcp-workflow-ui--phase-glyph phase)) 'face (hive-mcp-workflow-ui--phase-face phase)))
    (insert (propertize (format "%s" run-id) 'face 'hive-mcp-workflow-ui-run))
    (insert (propertize (format "   %s\n" label) 'face (hive-mcp-workflow-ui--phase-face phase)))
    (let* ((i 0))
    (dolist (seg segs)
    (let* ((last (equal i (- n 1)))
        (branch (if last "  └ " "  ├ "))
        (st (hive-mcp-workflow-ui--short-state (hive-mcp-workflow-ui--field seg 'state-id)))
        (status (hive-mcp-workflow-ui--as-string (hive-mcp-workflow-ui--field seg 'status)))
        (face (if last 'hive-mcp-workflow-ui-current 'hive-mcp-workflow-ui-trace)))
    (insert (propertize branch 'face 'hive-mcp-workflow-ui-meta))
    (insert (propertize st 'face face))
    (when (> (length status) 0)
    (insert (propertize (format "   %s" status) 'face 'hive-mcp-workflow-ui-meta)))
    (insert "\n"))
    (setq i (+ i 1))))
    (when wave
    (hive-mcp-workflow-ui--render-wave wave))
    (insert "\n")))

(defun hive-mcp-workflow-ui--redraw-buffer ()
  "Re-render every run into the roster buffer from scratch."
  (let* ((buf (get-buffer-create hive-mcp-workflow-ui-buffer-name)))
    (with-current-buffer buf
    (unless (eq major-mode 'hive-mcp-workflow-ui-mode)
    (hive-mcp-workflow-ui-mode))
    (let* ((inhibit-read-only t)
        (pt (point)))
    (erase-buffer)
    (insert (propertize (format "Workflow Runs (%d)\n" (length hive-mcp-workflow-ui--order)) 'face 'hive-mcp-workflow-ui-run))
    (insert (propertize (concat (make-string 60 9472) "\n\n") 'face 'hive-mcp-workflow-ui-meta))
    (dolist (run-id hive-mcp-workflow-ui--order)
    (let* ((frame (gethash run-id hive-mcp-workflow-ui--runs)))
    (when frame
    (hive-mcp-workflow-ui--render-run run-id frame))))
    (goto-char (min pt (point-max))))
    (let* ((win (get-buffer-window buf)))
    (when win
    (set-window-point win (point-min)))))
    buf))

(defun hive-mcp-workflow-ui--prune ()
  "Drop oldest runs beyond `hive-mcp-workflow-ui-max-runs'."
  (while (> (length hive-mcp-workflow-ui--order) hive-mcp-workflow-ui-max-runs)
    (let* ((oldest (car hive-mcp-workflow-ui--order)))
    (setq hive-mcp-workflow-ui--order (cdr hive-mcp-workflow-ui--order))
    (remhash oldest hive-mcp-workflow-ui--runs))))

(defun hive-mcp-workflow-ui--ingest (run-id frame)
  "Store transition FRAME under RUN-ID, tracking first-seen order. Any existing\n`wave' (drone-roster) data on the run is carried over so a later transition\nframe does not wipe the roster panel."
  (let* ((existing (gethash run-id hive-mcp-workflow-ui--runs))
        (wave (and existing (alist-get 'wave existing)))
        (frame (if wave (cons (cons 'wave wave) frame) frame)))
    (unless existing
    (setq hive-mcp-workflow-ui--order (append hive-mcp-workflow-ui--order (list run-id))))
    (puthash run-id frame hive-mcp-workflow-ui--runs)
    (hive-mcp-workflow-ui--prune)))

(defun hive-mcp-workflow-ui--ingest-wave (run-id wave)
  "Merge WAVE (drone-roster alist) into RUN-ID's frame under the `wave' key,\npreserving any existing transition fields and first-seen order."
  (let* ((existing (gethash run-id hive-mcp-workflow-ui--runs))
        (base0 (if existing (assq-delete-all 'wave (copy-sequence existing)) '()))
        (base (if (alist-get 'phase base0) base0 (cons (cons 'phase "wave") base0)))
        (frame (cons (cons 'wave wave) base)))
    (unless existing
    (setq hive-mcp-workflow-ui--order (append hive-mcp-workflow-ui--order (list run-id))))
    (puthash run-id frame hive-mcp-workflow-ui--runs)
    (hive-mcp-workflow-ui--prune)))

(defun hive-mcp-workflow-ui--on-workflow-transition (msg)
  "Handle a `:workflow-transition' WebSocket frame MSG (alist)."
  (let* ((run-id (hive-mcp-workflow-ui--as-string (hive-mcp-workflow-ui--field msg 'run-id))))
    (when (> (length run-id) 0)
    (let* ((existed (gethash run-id hive-mcp-workflow-ui--runs))
        (frame (list (cons 'variant (hive-mcp-workflow-ui--field msg 'variant)) (cons 'phase (hive-mcp-workflow-ui--field msg 'phase)) (cons 'state-id (hive-mcp-workflow-ui--field msg 'state-id)) (cons 'from (hive-mcp-workflow-ui--field msg 'from)) (cons 'trace-tail (hive-mcp-workflow-ui--field msg 'trace-tail)))))
    (hive-mcp-workflow-ui--ingest run-id frame)
    (hive-mcp-workflow-ui--redraw-buffer)
    (when (and hive-mcp-workflow-ui-auto-pop (not existed))
    (display-buffer (get-buffer hive-mcp-workflow-ui-buffer-name)))))))

(defun hive-mcp-workflow-ui--on-workflow-wave (msg)
  "Handle a `:workflow-wave' WebSocket frame MSG (alist): drone parity counts\nand the in-flight roster for a dag-wave run, keyed by run-id (= dag plan-id)."
  (let* ((run-id (hive-mcp-workflow-ui--as-string (hive-mcp-workflow-ui--field msg 'run-id))))
    (when (> (length run-id) 0)
    (let* ((existed (gethash run-id hive-mcp-workflow-ui--runs))
        (wave (list (cons 'variant (hive-mcp-workflow-ui--field msg 'variant)) (cons 'dispatched (hive-mcp-workflow-ui--field msg 'dispatched)) (cons 'completed (hive-mcp-workflow-ui--field msg 'completed)) (cons 'failed (hive-mcp-workflow-ui--field msg 'failed)) (cons 'in-flight (hive-mcp-workflow-ui--field msg 'in-flight)))))
    (hive-mcp-workflow-ui--ingest-wave run-id wave)
    (hive-mcp-workflow-ui--redraw-buffer)
    (when (and hive-mcp-workflow-ui-auto-pop (not existed))
    (display-buffer (get-buffer hive-mcp-workflow-ui-buffer-name)))))))

(defun hive-mcp-workflow-ui-show ()
  "Open the live workflow FSM state-tree roster."
  (interactive)
  (display-buffer (hive-mcp-workflow-ui--redraw-buffer)))

(defun hive-mcp-workflow-ui-redraw ()
  "Re-render the roster buffer."
  (interactive)
  (hive-mcp-workflow-ui--redraw-buffer))

(defun hive-mcp-workflow-ui-clear ()
  "Forget all runs and clear the roster buffer."
  (interactive)
  (clrhash hive-mcp-workflow-ui--runs)
  (setq hive-mcp-workflow-ui--order '())
  (hive-mcp-workflow-ui--redraw-buffer))

(defun hive-mcp-workflow-ui-register-handlers ()
  "Register WebSocket handlers for live workflow state streaming."
  (when (fboundp 'hive-mcp-channel-ws-on)
    (hive-mcp-channel-ws-on "workflow-transition" #'hive-mcp-workflow-ui--on-workflow-transition)
    (hive-mcp-channel-ws-on "workflow-wave" #'hive-mcp-workflow-ui--on-workflow-wave)))

(hive-mcp-workflow-ui-register-handlers)

(provide 'hive-mcp-workflow-ui)

(provide 'hive-mcp-workflow-ui)
;;; hive-mcp-workflow-ui.el ends here
