;;; hive-mcp-olympus.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(eval-and-compile (require 'clojure-elisp-runtime))

;;; Code:



(require 'olympus-ui)

(defalias 'hive-olympus (lambda ()
    "Open the Olympus grid UI."
    (interactive)
    (olympus-ui-show)
    (pop-to-buffer (get-buffer-create olympus-ui--buffer-name))))

(defalias 'hive-mcp-olympus-dashboard (lambda ()
    "Open the Olympus dashboard."
    (interactive)
    (olympus-ui-show)))

(defvar hive-mcp-olympus-mode-map (make-sparse-keymap)
  "Keymap for `hive-mcp-olympus-mode'.")

(define-key hive-mcp-olympus-mode-map (kbd "C-c h o") #'hive-olympus)

(define-key hive-mcp-olympus-mode-map (kbd "C-c h n") #'hive-olympus)

(define-key hive-mcp-olympus-mode-map (kbd "C-c h A") #'olympus-ui-arrange-windows)

(define-minor-mode hive-mcp-olympus-mode
  "Global minor mode for Olympus grid keybindings and notifications.\nWhen enabled, provides C-c h o to open the Olympus grid."
  :global t
  :lighter " Olympus"
  :keymap hive-mcp-olympus-mode-map)

(provide 'hive-mcp-olympus)
;;; hive-mcp-olympus.el ends here
