;;; hive-mcp-cider-ui.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(eval-and-compile (require 'clojure-elisp-runtime))

;;; Code:



(require 'cl-lib)

(declare-function hive-mcp-cider-nrepl-start-default "hive-mcp-cider-nrepl")

(declare-function hive-mcp-cider-nrepl-stop-default "hive-mcp-cider-nrepl")

(declare-function hive-mcp-cider-connection-start-auto-connect "hive-mcp-cider-connection")

(declare-function hive-mcp-cider-memory-eval-with-context "hive-mcp-cider-memory")

(declare-function hive-mcp-cider-memory-save-last-result "hive-mcp-cider-memory")

(declare-function hive-mcp-cider-memory-save-defun "hive-mcp-cider-memory")

(declare-function hive-mcp-cider-memory-query-solutions "hive-mcp-cider-memory")

(declare-function hive-mcp-cider-memory-toggle-auto-log "hive-mcp-cider-memory")

(declare-function hive-mcp-cider-spawn-session "hive-mcp-cider")

(transient-define-prefix hive-mcp-cider-ui-transient ()
  "MCP integration menu for CIDER."
  ["hive-mcp + CIDER" ["nREPL Server" ("n" "Start nREPL (async)" hive-mcp-cider-nrepl-start-default) ("N" "Stop nREPL" hive-mcp-cider-nrepl-stop-default) ("c" "Auto-connect" hive-mcp-cider-connection-start-auto-connect)] ["Spawn" ("sc" "Spawn CLJ" (lambda ()
    (interactive)
    (hive-mcp-cider-spawn-session (clel-read-string "Name: ") 'clj))) ("ss" "Spawn CLJS" (lambda ()
    (interactive)
    (hive-mcp-cider-spawn-session (clel-read-string "Name: ") 'cljs))) ("sl" "Spawn CLJEL" (lambda ()
    (interactive)
    (hive-mcp-cider-spawn-session (clel-read-string "Name: ") 'cljel)))] ["Evaluate" ("e" "Eval with context" hive-mcp-cider-memory-eval-with-context)] ["Memory" ("s" "Save last result" hive-mcp-cider-memory-save-last-result) ("d" "Save defun" hive-mcp-cider-memory-save-defun) ("q" "Query solutions" hive-mcp-cider-memory-query-solutions)] ["Settings" ("L" "Toggle auto-log" hive-mcp-cider-memory-toggle-auto-log)]])

(define-minor-mode hive-mcp-cider-mode
  "Minor mode for hive-mcp integration with CIDER.\n\nProvides:\n- Save REPL results to memory\n- Query past solutions\n- Clojure-aware context\n\nNote: nREPL auto-start is handled by addon lifecycle hooks.\nSet `hive-mcp-cider-auto-start-nrepl' to t and load the addon."
  :init-value nil
  :lighter " MCP-Clj"
  :global t
  :group 'hive-mcp-cider
  (if hive-mcp-cider-mode (message "hive-mcp-cider mode enabled") (message "hive-mcp-cider mode disabled")))

(provide 'hive-mcp-cider-ui)
;;; hive-mcp-cider-ui.el ends here
