;;; hive-mcp-context.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(eval-and-compile
  (require 'clojure-elisp-runtime)
  (unless (and (boundp 'clel-runtime-version)
               (version<= "0.7.2" clel-runtime-version))
    (error "clojure-elisp-runtime %s is too old for this file (needs %s)"
           (if (boundp 'clel-runtime-version) clel-runtime-version "(pre-0.7.2)")
           "0.7.2")))

;;; Code:



(require 'project)

(require 'subr-x)

(defgroup hive-mcp-context nil
  "Context gathering settings for hive-mcp."
  :group 'hive-mcp
  :prefix "hive-mcp-context-")

(defvar hive-mcp-context-providers nil
  "Alist of (NAME . FUNCTION) for additional context providers.\nEach function should return a plist or nil.")

(defvar hive-mcp-context-gather-hook nil
  "Hook run when gathering context.  Can modify context plist.\nCalled with single argument: the context plist being built.")

(defun hive-mcp-context-register-provider (name fn)
  "Register context provider NAME calling FN."
  (setf (alist-get name hive-mcp-context-providers) fn))

(defun hive-mcp-context-buffer ()
  "Return current buffer context as plist."
  (list :name (buffer-name) :file (buffer-file-name) :mode (symbol-name major-mode) :modified (if (buffer-modified-p) t :false) :readonly (if buffer-read-only t :false) :point (point) :line (line-number-at-pos) :column (current-column) :size (buffer-size) :encoding (symbol-name buffer-file-coding-system)))

(defun hive-mcp-context-region ()
  "Return region context if active, nil otherwise."
  (when (use-region-p)
    (let* ((start (region-beginning))
        (end (region-end)))
    (list :active t :start start :end end :start-line (line-number-at-pos start) :end-line (line-number-at-pos end) :length (- end start) :text (buffer-substring-no-properties start end)))))

(defun hive-mcp-context-defun ()
  "Return current defun context if in a function."
  (save-excursion
    (condition-case nil
    (when (beginning-of-defun)
    (let* ((start (point))
        (name (hive-mcp-context--defun-name)))
    (end-of-defun)
    (list :name name :start-line (line-number-at-pos start) :end-line (line-number-at-pos) :start start :end (point) :text (buffer-substring-no-properties start (point)))))
  (error nil))))

(defun hive-mcp-context--defun-name ()
  "Extract name of defun at point."
  (save-excursion
    (beginning-of-defun)
    (cond
  ((looking-at "(def\\(?:un\\|n\\|method\\|macro\\|test\\)?\\s-+\\(\\(?:\\sw\\|\\s_\\)+\\)") (match-string-no-properties 1))
  ((looking-at "\\(?:async\\s-+\\)?def\\s-+\\([a-zA-Z_][a-zA-Z0-9_]*\\)") (match-string-no-properties 1))
  ((looking-at "\\(?:async\\s-+\\)?function\\s-+\\([a-zA-Z_$][a-zA-Z0-9_$]*\\)") (match-string-no-properties 1))
  ((looking-at "\\(?:pub\\s-+\\)?fn\\s-+\\([a-zA-Z_][a-zA-Z0-9_]*\\)") (match-string-no-properties 1))
  ((looking-at "func\\s-+\\(?:([^)]+)\\s-+\\)?\\([a-zA-Z_][a-zA-Z0-9_]*\\)") (match-string-no-properties 1))
  (t nil))))

(defun hive-mcp-context-project-root ()
  "Return project root directory or nil."
  (when-let* ((proj (project-current)))
    (hive-mcp-context-project-root proj)))

(defun hive-mcp-context-project ()
  "Return project context as plist."
  (when-let* ((root (hive-mcp-context-project-root)))
    (list :root root :name (file-name-nondirectory (directory-file-name root)) :type (hive-mcp-context--detect-project-type root))))

(defun hive-mcp-context--detect-project-type (root)
  "Detect project type based on marker files in ROOT."
  (cond
  ((file-exists-p (expand-file-name "deps.edn" root)) "clojure-deps")
  ((file-exists-p (expand-file-name "project.clj" root)) "clojure-lein")
  ((file-exists-p (expand-file-name "bb.edn" root)) "babashka")
  ((file-exists-p (expand-file-name "shadow-cljs.edn" root)) "clojurescript")
  ((file-exists-p (expand-file-name "package.json" root)) "node")
  ((file-exists-p (expand-file-name "Cargo.toml" root)) "rust")
  ((file-exists-p (expand-file-name "pyproject.toml" root)) "python")
  ((file-exists-p (expand-file-name "setup.py" root)) "python")
  ((file-exists-p (expand-file-name "go.mod" root)) "go")
  ((file-exists-p (expand-file-name "Makefile" root)) "make")
  ((file-exists-p (expand-file-name ".git" root)) "git")
  (t "unknown")))

(defun hive-mcp-context-git ()
  "Return git context as plist, nil if not in git repo."
  (when-let* ((root (hive-mcp-context-project-root)))
    (let* ((default-directory root))
    (when (file-directory-p (expand-file-name ".git" root))
    (list :branch (hive-mcp-context--git-current-branch) :dirty (if (hive-mcp-context--git-dirty-p) t :false) :staged (hive-mcp-context--git-staged-files) :modified (hive-mcp-context--git-modified-files) :recent-commits (hive-mcp-context--git-recent-commits 5))))))

(defun hive-mcp-context--git-current-branch ()
  "Return current git branch name."
  (let* ((result (string-trim (shell-command-to-string "git rev-parse --abbrev-ref HEAD 2>/dev/null"))))
    (unless (string-empty-p result)
    result)))

(defun hive-mcp-context--git-dirty-p ()
  "Return t if working tree has uncommitted changes."
  (not (string-empty-p (shell-command-to-string "git status --porcelain 2>/dev/null"))))

(defun hive-mcp-context--git-staged-files ()
  "Return list of staged file paths."
  (let* ((output (shell-command-to-string "git diff --cached --name-only 2>/dev/null")))
    (unless (string-empty-p output)
    (split-string (string-trim output) "\n" t))))

(defun hive-mcp-context--git-modified-files ()
  "Return list of modified (unstaged) file paths."
  (let* ((output (shell-command-to-string "git diff --name-only 2>/dev/null")))
    (unless (string-empty-p output)
    (split-string (string-trim output) "\n" t))))

(defun hive-mcp-context--git-recent-commits (n)
  "Return last N commit summaries."
  (let* ((output (shell-command-to-string (format "git log --oneline -n %d 2>/dev/null" n))))
    (unless (string-empty-p output)
    (split-string (string-trim output) "\n" t))))

(defun hive-mcp-context-language ()
  "Detect programming language from major mode."
  (let* ((pcase-dispatch-value-197 major-mode))
    (cond
  ((equal pcase-dispatch-value-197 'clojure-mode) "clojure")
  ((equal pcase-dispatch-value-197 'clojurescript-mode) "clojurescript")
  ((equal pcase-dispatch-value-197 'clojurec-mode) "clojure")
  ((equal pcase-dispatch-value-197 'emacs-lisp-mode) "elisp")
  ((equal pcase-dispatch-value-197 'lisp-mode) "common-lisp")
  ((equal pcase-dispatch-value-197 'scheme-mode) "scheme")
  ((equal pcase-dispatch-value-197 'python-mode) "python")
  ((equal pcase-dispatch-value-197 'python-ts-mode) "python")
  ((equal pcase-dispatch-value-197 'js-mode) "javascript")
  ((equal pcase-dispatch-value-197 'js2-mode) "javascript")
  ((equal pcase-dispatch-value-197 'typescript-mode) "typescript")
  ((equal pcase-dispatch-value-197 'typescript-ts-mode) "typescript")
  ((equal pcase-dispatch-value-197 'rust-mode) "rust")
  ((equal pcase-dispatch-value-197 'rust-ts-mode) "rust")
  ((equal pcase-dispatch-value-197 'go-mode) "go")
  ((equal pcase-dispatch-value-197 'go-ts-mode) "go")
  ((equal pcase-dispatch-value-197 'c-mode) "c")
  ((equal pcase-dispatch-value-197 'c++-mode) "c++")
  ((equal pcase-dispatch-value-197 'java-mode) "java")
  ((equal pcase-dispatch-value-197 'ruby-mode) "ruby")
  ((equal pcase-dispatch-value-197 'sh-mode) "shell")
  ((equal pcase-dispatch-value-197 'sql-mode) "sql")
  ((equal pcase-dispatch-value-197 'html-mode) "html")
  ((equal pcase-dispatch-value-197 'css-mode) "css")
  ((equal pcase-dispatch-value-197 'json-mode) "json")
  ((equal pcase-dispatch-value-197 'yaml-mode) "yaml")
  ((equal pcase-dispatch-value-197 'markdown-mode) "markdown")
  ((equal pcase-dispatch-value-197 'org-mode) "org")
  (t (replace-regexp-in-string "-mode$" "" (symbol-name major-mode))))))

(defun hive-mcp-context-full ()
  "Return complete current context for Claude.\nIncludes buffer, region, defun, project, git, and custom providers."
  (let* ((context (list :timestamp (format-time-string "%FT%T%z") :buffer (hive-mcp-context-buffer) :region (hive-mcp-context-region) :defun (hive-mcp-context-defun) :project (hive-mcp-context-project) :git (hive-mcp-context-git) :language (hive-mcp-context-language))))
    (dolist (provider hive-mcp-context-providers)
    (when-let* ((data (funcall (cdr provider))))
    (setq context (plist-put context (car provider) data))))
    (run-hook-with-args 'hive-mcp-context-gather-hook context)
    context))

(defun hive-mcp-context-current-line ()
  "Return current line content."
  (buffer-substring-no-properties (line-beginning-position) (line-end-position)))

(defun hive-mcp-context-surrounding-lines (&optional before after)
  "Return lines surrounding point.\nBEFORE and AFTER default to 5 lines each."
  (let* ((before-n (or before 5))
        (after-n (or after 5)))
    (save-excursion
    (let* ((current-line (line-number-at-pos))
        (start (progn
  (forward-line (- before-n))
  (line-beginning-position)))
        (end (progn
  (goto-char (point))
  (forward-line (+ before-n after-n 1))
  (line-end-position))))
    (list :current-line current-line :start-line (line-number-at-pos start) :end-line (line-number-at-pos end) :text (buffer-substring-no-properties start end))))))

(provide 'hive-mcp-context)

(provide 'hive-mcp-context)
;;; hive-mcp-context.el ends here
