;;; hive-mcp-cider.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(eval-and-compile (require 'clojure-elisp-runtime))
(let* ((this-dir (file-name-directory (or load-file-name buffer-file-name))))
    (add-to-list 'load-path (expand-file-name "cider" this-dir)))
(require 'hive-mcp-api)
(require 'hive-mcp-cider-sessions)
(require 'hive-mcp-cider-nrepl)
(require 'hive-mcp-cider-connection)
(require 'hive-mcp-cider-eval)
(require 'hive-mcp-cider-introspection)
(require 'hive-mcp-cider-memory)
(require 'hive-mcp-cider-ui)

;;; Code:



(defgroup hive-mcp-cider nil
  "Integration between CIDER and hive-mcp."
  :group 'cider
  :prefix "hive-mcp-cider-")

(defalias 'hive-mcp-cider-list-sessions 'hive-mcp-cider-sessions-list-all)

(defalias 'hive-mcp-cider-get-session 'hive-mcp-cider-sessions-lookup)

(defalias 'hive-mcp-cider-start-nrepl 'hive-mcp-cider-nrepl-start-default)

(defalias 'hive-mcp-cider-stop-nrepl 'hive-mcp-cider-nrepl-stop-default)

(defalias 'hive-mcp-cider-auto-connect 'hive-mcp-cider-connection-start-auto-connect)

(defalias 'hive-mcp-cider-eval-silent 'hive-mcp-cider-eval-eval-silent)

(defalias 'hive-mcp-cider-eval-explicit 'hive-mcp-cider-eval-eval-explicit)

(defalias 'hive-mcp-cider-eval-in-session 'hive-mcp-cider-eval-eval-in-session)

(defalias 'hive-mcp-cider-status 'hive-mcp-cider-introspection-status)

(defalias 'hive-mcp-cider-doc 'hive-mcp-cider-introspection-doc)

(defalias 'hive-mcp-cider-apropos 'hive-mcp-cider-introspection-apropos)

(defalias 'hive-mcp-cider-info 'hive-mcp-cider-introspection-info)

(defalias 'hive-mcp-cider-complete 'hive-mcp-cider-introspection-complete)

(defalias 'hive-mcp-cider-save-last-result 'hive-mcp-cider-memory-save-last-result)

(defalias 'hive-mcp-cider-save-defun 'hive-mcp-cider-memory-save-defun)

(defalias 'hive-mcp-cider-query-solutions 'hive-mcp-cider-memory-query-solutions)

(defalias 'hive-mcp-cider-eval-with-context 'hive-mcp-cider-memory-eval-with-context)

(defalias 'hive-mcp-cider-toggle-auto-log 'hive-mcp-cider-memory-toggle-auto-log)

(defalias 'hive-mcp-cider-transient 'hive-mcp-cider-ui-transient)

(defun hive-mcp-cider-spawn-session-from-plist (params)
  "Spawn a new CIDER session from a structured request plist.\nMCP entry point — named params prevent positional arg ordering bugs.\nPARAMS is a plist with keys :name, :repl-type, :port, :project-dir, :agent-id.\nDelegates to spawn-session after destructuring."
  (hive-mcp-cider-spawn-session (plist-get params :name) (plist-get params :repl-type) (plist-get params :port) (plist-get params :project-dir) (plist-get params :agent-id)))

(defun hive-mcp-cider-spawn-session (name &optional repl-type port project-dir agent-id)
  "Spawn a new named CIDER session with its own nREPL server.\nNAME is the session identifier (e.g., \"agent-1\", \"task-render\").\nREPL-TYPE is one of 'clj (default), 'cljs, or 'cljel.\nPORT is the nREPL port (default: auto-assign from session range).\nPROJECT-DIR is the directory to start nREPL in (default: current project).\nAGENT-ID optionally links this session to a swarm agent."
  (interactive "sSession name: ")
  (let* ((rtype (or repl-type 'clj))
        (the-port (or port (hive-mcp-cider-sessions-find-available-port #'hive-mcp-cider-nrepl-port-open-p)))
        (dir (or project-dir (hive-mcp-cider-nrepl-project-dir rtype)))
        (process (hive-mcp-cider-nrepl-launch-process name the-port rtype dir))
        (timer (run-with-timer 2 1 (lambda ()
    (condition-case err
    (hive-mcp-cider-connection-try-connect-session name)
  (error (message "[cider] Timer error connecting session %s: %s" name (error-message-string err))))))))
    (hive-mcp-cider-sessions-register name (hive-mcp-cider-sessions-make-session the-port :process process :buffer (format "*nREPL-%s*" name) :agent-id agent-id :project-dir dir :repl-type rtype :status 'starting :timer timer))
    (message "hive-mcp-cider: Spawning %s session '%s' on port %d..." (symbol-name rtype) name the-port)
    (list :name name :port the-port :repl-type (symbol-name rtype) :status "starting")))

(defun hive-mcp-cider-connect-session (name host port &optional repl-type agent-id project-dir)
  "Connect to an existing nREPL server as a named session.\nNAME is the session identifier.\nHOST is the nREPL host (default \"localhost\").\nPORT is the nREPL port number.\nREPL-TYPE is one of \"clj\" (default), \"cljs\", or \"cljel\".\nAGENT-ID optionally links this session to a swarm agent.\nPROJECT-DIR (optional) labels the REPL buffer with the target project\nso cross-project sessions don't all collide under the current buffer's\nproject root.\n\nConnection is deferred to Emacs event loop to avoid blocking emacsclient."
  (interactive "sSession name: \nsHost (localhost): \nnPort: ")
  (let* ((host (or host "localhost"))
        (rtype (or (and repl-type (intern repl-type)) 'clj))
        (expanded-dir (and project-dir (file-name-as-directory (expand-file-name project-dir)))))
    (hive-mcp-cider-sessions-register name (hive-mcp-cider-sessions-make-session port :agent-id agent-id :repl-type rtype :project-dir expanded-dir :status 'connecting))
    (condition-case err
    (let* ((default-directory (or expanded-dir default-directory))
        (conn (hive-mcp-cider-connection-connect-deferred rtype port expanded-dir))
        (cider-buf (buffer-name conn)))
    (hive-mcp-cider-sessions-update-props name :status 'connected :cider-buffer cider-buf)
    (message "hive-mcp-cider: Session '%s' (%s) connected to %s:%d" name (symbol-name rtype) host port)
    (list :name name :port port :repl-type (symbol-name rtype) :status "connected"))
  (error (hive-mcp-cider-sessions-update-prop name :status 'error)
      (error "Session '%s' connect failed: %s" name (error-message-string err))))))

(defun hive-mcp-cider-kill-session (name)
  "Kill the CIDER session NAME — stops process and cleans up."
  (interactive (list (completing-read "Kill session: " (hive-mcp-cider-sessions-names))))
  (let* ((session (hive-mcp-cider-sessions-lookup name)))
    (when session
    (when-let* ((timer (plist-get session :timer)))
    (when (timerp timer)
    (cancel-timer timer)))
    (when-let* ((cider-buf (plist-get session :cider-buffer)))
    (when (get-buffer cider-buf)
    (with-current-buffer cider-buf
    (when (fboundp 'cider-quit)
    (cider-quit)))))
    (hive-mcp-cider-nrepl-stop-process (plist-get session :process))
    (hive-mcp-cider-sessions-unregister name)
    (message "hive-mcp-cider: Session '%s' killed" name))))

(defun hive-mcp-cider-kill-all-sessions ()
  "Kill all CIDER sessions."
  (interactive)
  (dolist (name (hive-mcp-cider-sessions-names))
    (hive-mcp-cider-kill-session name))
  (hive-mcp-cider-sessions-clear-all)
  (message "hive-mcp-cider: All sessions killed"))

(defun hive-mcp-cider--addon-init ()
  "Synchronous init for cider addon."
  (if (not (featurep 'cider)) (message "hive-mcp-cider: cider package not found, addon disabled") (require 'hive-mcp-api nil t)))

(defun hive-mcp-cider--addon-async-init ()
  "Asynchronous init — starts nREPL in background if configured."
  (when (bound-and-true-p hive-mcp-cider-nrepl-auto-start)
    (hive-mcp-cider-nrepl-start-default)
    (when hive-mcp-cider-connection-auto-connect
    (hive-mcp-cider-connection-start-auto-connect))
    hive-mcp-cider-nrepl--default-process))

(defun hive-mcp-cider--addon-shutdown ()
  "Shutdown — stops nREPL server and cleans up timers."
  (hive-mcp-cider-connection-stop-auto-connect)
  (hive-mcp-cider-nrepl-stop-default)
  (message "hive-mcp-cider: shutdown complete"))

(with-eval-after-load 'hive-mcp-addons
  (hive-mcp-addon-register 'cider :version "0.4.0" :description "Integration with CIDER (Clojure IDE) - multi-REPL (CLJ/CLJS/CLJEL)" :requires '(cider hive-mcp-api) :provides '(hive-mcp-cider-mode hive-mcp-cider-transient) :init #'hive-mcp-cider--addon-init :async-init #'hive-mcp-cider--addon-async-init :shutdown #'hive-mcp-cider--addon-shutdown))

(provide 'hive-mcp-cider)
;;; hive-mcp-cider.el ends here
