;;; hive-mcp-chroma.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(require 'clojure-elisp-runtime)
(require 'hive-mcp-api)

;;; Code:



(declare-function hive-mcp-addon-register "hive-mcp-addons")

(declare-function transient-define-prefix "transient")

(declare-function hive-mcp--send-request "hive-mcp")

(defgroup hive-mcp-chroma nil
  "Chroma vector database integration for hive-mcp."
  :group 'hive-mcp
  :prefix "hive-mcp-chroma-")

(defcustom hive-mcp-chroma-docker-compose-file nil
  "Path to docker-compose.yml for Chroma.\nIf nil, uses the default location in the hive-mcp project."
  :group 'hive-mcp-chroma
  :type '(choice (const nil) file))

(defcustom hive-mcp-chroma-host "localhost"
  "Chroma server host."
  :group 'hive-mcp-chroma
  :type 'string)

(defcustom hive-mcp-chroma-port 8000
  "Chroma server port."
  :group 'hive-mcp-chroma
  :type 'integer)

(defcustom hive-mcp-chroma-auto-start t
  "When non-nil, automatically start Chroma on addon initialization."
  :group 'hive-mcp-chroma
  :type 'boolean)

(defcustom hive-mcp-chroma-embedding-provider 'ollama
  "Embedding provider to use for vector search.\nOptions are `ollama' (local), `mock' (testing), or `none' (disabled)."
  :group 'hive-mcp-chroma
  :type '(choice (const :tag "Ollama (local)" ollama) (const :tag "Mock (testing)" mock) (const :tag "Disabled" none)))

(defcustom hive-mcp-chroma-ollama-model "nomic-embed-text"
  "Ollama model to use for embeddings."
  :group 'hive-mcp-chroma
  :type 'string)

(defcustom hive-mcp-chroma-startup-timeout 30
  "Timeout in seconds to wait for Chroma to become healthy."
  :group 'hive-mcp-chroma
  :type 'integer)

(defvar hive-mcp-chroma--process nil)

(defvar hive-mcp-chroma--status 'unknown
  "Current Chroma status: `running', `stopped', `starting', or `unknown'.")

(defvar hive-mcp-chroma--fallback-active nil)

(defvar hive-mcp-chroma--project-root nil)

(defun hive-mcp-chroma---project-root ()
  "Find the hive-mcp project root directory.\nChecks in order:\n1. Cached value\n2. `hive-mcp-root' variable (set in user config)\n3. Computed from load-file-name (fallback)"
  (or hive-mcp-chroma--project-root (setq hive-mcp-chroma--project-root (cond
  (((and (boundp 'hive-mcp-root) hive-mcp-root) hive-mcp-root) (t (let* ((load-path-dir (file-name-directory (or load-file-name buffer-file-name default-directory))))
    (expand-file-name "../.." load-path-dir))))))))

(defun hive-mcp-chroma---docker-compose-file ()
  "Return the path to docker-compose.yml."
  (or hive-mcp-chroma-docker-compose-file (expand-file-name "docker-compose.yml" (-project-root))))

(defun hive-mcp-chroma---docker-available-p ()
  "Check if docker is available."
  (zerop (call-process "docker" nil nil nil "info")))

(defun hive-mcp-chroma---compose-available-p ()
  "Check if docker-compose is available."
  (or (zerop (call-process "docker" nil nil nil "compose" "version")) (zerop (call-process "docker-compose" nil nil nil "--version"))))

(defun hive-mcp-chroma---ollama-available-p ()
  "Check if Ollama is available and has the embedding model."
  (and (zerop (call-process "ollama" nil nil nil "list")) (let* ((output (shell-command-to-string "ollama list")))
    (string-match-p hive-mcp-chroma-ollama-model output))))

(defun hive-mcp-chroma---health-check ()
  "Check if Chroma is responding to health checks."
  (condition-case nil
    (let* ((url (format "http://%s:%d/api/v2/heartbeat" hive-mcp-chroma-host hive-mcp-chroma-port)))
    (with-current-buffer (url-retrieve-synchronously url t nil 5)
    (goto-char (point-min))
    (search-forward "\n\n" nil t)
    (let* ((json-object-type 'plist))
    (ignore-errors (json-read)))))
  (error nil)))

(defun hive-mcp-chroma---compose-command ()
  "Return the docker-compose command to use."
  (if (zerop (call-process "docker" nil nil nil "compose" "version")) '("docker" "compose") '("docker-compose")))

(defun hive-mcp-chroma-start ()
  "Start the Chroma container via docker-compose."
  (interactive)
  (let* ((compose-file (-docker-compose-file)))
    (unless (file-exists-p compose-file)
    (error "docker-compose.yml not found at %s" compose-file))
    (unless (-docker-available-p)
    (error "Docker is not available"))
    (unless (-compose-available-p)
    (error "docker-compose is not available"))
    (setq hive-mcp-chroma--status 'starting)
    (message "Starting Chroma container...")
    (let* ((default-directory (file-name-directory compose-file))
        (cmd (-compose-command))
        (args (append (cdr cmd) (list "-f" compose-file "up" "-d"))))
    (setq hive-mcp-chroma--process (apply #'start-process "hive-mcp-chroma" "*hive-mcp-chroma*" (car cmd) args))
    (set-process-sentinel hive-mcp-chroma--process (lambda (proc _event)
    (when (eq (process-status proc) 'exit)
    (if (zerop (process-exit-status proc)) (-wait-for-healthy) (setq hive-mcp-chroma--status 'stopped))))))))

(provide 'hive-mcp-chroma)
;;; hive-mcp-chroma.el ends here
