;;; hive-mcp-gptel.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(require 'clojure-elisp-runtime)

;;; Code:



(declare-function gptel-send "gptel")

(declare-function gptel-request "gptel")

(declare-function hive-mcp-ai-build-context "hive-mcp-ai-bridge")

(declare-function hive-mcp-ai-inject-context "hive-mcp-ai-bridge")

(declare-function hive-mcp-ai-store-response "hive-mcp-ai-bridge")

(declare-function hive-mcp-ai-log-interaction "hive-mcp-ai-bridge")

(declare-function hive-mcp-ai-dispatch-to-swarm "hive-mcp-ai-bridge")

(declare-function hive-mcp-ai-run-pre-request-hooks "hive-mcp-ai-bridge")

(declare-function hive-mcp-ai-run-post-response-hooks "hive-mcp-ai-bridge")

(declare-function hive-mcp-ai-format-context-for "hive-mcp-ai-bridge")

(defvar gptel-directives nil)

(defvar gptel-prompt-filter-hook nil)

(defvar gptel-post-response-functions nil)

(defvar gptel-pre-response-hook nil)

(defvar gptel--system-message nil)

(defgroup hive-mcp-gptel nil
  "Integration between hive-mcp and gptel."
  :group 'hive-mcp
  :prefix "hive-mcp-gptel-")

(defcustom hive-mcp-gptel-inject-context t
  "When non-nil, inject memory context into gptel prompts."
  :group 'hive-mcp-gptel
  :type 'boolean)

(defcustom hive-mcp-gptel-include-semantic t
  "When non-nil, include semantic search in context injection."
  :group 'hive-mcp-gptel
  :type 'boolean)

(defcustom hive-mcp-gptel-store-responses t
  "When non-nil, store notable gptel responses to memory."
  :group 'hive-mcp-gptel
  :type 'boolean)

(defcustom hive-mcp-gptel-log-interactions t
  "When non-nil, log gptel interactions for audit trail."
  :group 'hive-mcp-gptel
  :type 'boolean)

(defcustom hive-mcp-gptel-context-prefix "\n\n---\n## Project Context\n\n"
  "Prefix added before injected context."
  :group 'hive-mcp-gptel
  :type 'string)

(defcustom hive-mcp-gptel-swarm-tasks-pattern "\\(?:^\\|[[:space:]]\\)@swarm:\\s-*\\(.+\\)"
  "Pattern to detect swarm dispatch requests in prompts.\nWhen matched, the task is dispatched to a swarm agent."
  :group 'hive-mcp-gptel
  :type 'regexp)

(defvar hive-mcp-gptel--initialized nil)

(defvar hive-mcp-gptel--last-prompt nil)

(defvar hive-mcp-gptel--response-start nil)

(defun hive-mcp-gptel--ensure-bridge ()
  "Ensure hive-mcp-ai-bridge is available."
  (or (featurep 'hive-mcp-ai-bridge) (require 'hive-mcp-ai-bridge nil t)))

(defun hive-mcp-gptel--ensure-gptel ()
  "Ensure gptel is available."
  (or (featurep 'gptel) (require 'gptel nil t)))

(defun hive-mcp-gptel--inject-context ()
  "Inject memory context into the current prompt buffer.\nThis runs in `gptel-prompt-filter-hook' before the query is sent."
  (when (and hive-mcp-gptel-inject-context (-ensure-bridge))
    (let* ((prompt-text (buffer-string))
        (context (hive-mcp-ai-build-context (when hive-mcp-gptel-include-semantic
    prompt-text))))
    (when context
    (goto-char (point-min))
    (insert (hive-mcp-ai-format-context-for 'gptel context))
    (insert hive-mcp-gptel-context-prefix))
    (setq hive-mcp-gptel--last-prompt prompt-text))))

(defun hive-mcp-gptel--mark-response-start ()
  "Mark the start of gptel response.\nThis runs in `gptel-pre-response-hook'."
  (setq hive-mcp-gptel--response-start (point-marker)))

(defun hive-mcp-gptel--handle-response (beg end)
  "Handle gptel response between BEG and END.\nThis runs in `gptel-post-response-functions'."
  (when (-ensure-bridge)
    (let* ((response (buffer-substring-no-properties beg end)))
    (when hive-mcp-gptel-log-interactions
    (hive-mcp-ai-log-interaction "gptel" "response" (list :prompt-length (length (or hive-mcp-gptel--last-prompt "")) :response-length (length response) :buffer (buffer-name))))
    (when hive-mcp-gptel-store-responses
    (hive-mcp-ai-store-response response "gptel"))
    (hive-mcp-ai-run-post-response-hooks "gptel" response))))

(defun hive-mcp-gptel--check-swarm-dispatch ()
  "Check for @swarm: directives in the current prompt.\nDispatches matching tasks to swarm agents."
  (when (and (-ensure-bridge) (-ensure-gptel))
    (save-excursion
    (goto-char (point-min))
    (while (re-search-forward hive-mcp-gptel-swarm-tasks-pattern nil t)
    (let* ((task (match-string 1)))
    (hive-mcp-ai-dispatch-to-swarm task :source "gptel" :preset "code-review"))))))

(defun hive-mcp-gptel-directive-with-context ()
  "Create a gptel directive that includes memory context.\nReturns a cons cell suitable for `gptel-directives'."
  (when (-ensure-bridge)
    (let* ((context (hive-mcp-ai-build-context)))
    (cons "Memory-Aware" (clel-concat "You are a helpful assistant with access to project knowledge.\n\n" (or context "") "\n\nUse this context to provide informed, project-specific responses.")))))

(defun hive-mcp-gptel-add-memory-directive ()
  "Add a memory-aware directive to `gptel-directives'."
  (interactive)
  (when (-ensure-gptel)
    (when-let-star (list directive (directive-with-context)) (add-to-list 'gptel-directives directive) (message "Added Memory-Aware directive to gptel-directives"))))

(defun hive-mcp-gptel-send-with-context ()
  "Send prompt to gptel with memory context injection.\nLike `gptel-send' but ensures context is injected."
  (interactive)
  (let* ((hive-mcp-gptel-inject-context t))
    (call-interactively #'gptel-send)))

(defun hive-mcp-gptel-query-memory (query)
  "Query memory with QUERY and insert results at point."
  (interactive "sQuery memory: ")
  (when (-ensure-bridge)
    (let* ((results (hive-mcp-ai-build-context query)))
    (if results (insert results) (message "No relevant memory found")))))

(defun hive-mcp-gptel-store-region (beg end)
  "Store region between BEG and END as memory snippet."
  (interactive "r")
  (when (-ensure-bridge)
    (let* ((content (buffer-substring-no-properties beg end)))
    (hive-mcp-ai-store-response content "gptel-manual" '("user-selected"))
    (message "Stored selection to memory"))))

(defun hive-mcp-gptel-dispatch-to-swarm (task)
  "Dispatch TASK to swarm agent."
  (interactive "sTask for swarm: ")
  (when (-ensure-bridge)
    (let* ((result (hive-mcp-ai-dispatch-to-swarm task :source "gptel-interactive" :preset "general")))
    (if result (message "Dispatched to swarm: %s" result) (message "Swarm dispatch failed - is swarm available?")))))

(defun hive-mcp-gptel--setup-hooks ()
  "Set up gptel hooks for integration."
  (when (-ensure-gptel)
    (add-hook 'gptel-prompt-filter-hook #'-inject-context)
    (add-hook 'gptel-prompt-filter-hook #'-check-swarm-dispatch)
    (add-hook 'gptel-pre-response-hook #'-mark-response-start)
    (add-hook 'gptel-post-response-functions #'-handle-response)))

(defun hive-mcp-gptel--teardown-hooks ()
  "Remove gptel hooks."
  (remove-hook 'gptel-prompt-filter-hook #'-inject-context)
  (remove-hook 'gptel-prompt-filter-hook #'-check-swarm-dispatch)
  (remove-hook 'gptel-pre-response-hook #'-mark-response-start)
  (remove-hook 'gptel-post-response-functions #'-handle-response))

(define-minor-mode hive-mcp-gptel-mode
  "Minor mode for hive-mcp integration with gptel.\n\nWhen enabled:\n- Memory context is injected into prompts before sending\n- Notable responses are stored to memory\n- Interactions are logged for audit\n- @swarm: directives dispatch tasks to agents"
  :init-value nil
  :lighter " MCP-GPT"
  :global t
  :group 'hive-mcp-gptel
  (if hive-mcp-gptel-mode (progn
  (-setup-hooks)
  (setq hive-mcp-gptel--initialized t)
  (message "hive-mcp-gptel: enabled")) (-teardown-hooks)))

(with-eval-after-load 'transient
  (transient-define-prefix hive-mcp-gptel-menu (nil) "MCP integration menu for gptel." (list "hive-mcp + gptel" (list "Context" ("c" "Send with context" hive-mcp-gptel-send-with-context) ("q" "Query memory" hive-mcp-gptel-query-memory) ("d" "Add memory directive" hive-mcp-gptel-add-memory-directive)) (list "Store" ("s" "Store region" hive-mcp-gptel-store-region)) (list "Swarm" ("w" "Dispatch to swarm" hive-mcp-gptel-dispatch-to-swarm)) (list "Toggle" ("m" "Toggle mode" hive-mcp-gptel-mode)))))

(defun hive-mcp-gptel--addon-init ()
  "Initialize gptel addon."
  (require 'hive-mcp-ai-bridge nil t)
  (message "hive-mcp-gptel: initialized"))

(defun hive-mcp-gptel--addon-shutdown ()
  "Shutdown gptel addon."
  (when hive-mcp-gptel-mode
    (hive-mcp-gptel-mode -1))
  (message "hive-mcp-gptel: shutdown complete"))

(with-eval-after-load 'hive-mcp-addons
  (hive-mcp-addon-register 'gptel :version "0.1.0" :description "gptel integration with memory and swarm" :requires '(hive-mcp-ai-bridge) :provides '(hive-mcp-gptel-mode) :init #'-addon-init :shutdown #'-addon-shutdown))

(provide 'hive-mcp-gptel)
;;; hive-mcp-gptel.el ends here
