;;; hive-mcp-hooks.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(require 'clojure-elisp-runtime)
(require 'cl-lib)

;;; Code:



(declare-function hive-mcp-channel-on "hive-mcp-channel")

(declare-function hive-mcp-channel-off "hive-mcp-channel")

(declare-function hive-mcp-channel-connected-p "hive-mcp-channel")

(declare-function hive-mcp-with-fallback "hive-mcp-graceful")

(declare-function magit-status "magit" (&optional directory cache))

(defgroup hive-mcp-hooks nil
  "Hook event processing for hive-mcp."
  :group 'hive-mcp
  :prefix "hive-mcp-hooks-")

(defcustom hive-mcp-hooks-notify-function (var message)
  "Function to call for notifications.\nShould accept a format string and arguments like `message'.\nCan be set to `notifications-notify' for desktop notifications."
  :group 'hive-mcp-hooks
  :type 'function)

(defcustom hive-mcp-hooks-commit-auto-stage t
  "Whether to auto-stage all changes on commit hook.\nWhen non-nil, hook/commit events with action 'stage' stage all files."
  :group 'hive-mcp-hooks
  :type 'boolean)

(defcustom hive-mcp-hooks-wrap-auto-save t
  "Whether to auto-save buffers on wrap hook.\nWhen non-nil, hook/wrap events save all modified buffers."
  :group 'hive-mcp-hooks
  :type 'boolean)

(defcustom hive-mcp-hooks-log-events nil
  "Whether to log all hook events to *Messages*.\nUseful for debugging hook integrations."
  :group 'hive-mcp-hooks
  :type 'boolean)

(defvar hive-mcp-hooks--initialized nil)

(defvar hive-mcp-hooks--handler-alist nil)

(defun hive-mcp-hooks---log (format-string &rest args)
  "Log FORMAT-STRING with ARGS if logging is enabled."
  (when hive-mcp-hooks-log-events
    (apply #'message (clel-concat "[hive-mcp-hooks] " format-string) args)))

(defun hive-mcp-hooks-process (event)
  "Process a hook EVENT from the channel.\nEVENT is an alist with at least a \"type\" key.\nDispatches to appropriate handler based on event type."
  (let* ((type-str (or (cdr (clel-assoc "type" event)) (cdr (clel-assoc 'type event))))
        (data (or (cdr (clel-assoc "data" event)) (cdr (clel-assoc 'data event)) event)))
    (-log "Processing event: %s" type-str)
    (condition-case err
    (pcase type-str
  ("hook/commit" (-handle-commit data))
  ("hook/wrap" (-handle-wrap data))
  ("hook/notify" (-handle-notify data))
  ('_ (when-let-star (list handler (cdr (clel-assoc type-str hive-mcp-hooks--handler-alist))) (funcall handler data))))
  (error (message "[hive-mcp-hooks] Error processing %s: %s" type-str (error-message-string err))))))

(defun hive-mcp-hooks---handle-commit (data)
  "Handle a hook/commit event with DATA.\nDATA may contain:\n  - action: 'stage', 'commit', 'amend'\n  - message: commit message (for commit/amend)\n  - files: list of files to stage (optional)\n  - directory: working directory"
  (let* ((action (or (cdr (clel-assoc "action" data)) (cdr (clel-assoc 'action data)) "status"))
        (commit-msg (or (cdr (clel-assoc "message" data)) (cdr (clel-assoc 'message data))))
        (files (or (cdr (clel-assoc "files" data)) (cdr (clel-assoc 'files data))))
        (directory (or (cdr (clel-assoc "directory" data)) (cdr (clel-assoc 'directory data)) default-directory)))
    (-log "Commit hook: action=%s dir=%s" action directory)
    (let* ((default-directory directory))
    (pcase action
  ("stage" (if files (dolist (file files)
    (-git-stage file)) (when hive-mcp-hooks-commit-auto-stage
    (-git-stage-all))))
  ("commit" (when commit-msg
    (-git-commit commit-msg)))
  ("amend" (-git-amend commit-msg))
  ("status" (-show-git-status directory))
  ('_ (-log "Unknown commit action: %s" action))))))

(defun hive-mcp-hooks---handle-wrap (data)
  "Handle a hook/wrap event with DATA.\nDATA may contain:\n  - action: 'gather', 'crystallize', 'complete'\n  - session-id: current session identifier\n  - save-buffers: whether to save modified buffers"
  (let* ((action (or (cdr (clel-assoc "action" data)) (cdr (clel-assoc 'action data)) "gather"))
        (session-id (or (cdr (clel-assoc "session-id" data)) (cdr (clel-assoc 'session-id data))))
        (save-buffers (or (cdr (clel-assoc "save-buffers" data)) (cdr (clel-assoc 'save-buffers data)) hive-mcp-hooks-wrap-auto-save)))
    (-log "Wrap hook: action=%s session=%s" action session-id)
    (pcase action
  ("gather" (when save-buffers
    (save-some-buffers t)) (-notify "Wrap: Gathering session data..."))
  ("crystallize" (-notify "Wrap: Crystallizing session..."))
  ("complete" (when save-buffers
    (save-some-buffers t)) (-notify "Wrap: Session complete for %s" (or session-id "current session")))
  ('_ (-log "Unknown wrap action: %s" action)))))

(defun hive-mcp-hooks---handle-notify (data)
  "Handle a hook/notify event with DATA.\nDATA may contain:\n  - message: notification message (required)\n  - level: 'info', 'warning', 'error' (default: info)\n  - title: notification title (optional)"
  (let* ((msg (or (cdr (clel-assoc "message" data)) (cdr (clel-assoc 'message data)) "Notification"))
        (level (or (cdr (clel-assoc "level" data)) (cdr (clel-assoc 'level data)) "info"))
        (title (or (cdr (clel-assoc "title" data)) (cdr (clel-assoc 'title data)))))
    (-log "Notify: [%s] %s" level msg)
    (pcase level
  ("error" (-notify-error msg title))
  ("warning" (-notify-warning msg title))
  ('_ (-notify msg)))))

(defun hive-mcp-hooks---git-stage (file)
  "Stage FILE for commit."
  (let* ((output (shell-command-to-string (format "git add %s 2>&1" (shell-quote-argument file)))))
    (unless (string-empty-p output)
    (-log "git add %s: %s" file output))))

(defun hive-mcp-hooks---git-stage-all ()
  "Stage all modified files."
  (let* ((output (shell-command-to-string "git add -A 2>&1")))
    (-log "git add -A: %s" (if (string-empty-p output) "done" output))))

(defun hive-mcp-hooks---git-commit (message)
  "Create a commit with MESSAGE."
  (let* ((output (shell-command-to-string (format "git commit -m %s 2>&1" (shell-quote-argument message)))))
    (-log "git commit: %s" output)
    (-notify "Committed: %s" (truncate-string-to-width message 50))))

(defun hive-mcp-hooks---git-amend (&optional message)
  "Amend the last commit, optionally with new MESSAGE."
  (let* ((cmd (if message (format "git commit --amend -m %s 2>&1" (shell-quote-argument message)) "git commit --amend --no-edit 2>&1"))
        (output (shell-command-to-string cmd)))
    (-log "git commit --amend: %s" output)))

(defun hive-mcp-hooks---show-git-status (directory)
  "Show git status for DIRECTORY.\nUses Magit if available, otherwise falls back to shell."
  (if (fboundp 'magit-status) (magit-status directory) (let* ((default-directory directory))
    (shell-command "git status"))))

(defun hive-mcp-hooks---notify (format-string &rest args)
  "Send a notification with FORMAT-STRING and ARGS."
  (apply hive-mcp-hooks-notify-function format-string args))

(defun hive-mcp-hooks---notify-warning (message &optional title)
  "Send a warning notification with MESSAGE and optional TITLE."
  (display-warning 'hive-mcp-hooks (if title (format "%s: %s" title message) message) :warning))

(defun hive-mcp-hooks---notify-error (message &optional title)
  "Send an error notification with MESSAGE and optional TITLE."
  (display-warning 'hive-mcp-hooks (if title (format "%s: %s" title message) message) :error))

(defun hive-mcp-hooks---channel-handler (event)
  "Channel message handler that dispatches hook events.\nEVENT is the decoded channel message."
  (let* ((type-str (or (cdr (clel-assoc "type" event)) (cdr (clel-assoc 'type event)))))
    (when (and type-str (string-prefix-p "hook/" type-str))
    (process event))))

(defun hive-mcp-hooks---register-with-channel ()
  "Register hook handlers with the bidirectional channel."
  (when (require 'hive-mcp-channel nil t)
    (dolist (type '(:hook/commit :hook/wrap :hook/notify))
    (hive-mcp-channel-on type #'hive-mcp-hooks-process))
    (-log "Registered with channel")))

(defun hive-mcp-hooks---unregister-from-channel ()
  "Unregister hook handlers from the channel."
  (when (require 'hive-mcp-channel nil t)
    (dolist (type '(:hook/commit :hook/wrap :hook/notify))
    (hive-mcp-channel-off type #'hive-mcp-hooks-process))
    (-log "Unregistered from channel")))

(defun hive-mcp-hooks-register (hook-type handler)
  "Register HANDLER for custom HOOK-TYPE.\nHOOK-TYPE should be a string like \"hook/my-custom\".\nHANDLER receives the event data as an alist."
  (setf (alist-get hook-type hive-mcp-hooks--handler-alist nil nil #'equal) handler))

(defun hive-mcp-hooks-unregister (hook-type)
  "Unregister handler for HOOK-TYPE."
  (setf (alist-get hook-type hive-mcp-hooks--handler-alist nil 'remove #'equal) nil))

(defun hive-mcp-hooks-init ()
  "Initialize the hooks module.\nRegisters handlers with the channel if connected."
  (interactive)
  (unless hive-mcp-hooks--initialized
    (-register-with-channel)
    (setq hive-mcp-hooks--initialized t)
    (-log "Initialized")))

(defun hive-mcp-hooks-shutdown ()
  "Shutdown the hooks module."
  (interactive)
  (when hive-mcp-hooks--initialized
    (-unregister-from-channel)
    (setq hive-mcp-hooks--initialized nil)
    (-log "Shutdown")))

(defun hive-mcp-hooks-emit-hook-event (hook-type data)
  "Emit a hook event of HOOK-TYPE with DATA through swarm-events.\nThis allows Emacs-side code to trigger hooks that can be processed\nby both Emacs and Clojure sides."
  (when (require 'hive-mcp-swarm-events nil t)
    (declare-function hive-mcp-swarm-events-emit "hive-mcp-swarm-events")
    (hive-mcp-swarm-events-emit hook-type data)))

(defun hive-mcp-hooks-trigger-wrap (action &optional session-id)
  "Trigger a wrap hook with ACTION and optional SESSION-ID.\nACTION should be 'gather', 'crystallize', or 'complete'."
  (emit-hook-event "hook/wrap" (clel-seq (clel-concat (clojure-core-list (clel-seq (clel-concat (clojure-core-list "action") (clojure-core-list '.) (clojure-core-list 'user/action)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "session-id") (clojure-core-list '.) (clojure-core-list 'user/session-id)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "timestamp") (clojure-core-list '.) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'user/truncate) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'user/float-time))))))))))))))

(defun hive-mcp-hooks-trigger-notify (message &optional level title)
  "Trigger a notification hook with MESSAGE, LEVEL, and TITLE."
  (emit-hook-event "hook/notify" (clel-seq (clel-concat (clojure-core-list (clel-seq (clel-concat (clojure-core-list "message") (clojure-core-list '.) (clojure-core-list 'user/message)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "level") (clojure-core-list '.) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/or) (clojure-core-list 'user/level) (clojure-core-list "info"))))))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "title") (clojure-core-list '.) (clojure-core-list 'user/title))))))))

(defun hive-mcp-hooks---addon-init ()
  "Addon init function - called when addon loads."
  (init))

(defun hive-mcp-hooks---addon-shutdown ()
  "Addon shutdown function - called when addon unloads."
  (shutdown))

(with-eval-after-load 'hive-mcp-addons
  (declare-function hive-mcp-addon-register "hive-mcp-addons")
  (hive-mcp-addon-register 'hooks :version "0.1.0" :description "Hook event processor for channel-based triggers" :requires '(hive-mcp-channel) :provides '(hive-mcp-hooks-init hive-mcp-hooks-process) :init #'-addon-init :shutdown #'-addon-shutdown))

(provide 'hive-mcp-hooks)
;;; hive-mcp-hooks.el ends here
