;;; olympus-ui.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(require 'clojure-elisp-runtime)

;;; Code:



(defgroup olympus-ui nil
  "Olympus grid UI settings."
  :group 'hive-mcp
  :prefix "olympus-ui-")

(defcustom olympus-ui-refresh-interval 2
  "Seconds between automatic status refreshes.\nSet to 0 to disable auto-refresh (rely on push updates only)."
  :group 'olympus-ui
  :type 'integer)

(defcustom olympus-ui-show-task-preview t
  "When non-nil, show truncated task description in grid cells."
  :group 'olympus-ui
  :type 'boolean)

(defcustom olympus-ui-cell-width 40
  "Width in characters for each grid cell."
  :group 'olympus-ui
  :type 'integer)

(defcustom olympus-ui-cell-height 6
  "Height in lines for each grid cell."
  :group 'olympus-ui
  :type 'integer)

(defface olympus-ui-status-idle '((t :foreground "gray50" :weight normal)) "Face for idle lings." :group 'olympus-ui)

(defface olympus-ui-status-working '((t :foreground "green" :weight bold)) "Face for working/active lings." :group 'olympus-ui)

(defface olympus-ui-status-blocked '((t :foreground "orange" :weight bold)) "Face for blocked lings awaiting input." :group 'olympus-ui)

(defface olympus-ui-status-error '((t :foreground "red" :weight bold)) "Face for lings in error state." :group 'olympus-ui)

(defface olympus-ui-status-spawning '((t :foreground "cyan" :weight normal)) "Face for spawning/initializing lings." :group 'olympus-ui)

(defface olympus-ui-cell-border '((t :foreground "gray40")) "Face for grid cell borders." :group 'olympus-ui)

(defface olympus-ui-header '((t :foreground "cyan" :weight bold :height 1.2)) "Face for grid header." :group 'olympus-ui)

(defface olympus-ui-focused '((t :box (:line-width 2 :color "yellow"))) "Face for the focused ling cell." :group 'olympus-ui)

(defvar olympus-ui-olympus-ui--buffer-name "*Olympus Grid*"
  "Name of the Olympus grid buffer.")

(defvar olympus-ui-olympus-ui--current-state nil)

(defvar olympus-ui-olympus-ui--refresh-timer nil)

(defvar olympus-ui-olympus-ui--focused-ling nil)

(defvar olympus-ui-olympus-ui--ws-subscription nil)

(defun olympus-ui--status--gtface (status)
  "Return the face for a ling STATUS keyword."
  (pcase status
  ((quote idle) 'olympus-ui-status-idle)
  ('idle 'olympus-ui-status-idle)
  ((quote working) 'olympus-ui-status-working)
  ('working 'olympus-ui-status-working)
  ((quote blocked) 'olympus-ui-status-blocked)
  ('blocked 'olympus-ui-status-blocked)
  ((quote error) 'olympus-ui-status-error)
  ('error 'olympus-ui-status-error)
  ((quote spawning) 'olympus-ui-status-spawning)
  ('spawning 'olympus-ui-status-spawning)
  ((quote starting) 'olympus-ui-status-spawning)
  ('starting 'olympus-ui-status-spawning)
  ((quote initializing) 'olympus-ui-status-spawning)
  ('initializing 'olympus-ui-status-spawning)
  ('_ 'olympus-ui-status-idle)))

(defun olympus-ui--status--gticon (status)
  "Return a status icon character for STATUS."
  (pcase status
  ((quote idle) "○")
  ('idle "○")
  ((quote working) "●")
  ('working "●")
  ((quote blocked) "◐")
  ('blocked "◐")
  ((quote error) "✗")
  ('error "✗")
  ((quote spawning) "◌")
  ('spawning "◌")
  ((quote starting) "◌")
  ('starting "◌")
  ((quote initializing) "◌")
  ('initializing "◌")
  ('_ "?")))

(defun olympus-ui--ensure-api ()
  "Ensure hive-mcp-api is available."
  (if (featurep 'hive-mcp-api) nil (progn
  (require 'hive-mcp-api nil t)))
  (featurep 'hive-mcp-api))

(defun olympus-ui--fetch-status ()
  "Fetch current Olympus status from MCP.\nReturns map with :lings, :layout, :positions, :active-tab, :layout-mode.\nThe :lings map includes :status for each ling (the fix for 'idle' display)."
  (when (olympus-ui--ensure-api)
    (condition-case err
    (let* ((response (hive-mcp-api-call "olympus" (list :command "status"))))
    (when (and response (plist-get response :success))
    (let* ((hm-status (hive-mcp-api-call "hivemind" (list :command "status")))
        (agents (plist-get hm-status :agents)))
    (list :ling-count (plist-get response :ling-count) :layout (plist-get response :layout) :positions (plist-get response :positions) :active-tab (plist-get response :active-tab) :layout-mode (plist-get response :layout-mode) :lings agents))))
  (error (hive-mcp-log-log-error 'olympus "Failed to fetch status: %s" err)
      nil))))

(defun olympus-ui--fetch-lings-with-status ()
  "Fetch ling list with their current status.\nThis is the key function that fixes the 'idle' display issue:\nit reads :status from the lings map, not just positions."
  (let* ((state (olympus-ui--fetch-status)))
    (when state
    (let* ((lings (plist-get state :lings))
        (positions (plist-get state :positions)))
    (mapcar (lambda (pos-entry)
    (let* ((ling-id (car pos-entry))
        (pos (cdr pos-entry))
        (ling-data (gethash ling-id lings)))
    (list :id ling-id :row (plist-get pos :row) :col (plist-get pos :col) :tab (plist-get pos :tab) :status (or (plist-get ling-data :status) :idle) :name (or (plist-get ling-data :name) ling-id) :task (plist-get ling-data :current-task) :cwd (plist-get ling-data :cwd)))) positions)))))

(defun olympus-ui--truncate-string (s max-len)
  "Truncate string S to MAX-LEN characters, adding ellipsis if needed."
  (if (> (length s) max-len) (clel-concat (substring s 0 (- max-len 3)) "...") s))

(defun olympus-ui--pad-string (s width)
  "Pad string S to WIDTH characters, truncating if necessary."
  (let* ((truncated (olympus-ui--truncate-string s width)))
    (clel-concat truncated (make-string (cl-max 0 (- width (length truncated))) -p))))

(defun olympus-ui--render-cell-line (content width face)
  "Render a single line of cell content with FACE."
  (let* ((padded (olympus-ui--pad-string (or content "") (- width 2))))
    (propertize (clel-concat "│" padded "│") 'face face)))

(defun olympus-ui--render-cell (ling width height focused-p)
  "Render a single ling cell.\nLING is a plist with :id, :name, :status, :task.\nWIDTH and HEIGHT are dimensions.\nFOCUSED-P indicates if this cell should be highlighted."
  (let* ((id (plist-get ling :id))
        (name (plist-get ling :name))
        (status (plist-get ling :status))
        (task (plist-get ling :task))
        (status-face (olympus-ui--status--gtface status))
        (icon (olympus-ui--status--gticon status))
        (border-str (make-string (- width 2) -p─))
        (top-border (propertize (clel-concat "┌" border-str "┐") 'face 'olympus-ui-cell-border))
        (bottom-border (propertize (clel-concat "└" border-str "┘") 'face 'olympus-ui-cell-border))
        (status-line (format "%s %s  %s" icon (symbol-name (if (keywordp status) (intern (substring (symbol-name status) 1)) status)) (olympus-ui--truncate-string (or name id) (- width 15))))
        (id-line (olympus-ui--truncate-string (or id "unknown") (- width 4)))
        (task-line (when (and olympus-ui-show-task-preview task)
    (olympus-ui--truncate-string task (- width 4)))))
    (clel-concat top-border "\n" (olympus-ui--render-cell-line status-line width status-face) "\n" (olympus-ui--render-cell-line id-line width 'default) "\n" (if task-line (clel-concat (olympus-ui--render-cell-line task-line width 'font-lock-comment-face) "\n") (olympus-ui--render-cell-line "" width 'default)) (apply 'concat (mapcar (lambda (_)
    (clel-concat (olympus-ui--render-cell-line "" width 'default) "\n")) (number-sequence 1 (- height 5)))) bottom-border)))

(defun olympus-ui--render-empty-cell (width height)
  "Render an empty grid cell placeholder."
  (let* ((border-str (make-string (- width 2) -p─))
        (top-border (propertize (clel-concat "┌" border-str "┐") 'face 'olympus-ui-cell-border))
        (bottom-border (propertize (clel-concat "└" border-str "┘") 'face 'olympus-ui-cell-border))
        (empty-line (propertize (clel-concat "│" (make-string (- width 2) -p) "│") 'face 'olympus-ui-cell-border)))
    (clel-concat top-border "\n" (apply 'concat (mapcar (lambda (_)
    (clel-concat empty-line "\n")) (number-sequence 1 (- height 2)))) bottom-border)))

(provide 'olympus-ui)
;;; olympus-ui.el ends here
