;;; hive-mcp-org-kanban.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(require 'clojure-elisp-runtime)
(require 'cl-lib)
(require 'org)
(require 'json)
(require 'hive-mcp-kanban-protocol)
(require 'hive-mcp-kanban-standalone)
(require 'hive-mcp-kanban-vibe)
(require 'hive-mcp-kanban-board)

;;; Code:



(defvar org-id-locations nil)

(declare-function hive-mcp-api-get-context "hive-mcp-api")

(declare-function org-kanban-initialize "org-kanban")

(defgroup hive-mcp-kanban nil
  "Kanban integration for hive-mcp with dual backends."
  :group 'hive-mcp
  :prefix "hive-mcp-org-kanban-")

(defcustom backend 'standalone
  "Active kanban backend.\n- `vibe': Use vibe-kanban MCP server (cloud/team)\n- `standalone': Use local org file (personal/offline)"
  :group 'hive-mcp-kanban
  :type '(choice (const :tag "Vibe Kanban (MCP/Cloud)" vibe) (const :tag "Standalone (Local Org)" standalone)))

(defcustom statuses '("TODO" "IN-PROGRESS" "IN-REVIEW" "DONE" "CANCELLED")
  "List of kanban statuses/columns."
  :group 'hive-mcp-kanban
  :type '(repeat string))

(defcustom auto-sync nil
  "When non-nil, auto-sync changes to the other backend."
  :group 'hive-mcp-kanban
  :type 'boolean)

(defun hive-mcp-org-kanban-list-projects ()
  "List all projects from current backend."
  (hive-mcp-kanban-protocol--list-projects hive-mcp-org-kanban-backend))

(defun hive-mcp-org-kanban-list-tasks (&optional project-id status)
  "List tasks from current backend.\nPROJECT-ID defaults to `hive-mcp-kanban-vibe-default-project'.\nFor standalone backend, PROJECT-ID can be nil.\nSTATUS optionally filters by kanban status."
  (let* ((pid (or project-id hive-mcp-kanban-vibe-default-project)))
    (when (and (eq hive-mcp-org-kanban-backend 'vibe) (not pid))
    (error "No project ID specified. Set hive-mcp-kanban-vibe-default-project"))
    (hive-mcp-kanban-protocol--list-tasks hive-mcp-org-kanban-backend pid status)))

(defun hive-mcp-org-kanban-get-task (task-id)
  "Get task details by TASK-ID from current backend."
  (hive-mcp-kanban-protocol--get-task hive-mcp-org-kanban-backend task-id))

(defun hive-mcp-org-kanban-create-task (title &optional description project-id)
  "Create a new task with TITLE and optional DESCRIPTION.\nPROJECT-ID defaults to `hive-mcp-kanban-vibe-default-project'.\nFor standalone backend, PROJECT-ID can be nil."
  (let* ((pid (or project-id hive-mcp-kanban-vibe-default-project)))
    (when (and (eq hive-mcp-org-kanban-backend 'vibe) (not pid))
    (error "No project ID specified. Set hive-mcp-kanban-vibe-default-project"))
    (let* ((result (hive-mcp-kanban-protocol--create-task hive-mcp-org-kanban-backend pid title description)))
    (when hive-mcp-org-kanban-auto-sync
    (hive-mcp-org-kanban--sync-task-to-other-backend result))
    result)))

(defun hive-mcp-org-kanban-update-task (task-id &rest props)
  "Update task TASK-ID with PROPS (:title :description :status)."
  (let* ((result (apply #'hive-mcp-kanban-protocol--update-task hive-mcp-org-kanban-backend task-id props)))
    (when hive-mcp-org-kanban-auto-sync
    (apply #'hive-mcp-org-kanban--sync-update-to-other-backend task-id props))
    result))

(defun hive-mcp-org-kanban-delete-task (task-id)
  "Delete task by TASK-ID from current backend."
  (hive-mcp-kanban-protocol--delete-task hive-mcp-org-kanban-backend task-id))

(defun hive-mcp-org-kanban-move-task (task-id new-status)
  "Move task TASK-ID to NEW-STATUS."
  (hive-mcp-org-kanban-update-task task-id :status new-status))

(defun hive-mcp-org-kanban-enable-dual-backend ()
  "Enable dual backend mode with auto-sync."
  (interactive)
  (setq hive-mcp-org-kanban-auto-sync t)
  (message "Dual backend enabled. Changes sync to both vibe-kanban and standalone."))

(defun hive-mcp-org-kanban-sync-all ()
  "Sync all tasks between backends."
  (interactive)
  (message "Syncing kanban backends...")
  (let* ((vibe-tasks (hive-mcp-kanban-protocol--list-tasks 'vibe hive-mcp-kanban-vibe-default-project))
        (standalone-tasks (hive-mcp-kanban-protocol--list-tasks 'standalone hive-mcp-kanban-vibe-default-project)))
    (message "Synced %d vibe tasks and %d standalone tasks" (length vibe-tasks) (length standalone-tasks))))

(defun hive-mcp-org-kanban---sync-task-to-other-backend (task)
  "Sync TASK to the non-active backend."
  (let* ((other-backend (if (eq hive-mcp-org-kanban-backend 'vibe) 'standalone 'vibe)))
    (hive-mcp-kanban-protocol--create-task other-backend hive-mcp-kanban-vibe-default-project (alist-get 'title task) (alist-get 'description task))))

(defun hive-mcp-org-kanban---sync-update-to-other-backend (task-id &rest props)
  "Sync TASK-ID update with PROPS to the non-active backend."
  (let* ((other-backend (if (eq hive-mcp-org-kanban-backend 'vibe) 'standalone 'vibe)))
    (apply #'hive-mcp-kanban-protocol--update-task other-backend task-id props)))

(defun hive-mcp-org-kanban-view (&optional format)
  "View kanban board using native Clojure renderer.\nFORMAT can be `terminal' (ASCII art) or `emacs' (org-mode).\nWith prefix arg, prompts for format."
  (interactive (list (if current-prefix-arg (intern (completing-read "Format: " '("terminal" "emacs") nil t)) 'terminal)))
  (let* ((file hive-mcp-kanban-standalone-org-file)
        (fmt (or format 'terminal))
        (code (format "(do (require '[hive-mcp.org-clj.render :as r])\n                           (r/render-file (r/%s-renderer) \"%s\"))" fmt file)))
    (if (and (fboundp 'cider-connected-p) (cider-connected-p)) (let* ((result (cider-nrepl-sync-request:eval code)))
    (when-let-star (list value (nrepl-dict-get result "value")) (let* ((buf (get-buffer-create "*Kanban Board*")))
    (with-current-buffer buf
    (let* ((inhibit-read-only t))
    (erase-buffer)
    (insert (read value)))
    (goto-char (point-min))
    (if (eq fmt 'emacs) (org-mode) (special-mode)))
    (display-buffer buf)))) (hive-mcp-org-kanban--view-static file fmt))))

(defun hive-mcp-org-kanban---view-static (file _format)
  "Display static kanban board from FILE.\nFORMAT argument is unused in fallback mode.\nUsed when CIDER is not connected."
  (message "CIDER not connected. Showing org file directly.")
  (find-file file))

(defun hive-mcp-org-kanban-show-board ()
  "Show kanban board in org buffer."
  (interactive)
  (let* ((buf (get-buffer-create "*MCP Kanban*"))
        (tasks (hive-mcp-org-kanban-list-tasks)))
    (with-current-buffer buf
    (erase-buffer)
    (org-mode)
    (insert "#+TITLE: Kanban Board\n")
    (insert "#+STARTUP: overview\n\n")
    (dolist (status hive-mcp-org-kanban-statuses)
    (insert (format "* %s\n" status))
    (let* ((status-tasks (cl-remove-if-not (lambda (tsk)
    (equal (hive-mcp-kanban-protocol--vibe-to-org-status (alist-get 'status tsk)) status)) tasks)))
    (dolist (task status-tasks)
    (insert (format "** %s\n" (alist-get 'title task)))
    (insert ":PROPERTIES:\n")
    (insert (format ":ID: %s\n" (alist-get 'id task)))
    (when-let-star (list agent (alist-get 'agent task)) (insert (format ":AGENT: %s\n" agent)))
    (insert ":END:\n")
    (when-let-star (list desc (alist-get 'description task)) (insert desc "\n"))
    (insert "\n"))))
    (goto-char (point-min)))
    (switch-to-buffer buf)))

(defun hive-mcp-org-kanban-create ()
  "Create a new kanban task interactively."
  (interactive)
  (let* ((title (clel-read-string "Task title: "))
        (description (clel-read-string "Description (optional): " nil nil ""))
        (result (hive-mcp-org-kanban-create-task title (unless (string-empty-p description)
    description))))
    (message "Created task: %s" (alist-get 'id result))))

(defun hive-mcp-org-kanban-update-status ()
  "Update status of a task interactively."
  (interactive)
  (let* ((tasks (hive-mcp-org-kanban-list-tasks))
        (task-names (mapcar (lambda (tsk)
    (format "%s [%s]" (alist-get 'title tsk) (alist-get 'status tsk))) tasks))
        (selection (completing-read "Task: " task-names nil t))
        (task (nth (cl-position selection task-names :test #'equal) tasks))
        (new-status (completing-read "New status: " (mapcar #'cdr hive-mcp-kanban-protocol-status-map) nil t)))
    (hive-mcp-org-kanban-move-task (alist-get 'id task) new-status)
    (message "Moved task to %s" new-status)))

(defun hive-mcp-org-kanban-open-org-file ()
  "Open the standalone kanban org file."
  (interactive)
  (find-file hive-mcp-kanban-standalone-org-file))

(defun hive-mcp-org-kanban-set-project ()
  "Set the default kanban project interactively."
  (interactive)
  (let* ((projects (hive-mcp-org-kanban-list-projects))
        (names (mapcar (lambda (p)
    (alist-get 'name p)) projects))
        (selection (completing-read "Project: " names nil t))
        (project (cl-find-if (lambda (p)
    (equal (alist-get 'name p) selection)) projects)))
    (setq hive-mcp-kanban-vibe-default-project (alist-get 'id project))
    (message "Set default project: %s (%s)" selection hive-mcp-kanban-vibe-default-project)))

(defun hive-mcp-org-kanban-api-status ()
  "Get kanban status for API consumption.\nReturns current tasks grouped by status."
  (let* ((tasks (hive-mcp-org-kanban-list-tasks)))
    (backquote ((backend - hive-mcp-org-kanban-backend) (project - hive-mcp-kanban-vibe-default-project) (total - (length tasks)) (by_status - (mapcar (lambda (status)
    (cons status (length (cl-remove-if-not (lambda (tsk)
    (equal (alist-get 'status tsk) status)) tasks)))) (mapcar #'cdr hive-mcp-kanban-protocol-status-map))) (tasks - tasks)))))

(defun hive-mcp-org-kanban-api-my-tasks ()
  "Get tasks assigned to or modified by current agent."
  (let* ((agent (hive-mcp-kanban-protocol--current-agent))
        (tasks (hive-mcp-org-kanban-list-tasks)))
    (cl-remove-if-not (lambda (tsk)
    (or (equal (alist-get 'agent tsk) agent) (equal (alist-get 'last_agent tsk) agent))) tasks)))

(defun hive-mcp-org-kanban-api-roadmap ()
  "Get roadmap view with milestones and progress."
  (let* ((tasks (hive-mcp-org-kanban-list-tasks))
        (total (length tasks))
        (done (length (cl-remove-if-not (lambda (tsk)
    (member (alist-get 'status tsk) '("done" "cancelled"))) tasks))))
    (backquote ((total - total) (completed - done) (progress - (if (> total 0) (round (* 100 (/ (float done) total))) 0)) (in_progress - (cl-remove-if-not (lambda (tsk)
    (equal (alist-get 'status tsk) "inprogress")) tasks)) (next_up - (seq-take (cl-remove-if-not (lambda (tsk)
    (equal (alist-get 'status tsk) "todo")) tasks) 5))))))

(transient-define-prefix hive-mcp-org-kanban-transient (nil) "Kanban management menu." (list "hive-mcp Kanban" (list "View" ("b" "Interactive board" hive-mcp-kanban-board-open-board) ("v" "Text view (ASCII)" hive-mcp-org-kanban-view) ("V" "Text view (Emacs)" (lambda (_unused)
    (interactive "i")
    (hive-mcp-org-kanban-view 'emacs))) ("o" "Open org file" hive-mcp-org-kanban-open-org-file)) (list "Tasks" ("c" "Create task" hive-mcp-org-kanban-create) ("u" "Update status" hive-mcp-org-kanban-update-status)) (list "Settings" ("p" "Set project" hive-mcp-org-kanban-set-project) ("s" "Sync backends" hive-mcp-org-kanban-sync-all) ("d" "Toggle dual mode" hive-mcp-org-kanban-enable-dual-backend))))

(defvar hive-mcp-org-kanban-mode-map (let* ((map (make-sparse-keymap)))
    (define-key map (kbd "C-c M-k") 'hive-mcp-org-kanban-transient)
    map)
  "Keymap for `hive-mcp-org-kanban-mode'.")

(define-minor-mode hive-mcp-org-kanban-mode
  "Minor mode for kanban task tracking with hive-mcp.\n\nProvides:\n- Dual backend support (vibe-kanban + standalone org)\n- Agent-aware task tracking\n- org-kanban UI integration\n- Session continuity\n\n\\{hive-mcp-org-kanban-mode-map}"
  :init-value nil
  :lighter " Kanban"
  :keymap hive-mcp-org-kanban-mode-map
  :global t
  :group 'hive-mcp-kanban
  (if hive-mcp-org-kanban-mode (message "Emacs-mcp-kanban enabled (backend: %s)" hive-mcp-org-kanban-backend) (message "Emacs-mcp-kanban disabled")))

(with-eval-after-load 'hive-mcp-addons
  (hive-mcp-addon-register 'org-kanban :version "0.1.0" :description "Kanban tracking with dual backends (vibe-kanban + standalone org)" :requires '(org) :provides '(hive-mcp-org-kanban-mode hive-mcp-org-kanban-transient)))

(provide 'hive-mcp-org-kanban)
;;; hive-mcp-org-kanban.el ends here
