;;; hive-mcp-swarm.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(require 'clojure-elisp-runtime)
(require 'cl-lib)
(require 'json)
(require 'subr-x)
(require 'hive-mcp-graceful)
(require 'hive-mcp-swarm-events)
(require 'hive-mcp-swarm-prompts)
(require 'hive-mcp-swarm-presets)
(require 'hive-mcp-swarm-terminal)
(require 'hive-mcp-swarm-slaves)
(require 'hive-mcp-swarm-tasks)
(require 'hive-mcp-swarm-hooks)

;;; Code:



(let* ((swarm-dir (expand-file-name "swarm" (file-name-directory (or load-file-name buffer-file-name)))))
    (when (file-directory-p swarm-dir)
    (add-to-list 'load-path swarm-dir)))

(declare-function hive-mcp-swarm-terminal-start-completion-watcher "hive-mcp-swarm-terminal")

(declare-function hive-mcp-swarm-terminal-stop-completion-watcher "hive-mcp-swarm-terminal")

(declare-function hive-mcp-swarm-terminal-start-idle-watcher "hive-mcp-swarm-terminal")

(declare-function hive-mcp-swarm-terminal-stop-idle-watcher "hive-mcp-swarm-terminal")

(declare-function hive-mcp-swarm-terminal-reset-idle-state "hive-mcp-swarm-terminal")

(declare-function hive-mcp-swarm-terminal--record-activity "hive-mcp-swarm-terminal")

(declare-function hive-mcp-swarm-terminal--record-shout "hive-mcp-swarm-terminal")

(declare-function hive-mcp-swarm-terminal--clear-slave-timestamps "hive-mcp-swarm-terminal")

(declare-function hive-mcp-channel-connected-p "hive-mcp-channel")

(declare-function hive-mcp-channel-send "hive-mcp-channel")

(declare-function vterm "vterm")

(declare-function vterm-send-string "vterm")

(declare-function vterm-send-return "vterm")

(declare-function eat "eat")

(declare-function eat-mode "eat")

(declare-function eat-exec "eat")

(declare-function eat-term-send-string "eat")

(declare-function claude-code-ide "claude-code-ide")

(declare-function claude-code-ide--configure-vterm-buffer "claude-code-ide")

(declare-function claude-code-ide--terminal-send-string "claude-code-ide")

(declare-function claude-code-ide--terminal-send-return "claude-code-ide")

(declare-function claude-code-ide-mcp-server-get-session-context "claude-code-ide-mcp-server")

(defvar claude-code-ide-terminal-backend nil)

(defgroup hive-mcp-swarm nil
  "Claude swarm orchestration."
  :group 'hive-mcp
  :prefix "hive-mcp-swarm-")

(defcustom hive-mcp-swarm-presets-dir (expand-file-name "presets" (file-name-directory (or load-file-name buffer-file-name default-directory)))
  "Directory containing built-in preset markdown files."
  :group 'hive-mcp-swarm
  :type 'directory)

(defcustom hive-mcp-swarm-custom-presets-dirs nil
  "List of custom directories to scan for preset .md files.\nDirectories are scanned recursively for .md files only."
  :group 'hive-mcp-swarm
  :type '(repeat directory))

(defcustom hive-mcp-swarm-claude-command "claude"
  "Command to invoke Claude Code CLI."
  :group 'hive-mcp-swarm
  :type 'string)

(defcustom hive-mcp-swarm-terminal 'claude-code-ide
  "Terminal emulator to use for slave sessions.\n- `claude-code-ide': Use claude-code-ide.el WebSocket integration - RECOMMENDED\n  Provides MCP integration, robust session management, no terminal quirks.\n- `vterm': Use vterm (requires native compilation) - ALTERNATIVE\n- `eat': Use eat (pure Emacs Lisp) - EXPERIMENTAL, may have input issues"
  :group 'hive-mcp-swarm
  :type '(choice (const :tag "claude-code-ide (recommended)" claude-code-ide) (const :tag "vterm (native terminal)" vterm) (const :tag "eat (experimental)" eat)))

(defcustom hive-mcp-swarm-max-slaves 30
  "Maximum number of concurrent slave instances."
  :group 'hive-mcp-swarm
  :type 'integer)

(defcustom hive-mcp-swarm-max-depth 3
  "Maximum recursion depth (slaves spawning slaves).\nDepth 0 = master, 1 = child, 2 = grandchild, 3 = great-grandchild.\nBeyond this depth, spawn attempts are blocked to prevent runaway recursion."
  :group 'hive-mcp-swarm
  :type 'integer)

(defcustom hive-mcp-swarm-rate-limit-window 60
  "Time window in seconds for rate limiting spawn attempts."
  :group 'hive-mcp-swarm
  :type 'integer)

(defcustom hive-mcp-swarm-rate-limit-max-spawns 10
  "Maximum number of spawns allowed within `hive-mcp-swarm-rate-limit-window'."
  :group 'hive-mcp-swarm
  :type 'integer)

(defcustom hive-mcp-swarm-default-timeout 300000
  "Default task timeout in milliseconds (5 minutes)."
  :group 'hive-mcp-swarm
  :type 'integer)

(defcustom hive-mcp-swarm-send-verify t
  "If non-nil, verify that prompts were sent to the terminal.\nWhen enabled, dispatch will check the buffer for the prompt text\nand retry if not found."
  :group 'hive-mcp-swarm
  :type 'boolean)

(defcustom hive-mcp-swarm-send-retries 3
  "Number of retry attempts for sending prompts."
  :group 'hive-mcp-swarm
  :type 'integer)

(defcustom hive-mcp-swarm-send-delay 0.2
  "Base delay in seconds between send and return.\nThis delay increases with each retry (exponential backoff)."
  :group 'hive-mcp-swarm
  :type 'float)

(defcustom hive-mcp-swarm-return-delay 0.05
  "Delay in seconds between sending text and sending return.\nHelps ensure vterm processes the text before return is sent."
  :group 'hive-mcp-swarm
  :type 'float)

(defcustom hive-mcp-swarm-auto-approve t
  "If non-nil, automatically approve tool permission prompts.\nClaude Code asks for permission before running tools. This setting\nauto-sends 'y' when permission prompts are detected."
  :group 'hive-mcp-swarm
  :type 'boolean)

(defcustom hive-mcp-swarm-auto-approve-patterns '("Allow\\|Deny" "Yes\\|No" "(y/n)" "[Y/n]" "[y/N]" "Do you want to" "Would you like to" "Proceed\\?")
  "Patterns that indicate a permission/confirmation prompt.\nWhen any of these are found in the buffer, and `hive-mcp-swarm-auto-approve'\nis non-nil, automatically send 'y' to approve."
  :group 'hive-mcp-swarm
  :type '(repeat string))

(defcustom hive-mcp-swarm-prompt-mode 'human
  "How to handle permission prompts in slaves.\n- `human': Forward prompts to master for human decision (RECOMMENDED)\n- `auto': Timer-based auto-approve (use with caution)\n- `bypass': Use --permission-mode bypassPermissions (dangerous, sandboxed only)"
  :group 'hive-mcp-swarm
  :type '(choice (const :tag "Bypass permissions (CLI flag)" bypass) (const :tag "Auto-approve (timer)" auto) (const :tag "Human decision (hooks)" human)))

(defcustom hive-mcp-swarm-prompt-notify t
  "If non-nil, show notification when prompts are pending in human mode."
  :group 'hive-mcp-swarm
  :type 'boolean)

(defcustom hive-mcp-swarm-desktop-notify t
  "If non-nil, send desktop notification via notify-send for prompts.\nThis alerts the human even when running master Claude in a terminal."
  :group 'hive-mcp-swarm
  :type 'boolean)

(defvar hive-mcp-swarm-prompts-buffer-name "*Swarm Prompts*"
  "Buffer name for displaying pending prompts.")

(defcustom hive-mcp-swarm-prompt-marker "❯"
  "Marker indicating Claude is ready for input."
  :group 'hive-mcp-swarm
  :type 'string)

(defcustom hive-mcp-swarm-buffer-prefix "*swarm-"
  "Prefix for swarm buffer names."
  :group 'hive-mcp-swarm
  :type 'string)

(defvar hive-mcp-swarm--slaves (make-hash-table :test 'equal)
  "Hash table of slave-id -> slave plist.")

(defvar hive-mcp-swarm--tasks (make-hash-table :test 'equal)
  "Hash table of task-id -> task plist.")

(defvar hive-mcp-swarm--task-counter 0
  "Counter for generating unique task IDs.")

(defvar hive-mcp-swarm--session-id nil)

(defvar hive-mcp-swarm--current-depth 0
  "Current recursion depth (set via environment).")

(defvar hive-mcp-swarm--spawn-timestamps nil)

(defvar hive-mcp-swarm--ancestry nil)

(defalias 'hive-mcp-swarm--channel-available-p 'hive-mcp-swarm-events-channel-available-p)

(defalias 'hive-mcp-swarm--emit-event 'hive-mcp-swarm-events-emit)

(defalias 'hive-mcp-swarm--emit-task-completed 'hive-mcp-swarm-events-emit-task-completed)

(defalias 'hive-mcp-swarm--emit-task-failed 'hive-mcp-swarm-events-emit-task-failed)

(defalias 'hive-mcp-swarm--emit-prompt-shown 'hive-mcp-swarm-events-emit-prompt-shown)

(defalias 'hive-mcp-swarm--emit-state-changed 'hive-mcp-swarm-events-emit-state-changed)

(defalias 'hive-mcp-swarm--emit-slave-spawned 'hive-mcp-swarm-events-emit-slave-spawned)

(defalias 'hive-mcp-swarm--emit-slave-killed 'hive-mcp-swarm-events-emit-slave-killed)

(defalias 'hive-mcp-swarm--emit-auto-completed 'hive-mcp-swarm-events-emit-auto-completed)

(defalias 'hive-mcp-swarm--emit-auto-started 'hive-mcp-swarm-events-emit-auto-started)

(defalias 'hive-mcp-swarm--emit-auto-error 'hive-mcp-swarm-events-emit-auto-error)

(provide 'hive-mcp-swarm)
;;; hive-mcp-swarm.el ends here
