;;; hive-mcp-vibe-kanban.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(require 'clojure-elisp-runtime)
(require 'hive-mcp-api)

;;; Code:



(defgroup hive-mcp-vibe-kanban nil
  "Vibe Kanban integration for hive-mcp."
  :group 'hive-mcp
  :prefix "hive-mcp-vibe-kanban-")

(defcustom auto-start t
  "When non-nil, automatically start vibe-kanban server on addon load.\nThe server starts asynchronously and does not block Emacs startup."
  :group 'hive-mcp-vibe-kanban
  :type 'boolean)

(defcustom command "npx"
  "Command to run vibe-kanban.\nDefault is `npx' which auto-installs if needed."
  :group 'hive-mcp-vibe-kanban
  :type 'string)

(defcustom args '("vibe-kanban")
  "Arguments to pass to the vibe-kanban command."
  :group 'hive-mcp-vibe-kanban
  :type '(repeat string))

(defcustom port 3333
  "Port for vibe-kanban server."
  :group 'hive-mcp-vibe-kanban
  :type 'integer)

(defcustom project-dir nil
  "Project directory for vibe-kanban.\nIf nil, uses current project root or `default-directory'."
  :group 'hive-mcp-vibe-kanban
  :type '(choice (const nil) directory))

(defvar hive-mcp-vibe-kanban--process nil
  "Process object for the vibe-kanban server.")

(defvar hive-mcp-vibe-kanban--buffer-name "*vibe-kanban*"
  "Buffer name for vibe-kanban output.")

(defun hive-mcp-vibe-kanban---project-dir ()
  "Get the project directory for vibe-kanban."
  (or hive-mcp-vibe-kanban-project-dir (when (fboundp 'project-root)
    (when-let-star (list proj (project-current)) (project-root proj))) default-directory))

(defun hive-mcp-vibe-kanban---running-p ()
  "Return non-nil if vibe-kanban server is running."
  (and hive-mcp-vibe-kanban--process (process-live-p hive-mcp-vibe-kanban--process)))

(defun hive-mcp-vibe-kanban---start-async ()
  "Start vibe-kanban server asynchronously.\nReturns the process object."
  (unless (hive-mcp-vibe-kanban--running-p)
    (let* ((default-directory (hive-mcp-vibe-kanban--project-dir))
        (buf (get-buffer-create hive-mcp-vibe-kanban--buffer-name)))
    (message "hive-mcp-vibe-kanban: Starting server...")
    (setq hive-mcp-vibe-kanban--process (apply #'start-process "vibe-kanban" buf hive-mcp-vibe-kanban-command hive-mcp-vibe-kanban-args))
    (set-process-sentinel hive-mcp-vibe-kanban--process (lambda (proc event)
    (message "hive-mcp-vibe-kanban: %s" (string-trim event))))
    hive-mcp-vibe-kanban--process)))

(defun hive-mcp-vibe-kanban---stop ()
  "Stop the vibe-kanban server."
  (when (hive-mcp-vibe-kanban--running-p)
    (kill-process hive-mcp-vibe-kanban--process)
    (setq hive-mcp-vibe-kanban--process nil)
    (message "hive-mcp-vibe-kanban: Server stopped")))

(defun hive-mcp-vibe-kanban-start ()
  "Start the vibe-kanban server."
  (interactive)
  (if (hive-mcp-vibe-kanban--running-p) (message "hive-mcp-vibe-kanban: Server already running") (hive-mcp-vibe-kanban--start-async)))

(defun hive-mcp-vibe-kanban-stop ()
  "Stop the vibe-kanban server."
  (interactive)
  (hive-mcp-vibe-kanban--stop))

(defun hive-mcp-vibe-kanban-restart ()
  "Restart the vibe-kanban server."
  (interactive)
  (hive-mcp-vibe-kanban--stop)
  (sit-for 0.5)
  (hive-mcp-vibe-kanban--start-async))

(defun hive-mcp-vibe-kanban-status ()
  "Show vibe-kanban server status."
  (interactive)
  (message "hive-mcp-vibe-kanban: %s" (if (hive-mcp-vibe-kanban--running-p) "Running" "Stopped")))

(defun hive-mcp-vibe-kanban-show-buffer ()
  "Show the vibe-kanban output buffer."
  (interactive)
  (if-let-star (list buf (get-buffer hive-mcp-vibe-kanban--buffer-name)) (display-buffer buf) (message "hive-mcp-vibe-kanban: No output buffer")))

(defun hive-mcp-vibe-kanban---addon-init ()
  "Synchronous init for vibe-kanban addon."
  (require 'hive-mcp-api nil t)
  (message "hive-mcp-vibe-kanban: initialized"))

(defun hive-mcp-vibe-kanban---addon-async-init ()
  "Asynchronous init for vibe-kanban addon.\nStarts the server in background if auto-start is enabled.\nReturns the process object for lifecycle tracking."
  (when hive-mcp-vibe-kanban-auto-start
    (hive-mcp-vibe-kanban--start-async)))

(defun hive-mcp-vibe-kanban---addon-shutdown ()
  "Shutdown function for vibe-kanban addon."
  (hive-mcp-vibe-kanban--stop)
  (message "hive-mcp-vibe-kanban: shutdown complete"))

(transient-define-prefix hive-mcp-vibe-kanban-transient ()
  "Vibe Kanban control menu."
  ["Vibe Kanban" ["Server" ("s" "Start" hive-mcp-vibe-kanban-start) ("S" "Stop" hive-mcp-vibe-kanban-stop) ("r" "Restart" hive-mcp-vibe-kanban-restart) ("?" "Status" hive-mcp-vibe-kanban-status)] ["View" ("b" "Show buffer" hive-mcp-vibe-kanban-show-buffer)]])

(with-eval-after-load 'hive-mcp-addons
  (hive-mcp-addon-register 'vibe-kanban :version "0.1.0" :description "Vibe Kanban task management server" :requires '(hive-mcp-api) :provides '(hive-mcp-vibe-kanban-transient) :init #'-addon-init :async-init #'-addon-async-init :shutdown #'-addon-shutdown))

(provide 'hive-mcp-vibe-kanban)
;;; hive-mcp-vibe-kanban.el ends here
