;;; hive-mcp-cider-sessions.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(eval-and-compile (require 'clojure-elisp-runtime))

;;; Code:



(require 'cl-lib)

(defcustom hive-mcp-cider-sessions-port-base 7920
  "Base port for spawning new CIDER sessions.\nSessions will use ports starting from this value."
  :group 'hive-mcp-cider
  :type 'integer)

(defcustom hive-mcp-cider-sessions-port-max 7999
  "Maximum port for CIDER sessions."
  :group 'hive-mcp-cider
  :type 'integer)

(defvar hive-mcp-cider-sessions--registry (make-hash-table :test 'equal)
  "Registry of named CIDER sessions.\nKeys are session names (strings).\nValues are plists with :port, :process, :buffer, :agent-id, :project-dir,\n:repl-type, :status, :cider-buffer, :timer.")

(defun hive-mcp-cider-sessions-registry-has-name-p (name)
  "Return non-nil when NAME is present, including when its stored value is nil."
  (let* ((missing (make-symbol "missing-session")))
    (not (eq (gethash name hive-mcp-cider-sessions--registry missing) missing))))

(defun hive-mcp-cider-sessions-register (name props)
  "Register a session NAME with PROPS plist in the registry.\nSignals error if NAME already exists."
  (unless (and name (stringp name))
    (error "Invalid session name: %S" name))
  (when (hive-mcp-cider-sessions-registry-has-name-p name)
    (error "Session '%s' already exists" name))
  (puthash name props hive-mcp-cider-sessions--registry)
  props)

(defun hive-mcp-cider-sessions-unregister (name)
  "Remove session NAME from the registry. Returns removed plist or nil."
  (let* ((session (gethash name hive-mcp-cider-sessions--registry)))
    (remhash name hive-mcp-cider-sessions--registry)
    session))

(defun hive-mcp-cider-sessions-lookup (name)
  "Get session plist for NAME, or nil if not found."
  (gethash name hive-mcp-cider-sessions--registry))

(defun hive-mcp-cider-sessions-get-prop (name key)
  "Get property KEY from session NAME. Returns nil if session or key not found."
  (plist-get (gethash name hive-mcp-cider-sessions--registry) key))

(defun hive-mcp-cider-sessions-update-prop (name key value)
  "Set property KEY to VALUE in session NAME.\nSignals error if session not found."
  (let* ((session (gethash name hive-mcp-cider-sessions--registry)))
    (unless session
    (error "Session '%s' not found" name))
    (puthash name (plist-put session key value) hive-mcp-cider-sessions--registry)
    value))

(defun hive-mcp-cider-sessions-update-props (name &rest kvs)
  "Set multiple properties in session NAME from key-value pairs.\nSignals error if session not found."
  (let* ((session (gethash name hive-mcp-cider-sessions--registry)))
    (unless session
    (error "Session '%s' not found" name))
    (while kvs
    (setq session (plist-put session (car kvs) (cadr kvs)))
    (setq kvs (cddr kvs)))
    (puthash name session hive-mcp-cider-sessions--registry)
    session))

(defun hive-mcp-cider-sessions-exists-p (name)
  "Return non-nil if session NAME exists."
  (hive-mcp-cider-sessions-registry-has-name-p name))

(defun hive-mcp-cider-sessions-enum-label (value fallback)
  "Return FALLBACK for nil, symbol name for symbols, or VALUE unchanged."
  (cond
  ((null value) fallback)
  ((symbolp value) (symbol-name value))
  (t value)))

(defun hive-mcp-cider-sessions-list-all ()
  "Return a vector of session info plists for JSON encoding.\nEach entry contains :name, :port, :repl-type, :status, :agent-id, :cider-buffer."
  (let* ((sessions '()))
    (maphash (lambda (name props)
    (when (stringp name)
    (let* ((status (plist-get props :status))
        (rtype (plist-get props :repl-type)))
    (push (list :name name :port (plist-get props :port) :repl-type (hive-mcp-cider-sessions-enum-label rtype "clj") :status (hive-mcp-cider-sessions-enum-label status "unknown") :agent-id (plist-get props :agent-id) :cider-buffer (plist-get props :cider-buffer)) sessions)))) hive-mcp-cider-sessions--registry)
    (vconcat sessions)))

(defun hive-mcp-cider-sessions-find-by-status (status)
  "Find first session name with STATUS (symbol). Returns name string or nil."
  (let* ((result nil))
    (maphash (lambda (name props)
    (when (and (stringp name) (not result) (eq (plist-get props :status) status))
    (setq result name))) hive-mcp-cider-sessions--registry)
    result))

(defun hive-mcp-cider-sessions-clear-all ()
  "Remove all sessions from registry."
  (clrhash hive-mcp-cider-sessions--registry))

(defun hive-mcp-cider-sessions-count-sessions ()
  "Return the number of registered sessions."
  (hash-table-count hive-mcp-cider-sessions--registry))

(defun hive-mcp-cider-sessions-names ()
  "Return list of all session names."
  (hash-table-keys hive-mcp-cider-sessions--registry))

(defun hive-mcp-cider-sessions-find-available-port (port-check-fn)
  "Find next available port in the session range.\nPORT-CHECK-FN is a predicate (port) -> bool that returns t if port is in use."
  (let* ((port hive-mcp-cider-sessions-port-base)
        (used-ports (mapcar (lambda (name)
    (plist-get (gethash name hive-mcp-cider-sessions--registry) :port)) (hash-table-keys hive-mcp-cider-sessions--registry))))
    (while (and (<= port hive-mcp-cider-sessions-port-max) (or (member port used-ports) (funcall port-check-fn port)))
    (setq port (1+ port)))
    (if (<= port hive-mcp-cider-sessions-port-max) port (error "No available ports in range %d-%d" hive-mcp-cider-sessions-port-base hive-mcp-cider-sessions-port-max))))

(defun hive-mcp-cider-sessions-make-session (port &rest kvs)
  "Create a session plist with PORT and optional KVS overrides.\nDefaults: :process nil, :buffer nil, :agent-id nil, :project-dir nil,\n:repl-type 'clj, :status 'starting, :cider-buffer nil, :timer nil."
  (let* ((session (list :port port :process nil :buffer nil :agent-id nil :project-dir nil :repl-type 'clj :status 'starting :cider-buffer nil :timer nil)))
    (while kvs
    (setq session (plist-put session (car kvs) (cadr kvs)))
    (setq kvs (cddr kvs)))
    session))

(provide 'hive-mcp-cider-sessions)
;;; hive-mcp-cider-sessions.el ends here
