;;; hive-mcp-cider-nrepl-test.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(eval-and-compile
  (require 'clojure-elisp-runtime)
  (unless (and (boundp 'clel-runtime-version)
               (version<= "0.7.2" clel-runtime-version))
    (error "clojure-elisp-runtime %s is too old for this file (needs %s)"
           (if (boundp 'clel-runtime-version) clel-runtime-version "(pre-0.7.2)")
           "0.7.2")))
(require 'cl-lib)

;;; Code:



(require 'ert)

(require 'hive-mcp-cider-nrepl)

(ert-deftest hive-mcp-cider-nrepl-test-launch-flag-default nil "No aliases means a plain -M, which needs no alias in the target project." (should (equal "-M" (hive-mcp-cider-nrepl-launch-flag nil))) (should (equal "-M" (hive-mcp-cider-nrepl-launch-flag '()))))

(ert-deftest hive-mcp-cider-nrepl-test-launch-flag-aliases nil "Alias names are appended colon-separated; a leading colon is tolerated." (should (equal "-M:dev" (hive-mcp-cider-nrepl-launch-flag '("dev")))) (should (equal "-M:dev:test" (hive-mcp-cider-nrepl-launch-flag '(":dev" "test")))))

(ert-deftest hive-mcp-cider-nrepl-test-launch-flag-ignores-blanks nil "Empty and nil alias entries are dropped rather than emitting a bare colon." (should (equal "-M" (hive-mcp-cider-nrepl-launch-flag '("" nil)))) (should (equal "-M:dev" (hive-mcp-cider-nrepl-launch-flag '("" "dev")))))

(ert-deftest hive-mcp-cider-nrepl-test-build-command-inline-deps nil "The clj command spawns via inline -Sdeps and a plain -M, never -M:dev." (let* ((cmd (let* ((hive-mcp-cider-nrepl-launch-aliases nil))
    (hive-mcp-cider-nrepl-build-command 'clj 7999))))
    (should (equal "clojure" (car cmd)))
    (should (member "-Sdeps" cmd))
    (should (member "-M" cmd))
    (should-not (member "-M:dev" cmd))
    (should (member "7999" cmd))
    (should (member "nrepl.cmdline" cmd))))

(ert-deftest hive-mcp-cider-nrepl-test-build-command-honors-aliases nil "`hive-mcp-cider-nrepl-launch-aliases' selects the -M flag." (let* ((cmd (let* ((hive-mcp-cider-nrepl-launch-aliases '("dev")))
    (hive-mcp-cider-nrepl-build-command 'clj 7999))))
    (should (member "-M:dev" cmd))
    (should-not (member "-M" cmd))))

(ert-deftest hive-mcp-cider-nrepl-test-build-command-rejects-extra-arity nil "build-command takes (repl-type port &optional extra-args aliases extra-deps\nmiddleware) — a seventh argument signals." (should-error (hive-mcp-cider-nrepl-build-command 'clj 7999 nil nil nil nil nil)))

(ert-deftest hive-mcp-cider-nrepl-test-build-command-cljel-middleware nil "The cljel command pins the canonical clojure-elisp checkout and its middleware." (let* ((cmd (let* ((hive-mcp-cider-nrepl-cljel-project-dir "/tmp/clojure-elisp"))
    (hive-mcp-cider-nrepl-build-command 'cljel 7922)))
        (deps (car (cdr (cdr cmd)))))
    (should (string-match-p "/tmp/clojure-elisp" deps))
    (should (member "--middleware" cmd))
    (should (car (delq nil (mapcar (lambda (a)
    (and (stringp a) (string-match-p "wrap-cljel" a))) cmd))))))

(ert-deftest hive-mcp-cider-nrepl-test-build-command-cljs-watches-build nil "The cljs branch shells out to shadow-cljs with the configured build id." (let* ((cmd (let* ((hive-mcp-cider-nrepl-shadow-build ":app"))
    (hive-mcp-cider-nrepl-build-command 'cljs 9630))))
    (should (equal "npx" (car cmd)))
    (should (member ":app" cmd))))

(ert-deftest hive-mcp-cider-nrepl-test-default-dir-explicit-wins nil "An explicit DIR outranks both defcustoms." (let ((hive-mcp-cider-nrepl-project-dir "/tmp/configured")
        (hive-mcp-cider-nrepl-default-project-dir "/tmp/fallback"))
    (should (equal (expand-file-name "/tmp/explicit") (hive-mcp-cider-nrepl-default-project-dir "/tmp/explicit")))))

(ert-deftest hive-mcp-cider-nrepl-test-default-dir-project-then-fallback nil "Without DIR the project defcustom wins, and the fallback covers its nil." (let ((hive-mcp-cider-nrepl-default-project-dir "/tmp/fallback"))
    (let ((hive-mcp-cider-nrepl-project-dir "/tmp/configured"))
    (should (equal (expand-file-name "/tmp/configured") (hive-mcp-cider-nrepl-default-project-dir nil))))
    (let ((hive-mcp-cider-nrepl-project-dir nil))
    (should (equal (expand-file-name "/tmp/fallback") (hive-mcp-cider-nrepl-default-project-dir nil))))))

(ert-deftest hive-mcp-cider-nrepl-test-default-dir-nil-when-unset nil "Nothing configured resolves to nil — never to an accidental default." (let ((hive-mcp-cider-nrepl-project-dir nil)
        (hive-mcp-cider-nrepl-default-project-dir nil))
    (should-not (hive-mcp-cider-nrepl-default-project-dir nil))) (let ((hive-mcp-cider-nrepl-project-dir "")
        (hive-mcp-cider-nrepl-default-project-dir nil))
    (should-not (hive-mcp-cider-nrepl-default-project-dir nil))))

(ert-deftest hive-mcp-cider-nrepl-test-start-default-names-missing-setting nil "With nothing configured start-default names the settings instead of\nsignalling `stringp, nil' from start-process." (let* ((hive-mcp-cider-nrepl-project-dir nil)
        (hive-mcp-cider-nrepl-default-project-dir nil)
        (message nil))
    (cl-letf (((symbol-function 'start-process) (lambda (&rest _)
    (error "start-process must not run")))) (condition-case e
    (hive-mcp-cider-nrepl-start-default)
  (error (setq message (error-message-string e)))))
    (should (string-match-p "no directory for the default nREPL server" message))
    (should (string-match-p "hive-mcp-cider-nrepl-default-project-dir" message))))

(ert-deftest hive-mcp-cider-nrepl-test-start-default-rejects-missing-dir nil "A configured directory that does not exist is reported by name." (let* ((hive-mcp-cider-nrepl-project-dir "/tmp/hive-mcp-cider-nrepl-absent")
        (hive-mcp-cider-nrepl-default-project-dir nil)
        (message nil))
    (cl-letf (((symbol-function 'start-process) (lambda (&rest _)
    (error "start-process must not run")))) (condition-case e
    (hive-mcp-cider-nrepl-start-default)
  (error (setq message (error-message-string e)))))
    (should (string-match-p "does not exist" message))
    (should (string-match-p "hive-mcp-cider-nrepl-absent" message))))

(ert-deftest hive-mcp-cider-nrepl-test-start-default-spawns-in-resolved-dir nil "start-default runs in the resolved directory with the inline -Sdeps command." (let* ((dir (make-temp-file "hive-mcp-cider-nrepl-test" t))
        (captured nil))
    (unwind-protect
    (let* ((hive-mcp-cider-nrepl-project-dir nil)
        (hive-mcp-cider-nrepl-default-project-dir dir)
        (hive-mcp-cider-nrepl-launch-aliases nil)
        (hive-mcp-cider-nrepl-oom-score-adj nil))
    (cl-letf (((symbol-function 'start-process) (lambda (name buffer &rest cmd)
    (setq captured (list default-directory name buffer cmd))
    'stub-process))) (should (eq 'stub-process (hive-mcp-cider-nrepl-start-default))))
    (should (equal (file-name-as-directory dir) (car captured)))
    (should (equal "nrepl-server" (car (cdr captured))))
    (let* ((cmd (car (cdr (cdr (cdr captured))))))
    (should (equal "clojure" (car cmd)))
    (should (member "-Sdeps" cmd))
    (should (member "-M" cmd))
    (should-not (member "-M:dev" cmd))
    (should (member (number-to-string hive-mcp-cider-nrepl-port) cmd)))
    (should (eq 'stub-process hive-mcp-cider-nrepl--default-process)))
  (setq hive-mcp-cider-nrepl--default-process nil)
  (delete-directory dir t))))

(ert-deftest hive-mcp-cider-nrepl-test-start-default-explicit-dir-wins nil "An explicit DIR overrides the configured project directory." (let* ((dir (make-temp-file "hive-mcp-cider-nrepl-test" t))
        (captured nil))
    (unwind-protect
    (let* ((hive-mcp-cider-nrepl-project-dir "/tmp/hive-mcp-cider-nrepl-absent")
        (hive-mcp-cider-nrepl-default-project-dir nil))
    (cl-letf (((symbol-function 'start-process) (lambda (_name _buffer &rest _cmd)
    (setq captured default-directory)
    'stub-process))) (hive-mcp-cider-nrepl-start-default dir))
    (should (equal (file-name-as-directory dir) captured)))
  (setq hive-mcp-cider-nrepl--default-process nil)
  (delete-directory dir t))))

(ert-deftest hive-mcp-cider-nrepl-test-launch-process-requires-a-dir nil "A clj session with no configured directory refuses to spawn." (let* ((hive-mcp-cider-nrepl-project-dir nil)
        (message nil))
    (cl-letf (((symbol-function 'start-process) (lambda (&rest _)
    (error "start-process must not run")))) (condition-case e
    (hive-mcp-cider-nrepl-launch-process "s" 7999 'clj)
  (error (setq message (error-message-string e)))))
    (should (string-match-p "no project-dir for session" message))))

(ert-deftest hive-mcp-cider-nrepl-test-launch-process-uses-dir-as-cwd nil "The passed DIR becomes the process working directory, not a command argument." (let* ((dir (make-temp-file "hive-mcp-cider-nrepl-test" t))
        (captured nil))
    (unwind-protect
    (cl-letf (((symbol-function 'start-process) (lambda (name buffer &rest cmd)
    (setq captured (list default-directory name buffer cmd))
    'stub-process))) (should (eq 'stub-process (hive-mcp-cider-nrepl-launch-process "s" 7999 'clj dir))) (should (equal (file-name-as-directory dir) (car captured))) (should (equal "nrepl-s" (car (cdr captured)))) (should-not (member dir (car (cdr (cdr (cdr captured)))))))
  (delete-directory dir t))))

(defun hive-mcp-cider-nrepl-test-run-tests ()
  "Run all hive-mcp-cider-nrepl ERT tests in batch."
  (interactive)
  (ert-run-tests-batch-and-exit "^hive-mcp-cider-nrepl-test-"))

(ert-deftest hive-mcp-cider-nrepl-test-build-command-cljrs-src-paths nil "The cljrs branch passes one --src-path per configured native source root." (let* ((cmd (let* ((hive-mcp-cider-nrepl-cljrs-binary "/tmp/cljrs")
        (hive-mcp-cider-nrepl-native-source-roots '("src" "test")))
    (hive-mcp-cider-nrepl-build-command 'cljrs 7921))))
    (should (equal "nrepl" (car (cdr cmd))))
    (should (member "7921" cmd))
    (should (equal '("--src-path" "src" "--src-path" "test") (cdr (cdr (cdr (cdr cmd))))))))

(ert-deftest hive-mcp-cider-nrepl-test-build-command-cljw-classpath nil "A cljw resolved as accepting -cp receives the roots colon-joined.\nThe transport is resolved rather than assumed: setting\n`hive-mcp-cider-runtime-cljw-classpath' answers the top rung of the chain,\nso no binary is probed. cljw's nrepl subcommand takes a single -cp of\ncolon-separated dirs, unlike cljrs's repeated --src-path." (let* ((cmd (let* ((hive-mcp-cider-nrepl-cljw-binary "/tmp/cljw")
        (hive-mcp-cider-runtime-cljw-classpath :cp)
        (hive-mcp-cider-nrepl-native-source-roots '("src" "test")))
    (hive-mcp-cider-nrepl-build-command 'cljw 7920))))
    (should (equal "nrepl" (car (cdr cmd))))
    (should (member "7920" cmd))
    (should (equal '("-cp" "src:test") (cdr (cdr (cdr (cdr cmd))))))
    (should-not (member "--src-path" cmd))))

(ert-deftest hive-mcp-cider-nrepl-test-cljw-classpath-unsupported-warns nil "A cljw with no classpath mechanism drops the roots and says so.\nThe argv carries no -cp — a build without the fix exits 1 on one — and the\nplan carries a :classpath-unsupported diagnostic naming the roots, so a\nclasspath-less launch is announced rather than silently accepted." (let* ((plan (let* ((hive-mcp-cider-nrepl-cljw-binary "/tmp/cljw")
        (hive-mcp-cider-runtime-cljw-classpath :none)
        (hive-mcp-cider-nrepl-native-source-roots '("src" "test")))
    (hive-mcp-cider-nrepl-launch-plan 'cljw 7920))))
    (should (equal 4 (length (plist-get plan :command))))
    (should-not (member "-cp" (plist-get plan :command)))
    (let* ((diag (car (plist-get plan :diagnostics))))
    (should (eq :warn (plist-get diag :level)))
    (should (eq :classpath-unsupported (plist-get diag :code)))
    (should (string-match-p "src test" (plist-get diag :message))))))

(ert-deftest hive-mcp-cider-nrepl-test-build-command-cljw-no-roots-no-cp nil "With no configured source roots the cljw branch emits no -cp at all.\nAn empty -cp would otherwise shadow $CLJW_PATH and the ./deps.edn :paths\nfallback, which are the other two rungs of cljw's own classpath resolution.\nNothing is reported either — there were no roots to drop." (let* ((plan (let* ((hive-mcp-cider-nrepl-cljw-binary "/tmp/cljw")
        (hive-mcp-cider-runtime-cljw-classpath :cp)
        (hive-mcp-cider-nrepl-native-source-roots nil))
    (hive-mcp-cider-nrepl-launch-plan 'cljw 7920))))
    (should (equal 4 (length (plist-get plan :command))))
    (should-not (member "-cp" (plist-get plan :command)))
    (should-not (plist-get plan :diagnostics))))

(ert-deftest hive-mcp-cider-nrepl-test-build-command-appends-middleware nil "MIDDLEWARE strings append to the built-in list for the repl type." (let* ((cmd (let* ((hive-mcp-cider-nrepl-launch-aliases nil))
    (hive-mcp-cider-nrepl-build-command 'clj 7999 nil nil nil '("refactor-nrepl.middleware/wrap-refactor")))))
    (should (member "[cider.nrepl/cider-middleware,refactor-nrepl.middleware/wrap-refactor]" cmd))) (let* ((cmd (let* ((hive-mcp-cider-nrepl-cljel-project-dir "/tmp/clojure-elisp"))
    (hive-mcp-cider-nrepl-build-command 'cljel 7999 nil nil nil '("my.mw/wrap-x")))))
    (should (member "[cider.nrepl/cider-middleware,clojure-elisp.nrepl/wrap-cljel,my.mw/wrap-x]" cmd))))

(ert-deftest hive-mcp-cider-nrepl-test-launch-process-explicit-extra-deps nil "Explicit EXTRA-DEPS merge after the auto-detected local deps (later wins)." (let* ((dir (make-temp-file "hive-mcp-cider-nrepl-test" t))
        (captured nil))
    (unwind-protect
    (let* ((hive-mcp-cider-nrepl-local-deps-files '("local.deps.edn"))
        (hive-mcp-cider-nrepl-launch-aliases nil))
    (with-temp-file (expand-file-name "local.deps.edn" dir) (insert "{:deps {my/lib {:local/root \"../lib\"}}}"))
    (cl-letf (((symbol-function 'start-process) (lambda (name buffer &rest cmd)
    (setq captured cmd)
    'stub-process))) (should (eq 'stub-process (hive-mcp-cider-nrepl-launch-process "s" 7999 'clj dir nil nil '("{:deps {other/lib {:mvn/version \"1.0.0\"}}}")))) (let* ((sdeps-pos (cl-position "-Sdeps" captured :test #'equal))
        (sdeps-val (clel-nth captured (+ 1 sdeps-pos))))
    (should (string-match-p "nrepl/nrepl" sdeps-val))
    (should (string-match-p "my/lib" sdeps-val))
    (should (string-match-p "other/lib" sdeps-val)))))
  (delete-directory dir t))))

(ert-deftest hive-mcp-cider-nrepl-test-local-deps-contents-detects-file nil "A local.deps.edn in DIR yields its contents, in probe order." (let* ((dir (make-temp-file "hive-mcp-cider-nrepl-test" t)))
    (unwind-protect
    (let* ((hive-mcp-cider-nrepl-local-deps-files '("local.deps.edn")))
    (with-temp-file (expand-file-name "local.deps.edn" dir) (insert "{:deps {my/lib {:local/root \"../lib\"}}}"))
    (should (equal '("{:deps {my/lib {:local/root \"../lib\"}}}") (hive-mcp-cider-nrepl-local-deps-contents dir))))
  (delete-directory dir t))))

(ert-deftest hive-mcp-cider-nrepl-test-local-deps-contents-absent-and-disabled nil "No probe file means no contents; a nil defcustom disables detection entirely." (let* ((dir (make-temp-file "hive-mcp-cider-nrepl-test" t)))
    (unwind-protect
    (progn
  (let* ((hive-mcp-cider-nrepl-local-deps-files '("local.deps.edn")))
    (should-not (hive-mcp-cider-nrepl-local-deps-contents dir)))
  (let* ((hive-mcp-cider-nrepl-local-deps-files nil))
    (with-temp-file (expand-file-name "local.deps.edn" dir) (insert "{:deps {}}"))
    (should-not (hive-mcp-cider-nrepl-local-deps-contents dir))))
  (delete-directory dir t))))

(ert-deftest hive-mcp-cider-nrepl-test-merge-deps-edn-merges-into-one-sdeps nil "Overrides merge key-wise into the base map — the CLI keeps only the last\n-Sdeps, so the spawn command must carry ONE merged map." (let* ((merged (hive-mcp-cider-nrepl-merge-deps-edn "{:deps {nrepl/nrepl {:mvn/version \"1.7.0\"}}}" '("{:deps {my/lib {:local/root \"../lib\"}}}" "{:aliases {:test {}}}"))))
    (should (string-match-p "nrepl/nrepl" merged))
    (should (string-match-p "my/lib" merged))
    (should (string-match-p ":test" merged))) (should (string-match-p "0.62.2" (hive-mcp-cider-nrepl-merge-deps-edn "{:deps {cider/cider-nrepl {:mvn/version \"0.1.0\"}}}" '("{:deps {cider/cider-nrepl {:mvn/version \"0.62.2\"}}}")))))

(ert-deftest hive-mcp-cider-nrepl-test-launch-process-merges-local-deps nil "launch-process carries ONE -Sdeps merging built-in nrepl deps with\nlocal.deps.edn, and it lands before -M." (let* ((dir (make-temp-file "hive-mcp-cider-nrepl-test" t))
        (captured nil))
    (unwind-protect
    (let* ((hive-mcp-cider-nrepl-local-deps-files '("local.deps.edn"))
        (hive-mcp-cider-nrepl-launch-aliases nil))
    (with-temp-file (expand-file-name "local.deps.edn" dir) (insert "{:deps {my/lib {:local/root \"../lib\"}}}"))
    (cl-letf (((symbol-function 'start-process) (lambda (name buffer &rest cmd)
    (setq captured cmd)
    'stub-process))) (should (eq 'stub-process (hive-mcp-cider-nrepl-launch-process "s" 7999 'clj dir))) (should (equal 1 (length (delq nil (mapcar (lambda (a)
    (and (stringp a) (string= "-Sdeps" a))) captured))))) (let* ((sdeps-pos (cl-position "-Sdeps" captured :test #'equal))
        (sdeps-val (clel-nth captured (+ 1 sdeps-pos)))
        (m-pos (cl-position "-M" captured :test #'equal)))
    (should (string-match-p "nrepl/nrepl" sdeps-val))
    (should (string-match-p "my/lib" sdeps-val))
    (should (< sdeps-pos m-pos)))))
  (delete-directory dir t))))

(ert-deftest hive-mcp-cider-nrepl-test-build-command-extra-args-exact-argv nil "EXTRA-ARGS splice raw after -Sdeps and before the -M flag. A raw -Sdeps\nthere REPLACES the built-in one (the CLI keeps only the last) — merge-style\nlayering belongs in EXTRA-DEPS, not EXTRA-ARGS." (let* ((cmd (let* ((hive-mcp-cider-nrepl-launch-aliases nil)
        (hive-mcp-cider-nrepl-version "1.7.0")
        (hive-mcp-cider-nrepl-cider-nrepl-version "0.62.2"))
    (hive-mcp-cider-nrepl-build-command 'clj 7999 '("-Sdeps" "{:deps {my/lib {:local/root \"../lib\"}}}") '("test"))))
        (sdeps (clel-nth cmd 2)))
    (should (string-match-p "nrepl/nrepl" sdeps))
    (should (string-match-p "cider/cider-nrepl" sdeps))
    (should (equal (cdr (cdr (cdr cmd))) '("-Sdeps" "{:deps {my/lib {:local/root \"../lib\"}}}" "-M:test" "-m" "nrepl.cmdline" "--port" "7999" "--middleware" "[cider.nrepl/cider-middleware]")))))

(ert-deftest hive-mcp-cider-nrepl-test-neutralizer-nil-without-aliases nil "No aliases means no override map at all — the bare -M path is untouched." (should-not (hive-mcp-cider-nrepl-main-opts-neutralizer nil)) (should-not (hive-mcp-cider-nrepl-main-opts-neutralizer '("" nil))))

(ert-deftest hive-mcp-cider-nrepl-test-neutralizer-blanks-each-alias nil "Every selected alias gets :main-opts [], colon-prefixed names tolerated." (should (equal "{:aliases {:test {:main-opts []}}}" (hive-mcp-cider-nrepl-main-opts-neutralizer '("test")))) (should (equal "{:aliases {:dev {:main-opts []} :test {:main-opts []}}}" (hive-mcp-cider-nrepl-main-opts-neutralizer '(":dev" "test")))))

(ert-deftest hive-mcp-cider-nrepl-test-build-command-blanks-alias-main-opts nil "The spawn -Sdeps blanks the selected alias's :main-opts. Without this a\n:test alias carrying :main-opts [\"-m\" \"cognitect.test-runner\"] runs the\ntest runner, chokes on --port/--middleware, and no nREPL ever listens." (let* ((cmd (let* ((hive-mcp-cider-nrepl-launch-aliases nil))
    (hive-mcp-cider-nrepl-build-command 'clj 7999 nil '("test"))))
        (sdeps (clel-nth cmd 2)))
    (should (member "-M:test" cmd))
    (should (string-match-p ":aliases" sdeps))
    (should (string-match-p ":main-opts" sdeps))
    (should (string-match-p "nrepl/nrepl" sdeps))))

(ert-deftest hive-mcp-cider-nrepl-test-build-command-no-aliases-no-override nil "Without aliases the -Sdeps map carries deps only — no :aliases key." (let* ((cmd (let* ((hive-mcp-cider-nrepl-launch-aliases nil))
    (hive-mcp-cider-nrepl-build-command 'clj 7999)))
        (sdeps (clel-nth cmd 2)))
    (should-not (string-match-p ":aliases" sdeps))))

(ert-deftest hive-mcp-cider-nrepl-test-neutralizer-wins-over-extra-deps nil "The blank is merged LAST, so EXTRA-DEPS cannot re-arm the alias's :main-opts." (let* ((cmd (let* ((hive-mcp-cider-nrepl-launch-aliases nil))
    (hive-mcp-cider-nrepl-build-command 'clj 7999 nil '("test") '("{:aliases {:test {:main-opts [\"-m\" \"cognitect.test-runner\"]}}}"))))
        (sdeps (clel-nth cmd 2)))
    (should-not (string-match-p "cognitect.test-runner" sdeps))))

(ert-deftest hive-mcp-cider-nrepl-test-cljel-blanks-alias-main-opts nil "The cljel branch shares the neutralizer — it too runs through -M:alias." (let* ((cmd (let* ((hive-mcp-cider-nrepl-cljel-project-dir "/tmp/clojure-elisp"))
    (hive-mcp-cider-nrepl-build-command 'cljel 7999 nil '("dev"))))
        (sdeps (clel-nth cmd 2)))
    (should (member "-M:dev" cmd))
    (should (string-match-p ":main-opts" sdeps))))

(ert-deftest hive-mcp-cider-nrepl-test-build-command-per-spawn-aliases-override nil "A per-spawn ALIASES argument overrides the launch-aliases defcustom." (let* ((cmd (let* ((hive-mcp-cider-nrepl-launch-aliases nil))
    (hive-mcp-cider-nrepl-build-command 'clj 7999 nil '("test")))))
    (should (member "-M:test" cmd))
    (should-not (member "-M" cmd))))

(ert-deftest hive-mcp-cider-nrepl-test-launch-process-forwards-extra-args nil "launch-process forwards EXTRA-ARGS and ALIASES into the spawned argv." (let* ((dir (make-temp-file "hive-mcp-cider-nrepl-test" t))
        (captured nil))
    (unwind-protect
    (cl-letf (((symbol-function 'start-process) (lambda (name buffer &rest cmd)
    (setq captured cmd)
    'stub-process))) (should (eq 'stub-process (hive-mcp-cider-nrepl-launch-process "s" 7999 'clj dir '("-Sdeps" "{:deps {}}") '("test")))) (should (member "{:deps {}}" captured)) (should (member "-M:test" captured)))
  (delete-directory dir t))))

(ert-deftest hive-mcp-cider-nrepl-test-oom-guard-wraps-on-linux nil "On gnu/linux the argv is prefixed by a sh -c that writes the score to\n/proc/self/oom_score_adj and then execs the untouched original argv." (let* ((cmd (hive-mcp-cider-nrepl-oom-guard-command '("clojure" "-M" "a b") 500 'gnu/linux)))
    (should (equal '("sh" "-c") (list (car cmd) (car (cdr cmd)))))
    (should (string-match-p "echo 500 > /proc/self/oom_score_adj" (clel-nth cmd 2)))
    (should (string-match-p "exec \"\\$0\" \"\\$@\"" (clel-nth cmd 2)))
    (should (equal '("clojure" "-M" "a b") (cdr (cdr (cdr cmd)))))))

(ert-deftest hive-mcp-cider-nrepl-test-oom-guard-defaults-to-defcustom nil "Without ADJ the defcustom value is written." (let* ((cmd (let* ((hive-mcp-cider-nrepl-oom-score-adj 700))
    (hive-mcp-cider-nrepl-oom-guard-command '("clojure") nil 'gnu/linux))))
    (should (string-match-p "echo 700 " (clel-nth cmd 2)))))

(ert-deftest hive-mcp-cider-nrepl-test-oom-guard-degrades-silently nil "Off Linux, disabled, or out of range, the argv is returned unchanged." (let* ((argv '("clojure" "-M")))
    (should (equal argv (hive-mcp-cider-nrepl-oom-guard-command argv 500 'darwin)))
    (should (equal argv (hive-mcp-cider-nrepl-oom-guard-command argv 500 'windows-nt)))
    (should (equal argv (let* ((hive-mcp-cider-nrepl-oom-score-adj nil))
    (hive-mcp-cider-nrepl-oom-guard-command argv nil 'gnu/linux))))
    (should (equal argv (hive-mcp-cider-nrepl-oom-guard-command argv 1001 'gnu/linux)))
    (should (equal argv (hive-mcp-cider-nrepl-oom-guard-command argv -100 'gnu/linux)))
    (should-not (hive-mcp-cider-nrepl-oom-guard-command nil 500 'gnu/linux))))

(ert-deftest hive-mcp-cider-nrepl-test-launch-process-goes-through-port nil "launch-process starts its JVM through the process port, wrapped by the\nOOM guard, so the recording stub sees sh -c ... followed by the clojure argv." (let* ((dir (make-temp-file "hive-mcp-cider-nrepl-test" t))
        (calls nil))
    (unwind-protect
    (let* ((hive-mcp-cider-nrepl-process-spawner (lambda (name buffer &rest cmd)
    (setq calls (cons (list name buffer cmd) calls))
    'stub-process))
        (hive-mcp-cider-nrepl-oom-score-adj 500)
        (system-type 'gnu/linux)
        (hive-mcp-cider-nrepl-local-deps-files nil)
        (hive-mcp-cider-nrepl-launch-aliases nil))
    (should (eq 'stub-process (hive-mcp-cider-nrepl-launch-process "s" 7999 'clj dir)))
    (should (equal 1 (length calls)))
    (let* ((cmd (clel-nth (car calls) 2)))
    (should (equal "nrepl-s" (car (car calls))))
    (should (equal "sh" (car cmd)))
    (should (string-match-p "oom_score_adj" (clel-nth cmd 2)))
    (should (equal "clojure" (clel-nth cmd 3)))
    (should (member "nrepl.cmdline" cmd))))
  (delete-directory dir t))))

(ert-deftest hive-mcp-cider-nrepl-test-start-default-goes-through-port nil "The default server is spawned through the same guarded port." (let* ((dir (make-temp-file "hive-mcp-cider-nrepl-test" t))
        (captured nil))
    (unwind-protect
    (let* ((hive-mcp-cider-nrepl-process-spawner (lambda (name buffer &rest cmd)
    (setq captured (cons name cmd))
    'stub-process))
        (hive-mcp-cider-nrepl--default-process nil)
        (hive-mcp-cider-nrepl-oom-score-adj 500)
        (system-type 'gnu/linux)
        (hive-mcp-cider-nrepl-local-deps-files nil))
    (should (eq 'stub-process (hive-mcp-cider-nrepl-start-default dir)))
    (should (equal "nrepl-server" (car captured)))
    (should (equal "sh" (car (cdr captured))))
    (should (member "clojure" captured)))
  (delete-directory dir t))))

(ert-deftest hive-mcp-cider-nrepl-test-oom-guard-shell-command-wraps-on-linux nil "A jack-in shell-command string becomes sh -c <guard> sh -c <cmd>, every\nword shell-quoted, so the guard writes the score and execs the original\ncommand line unchanged." (let* ((cmd "clojure -Sdeps '{:deps {}}' -M:dev -m nrepl.cmdline")
        (wrapped (hive-mcp-cider-nrepl-oom-guard-shell-command cmd 500 'gnu/linux)))
    (should (string-prefix-p "sh -c " wrapped))
    (should (string-match-p "oom_score_adj" wrapped))
    (should (string-match-p (regexp-quote (shell-quote-argument cmd)) wrapped))
    (should (equal (mapconcat #'shell-quote-argument (hive-mcp-cider-nrepl-oom-guard-command (list "sh" "-c" cmd) 500 'gnu/linux) " ") wrapped))))

(ert-deftest hive-mcp-cider-nrepl-test-oom-guard-shell-command-degrades nil "Off Linux, disabled, empty or non-string, the command is returned unchanged." (let* ((cmd "clojure -M:dev"))
    (should (equal cmd (hive-mcp-cider-nrepl-oom-guard-shell-command cmd 500 'darwin)))
    (should (equal cmd (let* ((hive-mcp-cider-nrepl-oom-score-adj nil))
    (hive-mcp-cider-nrepl-oom-guard-shell-command cmd nil 'gnu/linux))))
    (should (equal cmd (hive-mcp-cider-nrepl-oom-guard-shell-command cmd 2000 'gnu/linux)))
    (should (equal "" (hive-mcp-cider-nrepl-oom-guard-shell-command "" 500 'gnu/linux)))
    (should-not (hive-mcp-cider-nrepl-oom-guard-shell-command nil 500 'gnu/linux))))

(defvar hive-mcp-cider-nrepl-test--jack-in-calls nil
  "Calls recorded by `hive-mcp-cider-nrepl-test--jack-in-port'.")

(defun hive-mcp-cider-nrepl-test--jack-in-port (directory cmd on-port) "Recording stub with the signature of `nrepl-start-server-process'." (setq hive-mcp-cider-nrepl-test--jack-in-calls (cons (list directory cmd on-port) hive-mcp-cider-nrepl-test--jack-in-calls)) 'stub-server)

(ert-deftest hive-mcp-cider-nrepl-test-jack-in-guard-through-port nil "Installed on the jack-in process port, the guard rewrites only CMD; the\ndirectory and callback reach the port untouched, and uninstall restores the\nbare command." (let* ((hive-mcp-cider-nrepl-test--jack-in-calls nil)
        (hive-mcp-cider-nrepl-jack-in-guard-target 'hive-mcp-cider-nrepl-test--jack-in-port)
        (hive-mcp-cider-nrepl-oom-score-adj 500)
        (system-type 'gnu/linux)
        (cb (lambda (_)
    nil)))
    (unwind-protect
    (progn
  (hive-mcp-cider-nrepl-install-jack-in-guard)
  (hive-mcp-cider-nrepl-install-jack-in-guard)
  (should (eq 'stub-server (hive-mcp-cider-nrepl-test--jack-in-port "/proj/" "clojure -M:dev" cb)))
  (let* ((call (car hive-mcp-cider-nrepl-test--jack-in-calls)))
    (should (equal "/proj/" (car call)))
    (should (eq cb (clel-nth call 2)))
    (should (string-prefix-p "sh -c " (clel-nth call 1)))
    (should (string-match-p "oom_score_adj" (clel-nth call 1)))
    (should-not (string-match-p "oom_score_adj.*oom_score_adj" (clel-nth call 1)))))
  (hive-mcp-cider-nrepl-uninstall-jack-in-guard))
    (hive-mcp-cider-nrepl-test--jack-in-port "/proj/" "clojure -M:dev" cb)
    (should (equal "clojure -M:dev" (clel-nth (car hive-mcp-cider-nrepl-test--jack-in-calls) 1)))))

(provide 'hive-mcp-cider-nrepl-test)
;;; hive-mcp-cider-nrepl-test.el ends here
