;;; hive-mcp-cider-memory-test.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(eval-and-compile (require 'clojure-elisp-runtime))
(require 'cl-lib)

;;; Code:



(require 'ert)

(require 'hive-mcp-cider-memory)

(defun hive-mcp-cider-memory-test--dict-get (d k)
  "Test shim: look up string key K in alist D of (key . value) conses."
  (cdr (assoc k d)))

(ert-deftest hive-mcp-cider-memory-test-capture-result-p nil "A result is captured when it reaches the threshold; nil never is." (should (hive-mcp-cider-memory-capture-result-p "42" 0)) (should (hive-mcp-cider-memory-capture-result-p "abcde" 5)) (should-not (hive-mcp-cider-memory-capture-result-p "abc" 5)) (should-not (hive-mcp-cider-memory-capture-result-p nil 0)))

(ert-deftest hive-mcp-cider-memory-test-merge-capture-keeps-context nil "Context recorded for an expression survives that expression's async result." (let* ((prev (list :expr "(+ 1 2)" :context (list :buffer (list :name "a.clj"))))
        (merged (hive-mcp-cider-memory-merge-capture prev "(+ 1 2)" "user" "3")))
    (should (equal "3" (plist-get merged :result)))
    (should (equal "user" (plist-get merged :ns)))
    (should (equal (plist-get prev :context) (plist-get merged :context)))))

(ert-deftest hive-mcp-cider-memory-test-merge-capture-drops-foreign-context nil "Context is not carried onto a different expression." (let* ((prev (list :expr "(+ 1 2)" :context (list :buffer (list :name "a.clj"))))
        (merged (hive-mcp-cider-memory-merge-capture prev "(* 6 7)" "user" "42")))
    (should-not (plist-get merged :context))))

(ert-deftest hive-mcp-cider-memory-test-format-entry-has-result nil "Saved content carries the real result and the captured context." (let* ((capture (list :expr "(+ 40 2)" :ns "user" :result "42" :context (list :buffer (list :name "core.clj") :project (list :name "hive"))))
        (content (hive-mcp-cider-memory-format-entry capture)))
    (should (string-match-p "Result: 42" content))
    (should-not (string-match-p "Result: nil" content))
    (should (string-match-p "Context: core.clj @ hive" content))))

(ert-deftest hive-mcp-cider-memory-test-response-result nil "A value, or a cljel session's compiled Elisp, is the result payload." (cl-letf (((symbol-function 'nrepl-dict-get) #'hive-mcp-cider-memory-test--dict-get)) (should (equal "42" (hive-mcp-cider-memory-response-result (list (cons "value" "42"))))) (should (equal "(+ 1 2)" (hive-mcp-cider-memory-response-result (list (cons "cljel-compiled-elisp" "(+ 1 2)"))))) (should-not (hive-mcp-cider-memory-response-result (list (cons "status" (list "done"))))) (should (hive-mcp-cider-memory-response-done-p (list (cons "status" (list "done"))))) (should-not (hive-mcp-cider-memory-response-done-p (list (cons "status" (list "need-input")))))))

(ert-deftest hive-mcp-cider-memory-test-capture-callback-delegates nil "The capture callback records on done and forwards every response." (let* ((seen '()))
    (cl-letf (((symbol-function 'nrepl-dict-get) #'hive-mcp-cider-memory-test--dict-get)) (setq hive-mcp-cider-memory--last-eval nil) (let* ((callback (hive-mcp-cider-memory-make-capture-callback "(+ 40 2)" "user" (lambda (response)
    (setq seen (cons response seen))))))
    (funcall callback (list (cons "value" "42")))
    (should-not hive-mcp-cider-memory--last-eval)
    (funcall callback (list (cons "status" (list "done"))))
    (should (equal "42" (plist-get hive-mcp-cider-memory--last-eval :result)))
    (should (equal 2 (length seen)))))))

(ert-deftest hive-mcp-cider-memory-test-toggle-installs-and-removes-advice nil "Toggling auto-log installs the capture advice and removes it again." (cl-letf (((symbol-function 'cider-nrepl-request:eval) (lambda (input callback &rest _args)
    (list input callback)))) (unwind-protect
    (progn
  (hive-mcp-cider-memory-disable-auto-log)
  (should-not (hive-mcp-cider-memory-auto-log-enabled-p))
  (hive-mcp-cider-memory-toggle-auto-log)
  (should (hive-mcp-cider-memory-auto-log-enabled-p))
  (should hive-mcp-cider-memory-auto-log)
  (should (advice-member-p #'hive-mcp-cider-memory-eval-request-advice 'cider-nrepl-request:eval))
  (hive-mcp-cider-memory-toggle-auto-log)
  (should-not (hive-mcp-cider-memory-auto-log-enabled-p))
  (should-not hive-mcp-cider-memory-auto-log))
  (hive-mcp-cider-memory-disable-auto-log))))

(ert-deftest hive-mcp-cider-memory-test-advice-populates-last-eval nil "With auto-log on, an eval through CIDER's request funnel fills --last-eval." (cl-letf (((symbol-function 'nrepl-dict-get) #'hive-mcp-cider-memory-test--dict-get) ((symbol-function 'cider-current-ns) (lambda ()
    "user")) ((symbol-function 'cider-nrepl-request:eval) (lambda (_input callback &rest _args)
    (funcall callback (list (cons "value" "42")))
    (funcall callback (list (cons "status" (list "done"))))
    'sent))) (unwind-protect
    (progn
  (setq hive-mcp-cider-memory--last-eval nil)
  (hive-mcp-cider-memory-enable-auto-log)
  (should (eq 'sent (cider-nrepl-request:eval "(+ 40 2)" nil)))
  (should (equal "42" (plist-get hive-mcp-cider-memory--last-eval :result)))
  (should (equal "(+ 40 2)" (plist-get hive-mcp-cider-memory--last-eval :expr)))
  (should (equal "user" (plist-get hive-mcp-cider-memory--last-eval :ns))))
  (hive-mcp-cider-memory-disable-auto-log))))

(ert-deftest hive-mcp-cider-memory-test-advice-captures-cljel-result nil "A cljel session answers with compiled Elisp and is captured all the same." (cl-letf (((symbol-function 'nrepl-dict-get) #'hive-mcp-cider-memory-test--dict-get) ((symbol-function 'cider-current-ns) (lambda ()
    "user")) ((symbol-function 'cider-nrepl-request:eval) (lambda (_input callback &rest _args)
    (funcall callback (list (cons "cljel-compiled-elisp" "(message \"hi\")") (cons "status" (list "done"))))))) (unwind-protect
    (progn
  (setq hive-mcp-cider-memory--last-eval nil)
  (hive-mcp-cider-memory-enable-auto-log)
  (cider-nrepl-request:eval "(message \"hi\")" nil)
  (should (equal "(message \"hi\")" (plist-get hive-mcp-cider-memory--last-eval :result))))
  (hive-mcp-cider-memory-disable-auto-log))))

(ert-deftest hive-mcp-cider-memory-test-advice-off-captures-nothing nil "Without the advice installed the funnel is untouched and nothing is captured." (cl-letf (((symbol-function 'nrepl-dict-get) #'hive-mcp-cider-memory-test--dict-get) ((symbol-function 'cider-nrepl-request:eval) (lambda (_input callback &rest _args)
    (when callback
    (funcall callback (list (cons "value" "99") (cons "status" (list "done")))))
    'sent))) (hive-mcp-cider-memory-disable-auto-log) (setq hive-mcp-cider-memory--last-eval nil) (cider-nrepl-request:eval "(+ 98 1)" nil) (should-not hive-mcp-cider-memory--last-eval)))

(ert-deftest hive-mcp-cider-memory-test-save-last-result-persists-value nil "Save last result persists the captured value and context, never \"nil\"." (let* ((saved nil))
    (cl-letf (((symbol-function 'hive-mcp-api-memory-add) (lambda (type content tags)
    (setq saved (list type content tags)))) ((symbol-function 'read-string) (lambda (&rest _args)
    "clojure,repl")) ((symbol-function 'clel-read-string) (lambda (&rest _args)
    "clojure,repl"))) (setq hive-mcp-cider-memory--last-eval (list :expr "(+ 40 2)" :ns "user" :result "42" :context (list :buffer (list :name "core.clj") :project (list :name "hive")))) (hive-mcp-cider-memory-save-last-result) (should (equal "snippet" (clel-nth saved 0))) (should (string-match-p "Result: 42" (clel-nth saved 1))) (should (string-match-p "Context: core.clj @ hive" (clel-nth saved 1))) (should (equal '("clojure" "repl") (clel-nth saved 2))))))

(ert-deftest hive-mcp-cider-memory-test-save-last-result-without-capture nil "With nothing captured, save is a no-op rather than a nil snippet." (let* ((saved nil))
    (cl-letf (((symbol-function 'hive-mcp-api-memory-add) (lambda (&rest args)
    (setq saved args)))) (setq hive-mcp-cider-memory--last-eval nil) (hive-mcp-cider-memory-save-last-result) (should-not saved))))

(ert-deftest hive-mcp-cider-memory-test-save-defun-saves-buffer-text nil "Save defun persists the function at point." (let* ((saved nil)
        (buf (generate-new-buffer " *defun-src*")))
    (unwind-protect
    (cl-letf (((symbol-function 'hive-mcp-api-memory-add) (lambda (type content tags)
    (setq saved (list type content tags)))) ((symbol-function 'read-string) (lambda (&rest _args)
    "clojure,function")) ((symbol-function 'clel-read-string) (lambda (&rest _args)
    "clojure,function"))) (with-current-buffer buf
    (insert "(defn probe [x] (inc x))")
    (goto-char (point-min))
    (hive-mcp-cider-memory-save-defun)) (should (equal "snippet" (clel-nth saved 0))) (should (string-match-p "defn probe" (clel-nth saved 1))) (should (equal '("clojure" "function") (clel-nth saved 2))))
  (kill-buffer buf))))

(ert-deftest hive-mcp-cider-memory-test-query-plan-routes-free-text nil "Free text goes to semantic search, or becomes tags when it cannot." (let* ((semantic (hive-mcp-cider-memory-query-plan "lazy seq chunking" 20 t))
        (tagged (hive-mcp-cider-memory-query-plan "lazy seq" 20 nil))
        (empty (hive-mcp-cider-memory-query-plan "" 20 t)))
    (should (eq 'semantic (plist-get semantic :mode)))
    (should (equal "lazy seq chunking" (plist-get semantic :query)))
    (should (equal 20 (plist-get semantic :limit)))
    (should (eq 'tags (plist-get tagged :mode)))
    (should (equal '("clojure" "lazy" "seq") (plist-get tagged :tags)))
    (should (eq 'tags (plist-get empty :mode)))
    (should (equal '("clojure") (plist-get empty :tags)))))

(ert-deftest hive-mcp-cider-memory-test-run-plan-sends-query nil "The semantic plan sends the query text; the tag plan sends the tags." (let* ((sent nil))
    (cl-letf (((symbol-function 'hive-mcp-memory-search) (lambda (query project-id limit)
    (setq sent (list 'semantic query project-id limit))
    '())) ((symbol-function 'hive-mcp-api-memory-query) (lambda (type tags limit)
    (setq sent (list 'tags type tags limit))
    (list )))) (hive-mcp-cider-memory-run-plan (hive-mcp-cider-memory-query-plan "transducers" 20 t)) (should (equal '(semantic "transducers" nil 20) sent)) (hive-mcp-cider-memory-run-plan (hive-mcp-cider-memory-query-plan "transducers" 20 nil)) (should (equal '(tags "snippet" ("clojure" "transducers") 20) sent)))))

(ert-deftest hive-mcp-cider-memory-test-query-solutions-passes-query nil "The typed query reaches the backend instead of a hardcoded tag list." (let* ((sent nil))
    (cl-letf (((symbol-function 'hive-mcp-memory-search) (lambda (query _project-id limit)
    (setq sent (list query limit))
    (list (list :content "(map inc coll)" :tags '("clojure"))))) ((symbol-function 'display-buffer) (lambda (buf)
    buf))) (let* ((buf (hive-mcp-cider-memory-query-solutions "transducer completing")))
    (should (equal (list "transducer completing" hive-mcp-cider-memory-query-limit) sent))
    (with-current-buffer buf
    (should (string-match-p "transducer completing" (buffer-string)))
    (should (string-match-p "(map inc coll)" (buffer-string))))
    (kill-buffer buf)))))

(ert-deftest hive-mcp-cider-memory-test-entry-field-shapes nil "Entries read the same whether the backend returns alists or plists." (should (equal "alist body" (hive-mcp-cider-memory-entry-field (list (cons 'content "alist body") (cons 'tags '("a"))) 'content))) (should (equal "plist body" (hive-mcp-cider-memory-entry-field (list :content "plist body" :tags '("a")) 'content))) (should-not (hive-mcp-cider-memory-entry-field nil 'content)))

(ert-deftest hive-mcp-cider-memory-test-entry-seq-normalizes nil "Vector results and list results normalize to the same sequence." (should (equal '(1 2 3) (hive-mcp-cider-memory-entry-seq (list 1 2 3)))) (should (equal '(1 2 3) (hive-mcp-cider-memory-entry-seq '(1 2 3)))) (should (equal '() (hive-mcp-cider-memory-entry-seq nil))))

(ert-deftest hive-mcp-cider-memory-test-render-entries-empty nil "An empty result set says so instead of rendering an empty listing." (should (string-match-p "No solutions found" (hive-mcp-cider-memory-render-entries (hive-mcp-cider-memory-query-plan "nothing" 20 t) '()))))

(defun hive-mcp-cider-memory-test-run-tests ()
  "Run all hive-mcp-cider-memory ERT tests in batch."
  (interactive)
  (ert-run-tests-batch-and-exit "^hive-mcp-cider-memory-test-"))

(provide 'hive-mcp-cider-memory-test)
;;; hive-mcp-cider-memory-test.el ends here
