;;; hive-mcp-swarm-events.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(require 'clojure-elisp-runtime)

;;; Code:



(require 'cl-lib)

(declare-function hive-mcp-channel-connected-p "hive-mcp-channel")

(declare-function hive-mcp-channel-send "hive-mcp-channel")

(declare-function hive-mcp-channel-dispatch-local "hive-mcp-channel")

(defvar hive-mcp-swarm-events--session-id nil
  "Current session ID for event correlation.")

(defun hive-mcp-swarm-events-channel-available-p ()
  "Check if the bidirectional channel is available and connected."
  (and (require 'hive-mcp-channel nil t) (fboundp 'hive-mcp-channel-connected-p) (hive-mcp-channel-connected-p)))

(defun hive-mcp-swarm-events-emit (event-type data)
  "Emit EVENT-TYPE with DATA through the channel if connected.\nEVENT-TYPE should be a string like \"task-completed\".\nDATA is an alist of additional event properties.\n\nEvents are both:\n1. Sent to MCP server via channel (if connected)\n2. Dispatched locally to elisp handlers (always)\n\nThis enables components like hive-mcp-olympus to react immediately\nto swarm events without waiting for server round-trip."
  (let* ((event (clel-seq (clel-concat (clojure-core-list (clel-seq (clel-concat (clojure-core-list "type") (clojure-core-list '.) (clojure-core-list 'user/event-type)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "timestamp") (clojure-core-list '.) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'user/truncate) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'user/float-time)))))))))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "session-id") (clojure-core-list '.) (clojure-core-list 'user/hive-mcp-swarm-events--session-id)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/deref) (clojure-core-list 'user/data))))))))
    (when (fboundp 'hive-mcp-channel-dispatch-local)
    (condition-case err
    (hive-mcp-channel-dispatch-local event-type event)
  (error (message "[swarm-events] Local dispatch error: %s" (error-message-string err)))))
    (when (hive-mcp-swarm-events-channel-available-p)
    (condition-case err
    (hive-mcp-channel-send event)
  (error (message "[swarm-events] Channel emit error: %s" (error-message-string err)))))))

(defun hive-mcp-swarm-events-emit-slave-spawned (slave-id name presets &optional cwd kanban-task-id)
  "Emit slave-spawned event for SLAVE-ID with NAME, PRESETS, CWD, and KANBAN-TASK-ID.\nCWD is the working directory of the slave (optional but recommended for\nregistry sync per ADR-001 Phase 2).\nKANBAN-TASK-ID is the optional kanban task this ling is linked to."
  (hive-mcp-swarm-events-emit "slave-spawned" (clel-seq (clel-concat (clojure-core-list (clel-seq (clel-concat (clojure-core-list "slave-id") (clojure-core-list '.) (clojure-core-list 'user/slave-id)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "name") (clojure-core-list '.) (clojure-core-list 'clojure.core/name)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "presets") (clojure-core-list '.) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/or) (clojure-core-list 'user/presets) (clojure-core-list (apply clojure-core-vector (clel-seq (clel-concat)))))))))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "cwd") (clojure-core-list '.) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/or) (clojure-core-list 'user/cwd) (clojure-core-list ""))))))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/deref) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/when) (clojure-core-list 'user/kanban-task-id) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/seq) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/concat) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/list) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/seq) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/concat) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/list) (clojure-core-list "kanban-task-id")))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/list) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'quote) (clojure-core-list '.))))))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/list) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'quote) (clojure-core-list 'user/kanban-task-id))))))))))))))))))))))))))))))))

(defun hive-mcp-swarm-events-emit-slave-killed (slave-id)
  "Emit slave-killed event for SLAVE-ID."
  (hive-mcp-swarm-events-emit "slave-killed" (clel-seq (clel-concat (clojure-core-list (clel-seq (clel-concat (clojure-core-list "slave-id") (clojure-core-list '.) (clojure-core-list 'user/slave-id))))))))

(defun hive-mcp-swarm-events-emit-slave-ready (slave-id)
  "Emit slave-ready event for SLAVE-ID.\nThis signals that preset injection is complete and the slave is ready\nto receive dispatched tasks."
  (hive-mcp-swarm-events-emit "slave-ready" (clel-seq (clel-concat (clojure-core-list (clel-seq (clel-concat (clojure-core-list "slave-id") (clojure-core-list '.) (clojure-core-list 'user/slave-id))))))))

(defun hive-mcp-swarm-events-emit-task-completed (task-id slave-id result)
  "Emit task-completed event for TASK-ID from SLAVE-ID with RESULT."
  (hive-mcp-swarm-events-emit "task-completed" (clel-seq (clel-concat (clojure-core-list (clel-seq (clel-concat (clojure-core-list "task-id") (clojure-core-list '.) (clojure-core-list 'user/task-id)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "slave-id") (clojure-core-list '.) (clojure-core-list 'user/slave-id)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "result") (clojure-core-list '.) (clojure-core-list 'user/result))))))))

(defun hive-mcp-swarm-events-emit-task-failed (task-id slave-id error-msg)
  "Emit task-failed event for TASK-ID from SLAVE-ID with ERROR-MSG."
  (hive-mcp-swarm-events-emit "task-failed" (clel-seq (clel-concat (clojure-core-list (clel-seq (clel-concat (clojure-core-list "task-id") (clojure-core-list '.) (clojure-core-list 'user/task-id)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "slave-id") (clojure-core-list '.) (clojure-core-list 'user/slave-id)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "error") (clojure-core-list '.) (clojure-core-list 'user/error-msg))))))))

(defun hive-mcp-swarm-events-emit-prompt-shown (slave-id prompt-text)
  "Emit prompt-shown event for SLAVE-ID with PROMPT-TEXT."
  (hive-mcp-swarm-events-emit "prompt-shown" (clel-seq (clel-concat (clojure-core-list (clel-seq (clel-concat (clojure-core-list "slave-id") (clojure-core-list '.) (clojure-core-list 'user/slave-id)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "prompt") (clojure-core-list '.) (clojure-core-list 'user/prompt-text))))))))

(defun hive-mcp-swarm-events-emit-state-changed (slave-id old-state new-state)
  "Emit state-changed event for SLAVE-ID from OLD-STATE to NEW-STATE."
  (hive-mcp-swarm-events-emit "state-changed" (clel-seq (clel-concat (clojure-core-list (clel-seq (clel-concat (clojure-core-list "slave-id") (clojure-core-list '.) (clojure-core-list 'user/slave-id)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "old-state") (clojure-core-list '.) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'user/symbol-name) (clojure-core-list 'user/old-state))))))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "new-state") (clojure-core-list '.) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'user/symbol-name) (clojure-core-list 'user/new-state)))))))))))

(defun hive-mcp-swarm-events-emit-auto-completed (slave-id duration-secs status)
  "Emit auto-completed event for SLAVE-ID with DURATION-SECS and STATUS.\nSTATUS should be a string like \"completed\", \"unknown\", etc.\nDURATION-SECS is the task duration in seconds (float)."
  (hive-mcp-swarm-events-emit "auto-completed" (clel-seq (clel-concat (clojure-core-list (clel-seq (clel-concat (clojure-core-list "slave-id") (clojure-core-list '.) (clojure-core-list 'user/slave-id)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "duration-secs") (clojure-core-list '.) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/or) (clojure-core-list 'user/duration-secs) (clojure-core-list 0))))))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "status") (clojure-core-list '.) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/or) (clojure-core-list 'user/status) (clojure-core-list "completed"))))))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "detection-method") (clojure-core-list '.) (clojure-core-list "terminal-ready-transition"))))))))

(defun hive-mcp-swarm-events-emit-auto-started (slave-id task-preview)
  "Emit auto-started event for SLAVE-ID with TASK-PREVIEW.\nTASK-PREVIEW is a truncated version of the task prompt (first 100 chars)."
  (hive-mcp-swarm-events-emit "auto-started" (clel-seq (clel-concat (clojure-core-list (clel-seq (clel-concat (clojure-core-list "slave-id") (clojure-core-list '.) (clojure-core-list 'user/slave-id)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "task-preview") (clojure-core-list '.) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/or) (clojure-core-list 'user/task-preview) (clojure-core-list ""))))))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "detection-method") (clojure-core-list '.) (clojure-core-list "terminal-send"))))))))

(defun hive-mcp-swarm-events-emit-auto-error (slave-id duration-secs error-type error-preview)
  "Emit auto-error event for SLAVE-ID with error details.\nDURATION-SECS is the task duration before error (float).\nERROR-TYPE is a string like \"cli-error\", \"tool-error\", \"timeout\".\nERROR-PREVIEW is a truncated version of the error text (first 200 chars)."
  (hive-mcp-swarm-events-emit "auto-error" (clel-seq (clel-concat (clojure-core-list (clel-seq (clel-concat (clojure-core-list "slave-id") (clojure-core-list '.) (clojure-core-list 'user/slave-id)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "duration-secs") (clojure-core-list '.) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/or) (clojure-core-list 'user/duration-secs) (clojure-core-list 0))))))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "error-type") (clojure-core-list '.) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/or) (clojure-core-list 'user/error-type) (clojure-core-list "unknown"))))))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "error-preview") (clojure-core-list '.) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/or) (clojure-core-list 'user/error-preview) (clojure-core-list ""))))))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "detection-method") (clojure-core-list '.) (clojure-core-list "terminal-pattern-match"))))))))

(defun hive-mcp-swarm-events-emit-idle-timeout (slave-id idle-duration-secs)
  "Emit idle-timeout event for SLAVE-ID (Layer 2 convergence).\nIDLE-DURATION-SECS is how long the slave has been idle (float)."
  (hive-mcp-swarm-events-emit "idle-timeout" (clel-seq (clel-concat (clojure-core-list (clel-seq (clel-concat (clojure-core-list "slave-id") (clojure-core-list '.) (clojure-core-list 'user/slave-id)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "idle-duration-secs") (clojure-core-list '.) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/or) (clojure-core-list 'user/idle-duration-secs) (clojure-core-list 0))))))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "detection-method") (clojure-core-list '.) (clojure-core-list "terminal-introspection")))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "layer") (clojure-core-list '.) (clojure-core-list 2)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "convergence-pattern") (clojure-core-list '.) (clojure-core-list "4-layer-convergence"))))))))

(defun hive-mcp-swarm-events-emit-prompt-stall (slave-id idle-duration-secs prompt-text)
  "Emit prompt-stall event for SLAVE-ID (Layer 2 convergence).\nIDLE-DURATION-SECS is how long the slave has been idle (float).\nPROMPT-TEXT is the pending prompt text (truncated if long).\nThis event is URGENT - the coordinator needs to respond."
  (hive-mcp-swarm-events-emit "prompt-stall" (clel-seq (clel-concat (clojure-core-list (clel-seq (clel-concat (clojure-core-list "slave-id") (clojure-core-list '.) (clojure-core-list 'user/slave-id)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "idle-duration-secs") (clojure-core-list '.) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/or) (clojure-core-list 'user/idle-duration-secs) (clojure-core-list 0))))))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "prompt-preview") (clojure-core-list '.) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'if) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/>) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'user/length) (clojure-core-list 'user/prompt-text)))) (clojure-core-list 100)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/concat) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'user/substring) (clojure-core-list 'user/prompt-text) (clojure-core-list 0) (clojure-core-list 97)))) (clojure-core-list "...")))) (clojure-core-list 'user/prompt-text))))))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "detection-method") (clojure-core-list '.) (clojure-core-list "idle-with-pending-prompt")))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "layer") (clojure-core-list '.) (clojure-core-list 2)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "convergence-pattern") (clojure-core-list '.) (clojure-core-list "4-layer-convergence")))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "urgency") (clojure-core-list '.) (clojure-core-list "high"))))))))

(defun hive-mcp-swarm-events-emit-ling-ready-for-wrap (slave-id reason)
  "Emit ling-ready-for-wrap event for SLAVE-ID with REASON.\nREASON is a string describing why wrap is triggered."
  (hive-mcp-swarm-events-emit "ling-ready-for-wrap" (clel-seq (clel-concat (clojure-core-list (clel-seq (clel-concat (clojure-core-list "slave-id") (clojure-core-list '.) (clojure-core-list 'user/slave-id)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "reason") (clojure-core-list '.) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/or) (clojure-core-list 'user/reason) (clojure-core-list "task-completed"))))))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "session-id") (clojure-core-list '.) (clojure-core-list 'user/hive-mcp-swarm-events--session-id))))))))

(defun hive-mcp-swarm-events-emit-dispatch-dropped (slave-id reason prompt-preview retries queued-at)
  "Emit dispatch-dropped event for SLAVE-ID with failure details.\nREASON is a string describing why the dispatch was dropped.\nPROMPT-PREVIEW is a truncated version of the prompt (first 100 chars).\nRETRIES is the number of retry attempts made.\nQUEUED-AT is the epoch time when the dispatch was queued."
  (let* ((wait-time (- (float-time) (or queued-at (float-time)))))
    (hive-mcp-swarm-events-emit "dispatch-dropped" (clel-seq (clel-concat (clojure-core-list (clel-seq (clel-concat (clojure-core-list "slave-id") (clojure-core-list '.) (clojure-core-list 'user/slave-id)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "reason") (clojure-core-list '.) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/or) (clojure-core-list 'user/reason) (clojure-core-list "unknown"))))))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "prompt-preview") (clojure-core-list '.) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'if) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/>) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'user/length) (clojure-core-list 'user/prompt-preview)))) (clojure-core-list 100)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/concat) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'user/substring) (clojure-core-list 'user/prompt-preview) (clojure-core-list 0) (clojure-core-list 97)))) (clojure-core-list "...")))) (clojure-core-list 'user/prompt-preview))))))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "retries") (clojure-core-list '.) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/or) (clojure-core-list 'user/retries) (clojure-core-list 0))))))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "queued-at") (clojure-core-list '.) (clojure-core-list (clel-seq (clel-concat (clojure-core-list 'clojure.core/or) (clojure-core-list 'user/queued-at) (clojure-core-list 0))))))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "wait-time-secs") (clojure-core-list '.) (clojure-core-list 'user/wait-time)))) (clojure-core-list (clel-seq (clel-concat (clojure-core-list "urgency") (clojure-core-list '.) (clojure-core-list "high")))))))))

(defun hive-mcp-swarm-events-set-session-id (session-id)
  "Set the SESSION-ID for event correlation."
  (setq hive-mcp-swarm-events--session-id session-id))

(defun hive-mcp-swarm-events-get-session-id ()
  "Get the current session ID."
  hive-mcp-swarm-events--session-id)

(defun hive-mcp-swarm-events-init (session-id)
  "Initialize events module with SESSION-ID."
  (setq hive-mcp-swarm-events--session-id session-id))

(defun hive-mcp-swarm-events-shutdown ()
  "Shutdown events module."
  (setq hive-mcp-swarm-events--session-id nil))

(provide 'hive-mcp-swarm-events)
;;; hive-mcp-swarm-events.el ends here
