;;; hive-mcp-swarm-hooks.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(require 'clojure-elisp-runtime)

;;; Code:



(require 'cl-lib)

(defvar hive-mcp-swarm-hooks--registry nil
  "Alist of event-type -> list of handler functions.\nEach handler receives the event data as its argument.\nStructure: ((event-type . (handler1 handler2 ...)) ...)")

(defun hive-mcp-swarm-hooks-register (event-type handler)
  "Register HANDLER function for EVENT-TYPE events.\nHANDLER should be a function that accepts one argument: event data.\nMultiple handlers can be registered for the same event type.\nReturns t on successful registration."
  (unless (functionp handler)
    (error "Handler must be a function"))
  (let* ((existing (assq event-type hive-mcp-swarm-hooks--registry)))
    (if existing (unless (memq handler (cdr existing))
    (setcdr existing (cons handler (cdr existing)))) (push (cons event-type (hive-mcp-swarm-hooks-list handler)) hive-mcp-swarm-hooks--registry)))
  t)

(defun hive-mcp-swarm-hooks-unregister (event-type handler)
  "Unregister HANDLER from EVENT-TYPE events.\nReturns t if handler was found and removed, nil otherwise."
  (let* ((existing (assq event-type hive-mcp-swarm-hooks--registry)))
    (when existing
    (let* ((handlers (cdr existing)))
    (when (memq handler handlers)
    (setcdr existing (delq handler handlers))
    (when (null (cdr existing))
    (setq hive-mcp-swarm-hooks--registry (assq-delete-all event-type hive-mcp-swarm-hooks--registry)))
    t)))))

(defun hive-mcp-swarm-hooks-dispatch (event-type data)
  "Dispatch EVENT-TYPE event with DATA to all registered handlers.\nReturns the number of handlers that were invoked.\nErrors in handlers are caught and logged to *Messages*."
  (let* ((existing (assq event-type hive-mcp-swarm-hooks--registry))
        (count 0))
    (when existing
    (dolist (handler (cdr existing))
    (condition-case err
    (progn
  (funcall handler data)
  (cl-incf count))
  (error (message "[swarm-hooks] Handler error for %s: %s" event-type (error-message-string err))))))
    count))

(defun hive-mcp-swarm-hooks-clear ()
  "Clear all registered hooks.\nUse for testing or shutdown."
  (setq hive-mcp-swarm-hooks--registry nil))

(defun hive-mcp-swarm-hooks-list ()
  "Return the current hook registry for inspection.\nUseful for debugging."
  hive-mcp-swarm-hooks--registry)

(defun hive-mcp-swarm-hooks-init ()
  "Initialize hooks module.\nCalled during swarm addon startup."
  nil)

(defun hive-mcp-swarm-hooks-shutdown ()
  "Shutdown hooks module.\nClears all registered hooks."
  (hive-mcp-swarm-hooks-clear))

(provide 'hive-mcp-swarm-hooks)
;;; hive-mcp-swarm-hooks.el ends here
