;;; hive-mcp-hivemind.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(require 'clojure-elisp-runtime)

;;; Code:



(require 'hive-mcp-channel)

(require 'hive-mcp-channel-ws)

(declare-function hive-mcp-swarm-hooks-dispatch "hive-mcp-swarm-hooks")

(defgroup hive-mcp-hivemind nil
  "Hivemind coordinator for swarm agents."
  :group 'hive-mcp
  :prefix "hive-mcp-hivemind-")

(defcustom hive-mcp-hivemind-notify-events '(:hivemind-ask :hivemind-error :hivemind-blocked)
  "Event types that trigger desktop notifications."
  :group 'hive-mcp-hivemind
  :type '(repeat symbol))

(defcustom hive-mcp-hivemind-log-buffer "*Hivemind Log*"
  "Buffer name for hivemind activity log."
  :group 'hive-mcp-hivemind
  :type 'string)

(defvar hive-mcp-hivemind--agents (make-hash-table :test 'equal)
  "Hash table of agent-id -> status info.")

(defvar hive-mcp-hivemind--pending-asks nil)

(defun hive-mcp-hivemind--log (event-type agent-id message)
  "Log EVENT-TYPE from AGENT-ID with MESSAGE to the hivemind log buffer."
  (with-current-buffer (get-buffer-create hive-mcp-hivemind-log-buffer)
    (goto-char (point-max))
    (insert (format "[%s] %s (%s): %s\n" (format-time-string "%H:%M:%S") event-type (or agent-id "unknown") (or message "")))))

(defun hive-mcp-hivemind--notify (agent-id event-type message)
  "Show desktop notification for EVENT-TYPE from AGENT-ID."
  (when (fboundp 'notifications-notify)
    (notifications-notify :title (format "Hivemind: %s" event-type) :body (format "[%s] %s" agent-id (or message "")) :urgency (if (string-match-p "ask\\|error\\|blocked" (downcase (or event-type ""))) 'critical 'normal))))

(defun hive-mcp-hivemind--handle-shout (event)
  "Handle a hivemind shout EVENT from an agent."
  (let* ((agent-id (or (alist-get 'agent-id event) (cdr (clel-assoc "agent-id" event))))
        (data (or (alist-get 'data event) (cdr (clel-assoc "data" event))))
        (event-type (or (alist-get 'type event) (cdr (clel-assoc "type" event))))
        (timestamp (or (alist-get 'timestamp event) (cdr (clel-assoc "timestamp" event))))
        (task (or (alist-get 'task data) (cdr (clel-assoc "task" data))))
        (message (or (alist-get 'message data) (cdr (clel-assoc "message" data)))))
    (puthash agent-id (list :status event-type :task task :message message :last-seen (or timestamp (float-time))) hive-mcp-hivemind--agents)
    (hive-mcp-hivemind--log event-type agent-id (or message task))
    (when (member (intern event-type) hive-mcp-hivemind-notify-events)
    (hive-mcp-hivemind--notify agent-id event-type message))
    (when (fboundp 'hive-mcp-swarm-hooks-dispatch)
    (hive-mcp-swarm-hooks-dispatch (intern (clel-concat ":" event-type)) (list :agent-id agent-id :event-type event-type :task task :message message :data data :timestamp (or timestamp (float-time)))))))

(defun hive-mcp-hivemind--handle-ask (event)
  "Handle a hivemind ask EVENT requiring human response."
  (let* ((ask-id (or (alist-get 'ask-id event) (cdr (clel-assoc "ask-id" event))))
        (agent-id (or (alist-get 'agent-id event) (cdr (clel-assoc "agent-id" event))))
        (question (or (alist-get 'question event) (cdr (clel-assoc "question" event))))
        (options (or (alist-get 'options event) (cdr (clel-assoc "options" event)))))
    (push (list :ask-id ask-id :agent-id agent-id :question question :options options :timestamp (float-time)) hive-mcp-hivemind--pending-asks)
    (hive-mcp-hivemind--log "ASK" agent-id question)
    (hive-mcp-hivemind--notify agent-id "NEEDS INPUT" question)
    (message "HIVEMIND ASK [%s]: %s" agent-id question)))

(defun hive-mcp-hivemind-status ()
  "Show current hivemind status in a buffer."
  (interactive)
  (with-current-buffer (get-buffer-create "*Hivemind Status*")
    (erase-buffer)
    (insert "=== HIVEMIND STATUS ===\n\n")
    (insert "AGENTS:\n")
    (if (zerop (hash-table-count hive-mcp-hivemind--agents)) (insert "  (no agents registered)\n") (maphash (lambda (id info)
    (insert (format "  %s: %s - %s\n" id (plist-get info :status) (or (plist-get info :task) "")))) hive-mcp-hivemind--agents))
    (insert "\nPENDING QUESTIONS:\n")
    (if (null hive-mcp-hivemind--pending-asks) (insert "  (none)\n") (dolist (ask hive-mcp-hivemind--pending-asks)
    (insert (format "  [%s] %s: %s\n" (plist-get ask :ask-id) (plist-get ask :agent-id) (plist-get ask :question)))))
    (display-buffer (current-buffer))))

(defun hive-mcp-hivemind-respond (ask-id response)
  "Respond to ASK-ID with RESPONSE."
  (interactive (let* ((asks hive-mcp-hivemind--pending-asks)
        (ask (if (equal 1 (length asks)) (car asks) (let* ((id (completing-read "Ask ID: " (mapcar (lambda (a)
    (plist-get a :ask-id)) asks))))
    (seq-find (lambda (a)
    (string= (plist-get a :ask-id) id)) asks))))
        (options (plist-get ask :options))
        (resp (if options (completing-read (format "%s: " (plist-get ask :question)) options) (clel-read-string (format "%s: " (plist-get ask :question))))))
    (list (plist-get ask :ask-id) resp)))
  (if (hive-mcp-channel-ws-connected-p) (hive-mcp-channel-ws-send (list (cons 'type "hivemind-response") (cons 'ask-id ask-id) (cons 'decision response) (cons 'by "human"))) (hive-mcp-channel-send (list (cons "type" "hivemind-response") (cons "ask-id" ask-id) (cons "decision" response) (cons "by" "human"))))
  (setq hive-mcp-hivemind--pending-asks (seq-remove (lambda (a)
    (string= (plist-get a :ask-id) ask-id)) hive-mcp-hivemind--pending-asks))
  (message "Responded to %s: %s" ask-id response))

(defun hive-mcp-hivemind-show-log ()
  "Show the hivemind activity log."
  (interactive)
  (display-buffer (get-buffer-create hive-mcp-hivemind-log-buffer)))

(defun hive-mcp-hivemind-clear ()
  "Clear hivemind state (for debugging)."
  (interactive)
  (clrhash hive-mcp-hivemind--agents)
  (setq hive-mcp-hivemind--pending-asks nil)
  (message "Hivemind state cleared"))

(defun hive-mcp-hivemind-register-handlers ()
  "Register hivemind event handlers with the channel."
  (dolist (type '("hivemind-progress" "hivemind-completed" "hivemind-error" "hivemind-blocked" "hivemind-started"))
    (hive-mcp-channel-ws-on type #'hive-mcp-hivemind--handle-shout))
  (hive-mcp-channel-ws-on "hivemind-ask" #'hive-mcp-hivemind--handle-ask)
  (dolist (type '(:hivemind-progress :hivemind-completed :hivemind-error :hivemind-blocked :hivemind-started))
    (hive-mcp-channel-on type #'hive-mcp-hivemind--handle-shout))
  (hive-mcp-channel-on :hivemind-ask #'hive-mcp-hivemind--handle-ask))

(hive-mcp-hivemind-register-handlers)

(provide 'hive-mcp-hivemind)

(provide 'hive-mcp-hivemind)
;;; hive-mcp-hivemind.el ends here
