;;; hive-mcp-kanban-protocol.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(require 'clojure-elisp-runtime)
(require 'cl-lib)

;;; Code:



(cl-defgeneric -list-projects (list backend) "List all projects from BACKEND.\n\nReturns a list of alists, each with at least:\n  - `id': Unique project identifier\n  - `name': Human-readable project name\n\nExample return value:\n  (((id . \"uuid-1\") (name . \"Project Alpha\"))\n   ((id . \"uuid-2\") (name . \"Project Beta\")))")

(cl-defgeneric -list-tasks (list backend project-id &optional status) "List tasks from BACKEND for PROJECT-ID.\n\nPROJECT-ID identifies the project (may be nil for some backends).\nSTATUS optionally filters by kanban status (e.g., \"todo\", \"inprogress\").\n\nReturns a list of task alists, each with:\n  - `id': Unique task identifier\n  - `title': Task title\n  - `status': Kanban status (\"todo\", \"inprogress\", \"inreview\", \"done\")\n  - `description': Optional task description\n  - `agent': Optional agent identifier that created/modified task\n  - `session': Optional session identifier")

(cl-defgeneric -get-task (list backend task-id) "Get task details from BACKEND by TASK-ID.\n\nReturns a single task alist with full details:\n  - `id': Task identifier\n  - `title': Task title\n  - `status': Kanban status\n  - `description': Full description\n  - `agent': Creating agent\n  - `session': Creating session\n  - `created': Creation timestamp\n  - `updated': Last update timestamp\n\nReturns nil if task not found.")

(cl-defgeneric -create-task (list backend project-id title &optional description) "Create task in BACKEND for PROJECT-ID with TITLE.\n\nDESCRIPTION is optional task description.\nPROJECT-ID may be nil for backends that support a default project.\n\nReturns alist with at least:\n  - `id': Newly created task identifier")

(cl-defgeneric -update-task (list backend task-id &rest props) "Update TASK-ID in BACKEND with PROPS.\n\nPROPS is a plist with optional keys:\n  - `:title': New title\n  - `:description': New description\n  - `:status': New kanban status\n\nReturns non-nil on success.")

(cl-defgeneric -delete-task (list backend task-id) "Delete TASK-ID from BACKEND.\n\nReturns non-nil on success.")

(defcustom status-map '(("TODO" . "todo") ("IN-PROGRESS" . "inprogress") ("IN-REVIEW" . "inreview") ("DONE" . "done") ("CANCELLED" . "cancelled"))
  "Map org TODO states to vibe-kanban statuses.\nUsed for backend interoperability."
  :group 'hive-mcp-kanban
  :type '(alist :key-type string :value-type string))

(defun hive-mcp-kanban-protocol--org-to-vibe-status (org-status)
  "Convert ORG-STATUS to vibe-kanban status."
  (or (cdr (clel-assoc org-status hive-mcp-kanban-protocol-status-map)) "todo"))

(defun hive-mcp-kanban-protocol--vibe-to-org-status (vibe-status)
  "Convert VIBE-STATUS to org TODO state."
  (or (car (rassoc vibe-status hive-mcp-kanban-protocol-status-map)) "TODO"))

(defcustom track-agents t
  "When non-nil, track which agent (session) worked on tasks."
  :group 'hive-mcp-kanban
  :type 'boolean)

(defun hive-mcp-kanban-protocol--current-agent ()
  "Get current agent identifier.\nUses CLAUDE_SESSION_ID env var if available, else emacs PID."
  (or (getenv "CLAUDE_SESSION_ID") (format "emacs-%s" (emacs-pid))))

(defun hive-mcp-kanban-protocol--current-session ()
  "Get current session identifier (timestamp-based)."
  (format-time-string "%Y%m%d-%H%M%S"))

(provide 'hive-mcp-kanban-protocol)
;;; hive-mcp-kanban-protocol.el ends here
